### ISSUE TITLE
Parsian Paymnet,Invalid Token

### ISSUE THREAD

**Issue by amousavii** [shetabit/payment#100]
متاسفانه بعد از ریدارکت به صفحه پرداخت درگاه بانک پارسیان با خطای زیر مواجه میشم :
  
  
![Screenshot_20200905_133143](https://user-images.githubusercontent.com/43773690/92302271-15464300-ef80-11ea-8639-dce54ce70e49.png)

  
  کد انتقال به بانک  :
  
          $invoice = (new Invoice)->amount(1000);
        return Payment::callbackUrl('https://xyz.com/parsianResult')->via('parsian')->purchase($invoice, function ($driver, $transactionId) {

        `})->pay()->render();`

نسخه پکیج 4.0
نسخه PHP 7.2
با پشتیبانی بانک تماس گرفتم گفتن باید ریدایرکت به بانک با متد Post باشه 
از دوستان کسی این مشکل رو داشته ؟

**Comment by khanzadimahdi** [comment]
این مورد رو به ادرس زیر انتقال دادم
https://github.com/shetabit/multipay/issues/20
از طریق ادرس بالا پیگیری کنید

**Comment by khanzadimahdi** [comment]
رپازیتوری پکیج رو فورک کنید و درصورتی که مشکلی در درگاه میبینید اون رو رفع کنید و درخواست مرج بدید

https://github.com/shetabit/multipay/blob/master/src/Drivers/Parsian/Parsian.php

درایور پارسیان رو میتونید در مسیر بالا پیدا کنید
