### ISSUE TITLE
عدم تایید پرداخت برای درگاه زرین پال

### ISSUE THREAD

**Issue by LegenD1995** [shetabit/payment#101]
سلام وقت بخیر

من کوئری های ریدایرکت شده از زرین پال به روت ویو جِی اس رو دریافت و درقالب متد  
POST
به روت لاراول ارسال میکنم.

ولی با متد زیر:
```php

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Shetabit\Multipay\Invoice;
use Shetabit\Payment\Facade\Payment;
use Shetabit\Multipay\Exceptions\InvalidPaymentException;


     /**
     * Verify Payment
     * 
     * @param Illuminate\Http\Request authority
     */
    public function verify_payment(Request $request) {
        try {
            $receipt = Payment::transactionId($request->authority)->verify();

            // Add a Membership For user
            // ...
        
            // You can show payment referenceId to the user.
            return response()->json(['success' => true, 'refs' => $receipt->getReferenceId()]);
        } catch (InvalidPaymentException $exception) {
            /**
                when payment is not verified, it will throw an exception.
                We can catch the exception to handle invalid payments.
                getMessage method, returns a suitable message that can be used in user interface.
            **/
            return response()->json(['success' => false, 'catch' => $exception->getMessage()], 500);
        }
    }
```
هیچوقت وریفای نمیشه و متن
**عملیات پرداخت توسط کاربر لغو شد**
رو برام ارسال میکنه.

این متد در حالت سندباکس و نرمال چک شده!
پرداخت انجام میشه یا عملیات موفقیت آمیزه اما وریفای به مشکل میخوره

**ورژن shetabit/multipay:**
`
"name": "shetabit/multipay",
            "version": "v1.0.6",
`
**ورژن shetabit/payment:**
`
"name": "shetabit/payment",
            "version": "v4.0.1",
`
**ورژن لاراول:**
7.4

مشکل از کجاست؟؟

**Comment by khanzadimahdi** [comment]
see the below example

how to run:

```bash
php artisan migrate;
php artisan serve;
```

then open: http://127.0.0.1:8000

[payment-example.zip](https://github.com/shetabit/payment/files/5237545/payment-example.zip)

**Comment by LegenD1995** [comment]
ممنون! کدهای شما کار میده
سعی کردم همون مسیر رو تا حد ممکن روی مدل ها و کنترلرهام برم
(جز اینکه قیمت رو یه طور دیگه پاس دادم و از روت api لاراول استفاده کردم)

اما باز هم همون مشکل رو دارم.
متد verify کجای پکیج تعریف شده تا بررسی کنم؟

**Comment by khanzadimahdi** [comment]
<div dir="rtl">
لینک زیر رو بررسی کنید
</div>

https://github.com/shetabit/multipay/blob/master/src/Drivers/Zarinpal/Zarinpal.php

**Comment by LegenD1995** [comment]
خط 22  از فایل بالا نمیتونه Status رو توی درخواستم پیدا کنه!

به احتمال 99 درصد مشکل از درخواست سمت کلاینته، ممنون

**Comment by menkaff** [comment]
@LegenD1995 مشکل شما حل شد؟ من ارور  منفی 50 میگیرم که تو دایکومنت زرینپال و این پکیج حرفی ازش نیست

**Comment by khanzadimahdi** [comment]
@menkaff 

نمونه کدی که بالاتر هست رو دانلود کنید ببینید

خطای شما به دلیل این هست که مبلغ مورد وریفای با مبلغ پرداخت شده یکسان نیست

**Comment by menkaff** [comment]
@khanzadimahdi بله مشکل از مبلغ بود ممنونم مرسی

**Comment by matinwd** [comment]
مشکل 
 عملیات پرداخت توسط کاربر لغو شد
برای منم هست با اینکه status رو OK برمیگردونه
توی حالت sandbox چکش کردم 
ورژن پکیج هام هم اینهاست

``` "name": "shetabit/multipay",
            "version": "v1.1.3",```

```
 "name": "shetabit/payment",
            "version": "v4.0.1",
```
```
        "laravel/framework": "^7.24",

```

**Comment by khanzadimahdi** [comment]
@matinwd 

<div dir=rtl>
در مرحله وریفای باید مبلغ رو هم ارسال کنید

نمونه کدی که در بالاتر هست رو دانلود و اجرا کنید و کدها رو نگاه کنید تا دقیقتر متوجه بشید

داکیومنت های پکیج رو هم مطالعه کنید
</div>
