### ISSUE TITLE
درگاه پی پل لاراول

### ISSUE THREAD

**Issue by amiralibk** [shetabit/payment#102]
سلام مهدی جان 

درگاه پی پال کی اضاف میشه ؟ به شدت منتظریم .
ممنون از این پکیج عالی و کاربردی حرف نداره

**Comment by khanzadimahdi** [comment]
<div dir="rtl">
سلام. متاسفانه من دسترسی به مستندات و همچنین امکانات لازم واسه تست درگاه رو ندارم. میتونید درگاه رو اظافه کنید و درخواست مرج بدید. من فایل درایورشو اظافه کردم اما کدها نیاز به تکمیل و تست دارن. میتونید از لینک زیر ببینید

</div>

https://github.com/shetabit/multipay/blob/master/src/Drivers/Paypal/Paypal.php

**Comment by alitnk** [comment]
سلام
خبری از درایور paypal نیست؟

**Comment by khanzadimahdi** [comment]
سلام. اگه امکانش هست درگاه مورد نظرتون رو اضافه کنید و درخواست مرج بدید

به دلیل اینکه داکیومنت و قابلیت تست نداشتم نتونستم درگاه پی پل اضافه کنم
