### ISSUE TITLE
Multiple gateways and different configs with similar driver

### ISSUE THREAD

**Issue by alisalmabadi** [shetabit/payment#103]
Hi
thanks for this awesome package
I have multiple gateways in my current project with the same driver (3 payping! & ... ) I solved this issue by creating lots of custom drivers (which is great! )
for duplication elimination, it might be better to add this feature which we can add multiple merchant code for one driver and the ability to switch to any of them if it is logical and possible

**Comment by khanzadimahdi** [comment]
technically we don't need multiple merchant id from a service! 
say you use `payping` with 3 merchant ids!!!! you can implement it your self. the package provides the `config` method for setting dynamic configs on runtime.
