### ISSUE TITLE
problem with new version of zarinpa get error "اطلاعات ارسال شده ناقص است"

### ISSUE THREAD

**Issue by mobintmu** [shetabit/payment#104]
## Detailed description

issuse bug in new version of zarinpal

## Context

Why is this change important to you? How would you use it?

How can it benefit other users?

## Possible implementation

Not obligatory, but suggest an idea for implementing addition or change.

## Your environment

PHP 7.4
Ubunutu 20.04

**Comment by khanzadimahdi** [comment]
run below commands and try again:

```php
php artisan cache:clear
php artisan vendor:publish
```
then put your merchant id in `config/payment.php`

**Comment by mahdisoftdev** [comment]
> run below commands and try again:
> 
> ```
> php artisan cache:clear
> php artisan vendor:publish
> ```
> 
> then put your merchant id in `config/payment.php`

منم همین مشکل دارم این کارا رو انجام دادم ولی درست نشد

**Comment by khanzadimahdi** [comment]
see below

https://github.com/shetabit/payment/issues/101#issuecomment-694091114

**Comment by mobintmu** [comment]
I'm using Laravel version 5.5, unfortunately, I prefer to implement it traditionally. sorry I not checking your solution

https://medium.com/@mobinshaterian/running-zarinpal-gateway-on-laravel-framework-ac9d84674ec6

**Comment by khanzadimahdi** [comment]
Laravel 5.5 has not been tested yet. it has some issues that must be fixed.

https://github.com/shetabit/payment/issues/84

**Comment by khanzadimahdi** [comment]
you can fix it and send pull request. i will merge it.

**Comment by matinwd** [comment]
منم همین مشکلات رو دارم و همه سولوشن هارو چک کردم ولی فرقی نکرد

**Comment by khanzadimahdi** [comment]
@matinwd

لطفا ورژن پکیجی که استفاده میکنید به همراه ورژن لاراول خودتون رو ثبت کنید. سولوشن هایی که امتحان کردین چی بوده؟

**Comment by matinwd** [comment]
"laravel/framework": "^7.24",

        "shetabit/payment": "^4.0",


https://github.com/shetabit/payment/issues/101#issuecomment-694091114

**Comment by khanzadimahdi** [comment]
@matinwd 
کش کانفیگ رو پاک کردین؟

```php
php artisan config:clear
```

و اینکه وندور رو پابلیش کردین؟

**Comment by matinwd** [comment]
بله همه اینکار ها انجام شده
الان نمونه کد استفاده شده رو براتون میزارم

**Comment by matinwd** [comment]
Controller:
$invoice = new Invoice();
            $invoice->amount((int)$order->total);
            $invoice->detail('description','اطلاعات تست');
            $payment  = new Payment();
            $payment->detail('description','خرید تست');
            return $payment->purchase($invoice, function($driver, $transactionId) {
                // Store transactionId in database as we need it to verify payment in the future.
            })->pay()->render();

Config:
'default' => 'zarinpal',

'zarinpal' => [
            /* normal api */
            'apiPurchaseUrl' => 'https://ir.zarinpal.com/pg/services/WebGate/wsdl',
            'apiPaymentUrl' => 'https://www.zarinpal.com/pg/StartPay/',
            'apiVerificationUrl' => 'https://ir.zarinpal.com/pg/services/WebGate/wsdl',

            /* sandbox api */
            'sandboxApiPurchaseUrl' => 'https://sandbox.zarinpal.com/pg/services/WebGate/wsdl',
            'sandboxApiPaymentUrl' => 'https://sandbox.zarinpal.com/pg/StartPay/',
            'sandboxApiVerificationUrl' => 'https://sandbox.zarinpal.com/pg/services/WebGate/wsdl',

            /* zarinGate api */
            'zaringateApiPurchaseUrl' => 'https://ir.zarinpal.com/pg/services/WebGate/wsdl',
            'zaringateApiPaymentUrl' => 'https://www.zarinpal.com/pg/StartPay/:authority/ZarinGate',
            'zaringateApiVerificationUrl' => 'https://ir.zarinpal.com/pg/services/WebGate/wsdl',

            'mode' => 'sandbox', // can be normal, sandbox, zaringate
            'merchantId' => '86ff44fb-068e-4d9c-9e71-14a851cc20b9', //86ff44fb-068e-4d9c-9e71-14a851cc20b9
            'callbackUrl' => 'http://yoursite.com/path/to',
            'description' => 'payment using zarinpal',
        ],

**Comment by khanzadimahdi** [comment]
<div dir=rtl>
کد شما مشکل داره
</div>

```php
$payment = new Payment();
```

<div dir=rtl>

داکیومنت ها رو خوندین؟ توی داکیومنت هیچ مثالی به این شکلی که شما نوشتین نداره. 

وقتی از روی کلاس payment یه ابجکت میسازید باید کانفیگ رو خودتون بهش پاس بدید. کلاسشو باز کنید و متد سازنده رو ببینید متوجه میشین.

</div>

```php
$payment = new Payment(config('payment'));
```

<div dir=rtl>

یا اینکه طبق مستندات باید به صورت زیر عمل کنید

</div>

```php
// At the top of the file.
use Shetabit\Multipay\Invoice;
use Shetabit\Payment\Facade\Payment;
...

// Create new invoice.
$invoice = (new Invoice)->amount(1000);

// Purchase the given invoice.
Payment::purchase($invoice,function($driver, $transactionId) {
	// We can store $transactionId in database.
});
```

**Comment by khanzadimahdi** [comment]
سلام درگاه زرین پال رو با توجه به اخرین ورژن ای پی آی که ارائه دادن بروز رسانی کردم. لطفا پکیج رو اپدیت کنید و فایل کانفیگ پکیج رو حذف کنید و دوباره پابلیش کنید
