### ISSUE TITLE
 - Installation request for nesbot/carbon (locked at 1.22.1) -> satisfiable by nesbot/carbon[1.22.1].

### ISSUE THREAD

**Issue by AfshinEfati** [shetabit/payment#106]
## در زمان نصب روی لاراول 5.5.4 داره خطا میده 

خطا تا جایی که فهمیدم مربوط به کربن هستش 

 ```
Problem 1
    - The requested package nesbot/carbon (locked at 1.22.1, required as 2.16.3 as 1.34.0) is satisfiable by nesbot/carbon[1.22.1] but these conflict wi
th your requirements or minimum-stability.
```
```
  Problem 2
    - Conclusion: don't install nesbot/carbon 1.34.0|remove symfony/translation v3.3.9|install symfony/translation v4.4.0|install symfony/translation v4
.4.1|install symfony/translation v4.4.10|install symfony/translation v4.4.11|install symfony/translation v4.4.12|install symfony/translation v4.4.13|ins
tall symfony/translation v4.4.14|install symfony/translation v4.4.2|install symfony/translation v4.4.3|install symfony/translation v4.4.4|install symfon
y/translation v4.4.5|install symfony/translation v4.4.6|install symfony/translation v4.4.7|install symfony/translation v4.4.8|install symfony/translatio
n v4.4.9
```

` - laravel/framework v5.5.4 requires nesbot/carbon ~1.20 -> satisfiable by nesbot/carbon[1.34.0].`
`    - laravel/framework v5.5.4 requires nesbot/carbon ~1.20 -> satisfiable by nesbot/carbon[1.34.0].`
`    - laravel/framework v5.5.4 requires nesbot/carbon ~1.20 -> satisfiable by nesbot/carbon[1.34.0].`
   ` - Conclusion: don't install nesbot/carbon 1.34.0`

* Version used ( PHP 7.2, laravel 5.5.4):
* Operating system and version ( Windows 10):

**Comment by khanzadimahdi** [comment]
could you fix it and create pull request?

**Comment by khanzadimahdi** [comment]
I close this due to inactivity.
