### ISSUE TITLE
Object of class Shetabit\Multipay\Drivers\Zarinpal\Zarinpal could not be converted to string

### ISSUE THREAD

**Issue by ahzare** [shetabit/payment#107]
public static function replaceArray($search, array $replace, $subject)

    {

        $segments = explode($search, $subject);

 

        $result = array_shift($segments);

 

        foreach ($segments as $segment) {

            $result .= (array_shift($replace) ?? $search).$segment;

        }

 

        return $result;

    }

سلام هنگام انتقال به درگاه پرداخت این قسمت خطا مگیره چکار باید انجام بدم؟

**Comment by khanzadimahdi** [comment]
<div dir="rtl">
کدهای نوشته شده ربطی به کدهای درگاه و هیچ کدی از پکیج داره؟ حدس میزنم این موارد رو خود شما نوشتین پس مشکل از کد شماس و به پکیج مربوط نمیشه
</div>

**Comment by ahzare** [comment]
Shetabit\Multipay\Drivers\Zarinpal\Zarinpal
این کلاس که بنظر مربوط به کتابخانه هست. من چنین  کدی ننوشتم. بنظر شما اشکال از کجا متونه باشه؟؟

Sent from Mail for Windows 10

**Comment by khanzadimahdi** [comment]
see below example

https://github.com/shetabit/payment/issues/101#issuecomment-694091114
