### ISSUE TITLE
there is a problem in installation

### ISSUE THREAD

**Issue by sajad2176** [shetabit/payment#109]
* Version used (e.g. PHP 7.2, HHVM 3):7.2.5
* Operating system and version (e.g. Ubuntu 19.04, Windows 10):windows 10
* package version:4.0

after I run the composer install I got this error:

PHP Fatal error:  Allowed memory size of 1610612736 bytes exhausted (tried to allocate 4096 bytes) in phar://C:/ProgramData/ComposerSetup/bin/composer.phar/src/Composer/DependencyResolver/RuleWatchGraph.php on line 52

Fatal error: Allowed memory size of 1610612736 bytes exhausted (tried to allocate 4096 bytes) in phar://C:/ProgramData/ComposerSetup/bin/composer.phar/src/Composer/DependencyResolver/RuleWatchGraph.php on line 52

Check https://getcomposer.org/doc/articles/troubleshooting.md#memory-limit-errors for more info on how to handle out of memory errors.

**Comment by khanzadimahdi** [comment]
its related to composer.

**Comment by sajad2176** [comment]
But I install version 3.1.0 and works fine

**Comment by khanzadimahdi** [comment]
see below link

https://stackoverflow.com/questions/49212475/composer-require-runs-out-of-memory-php-fatal-error-allowed-memory-size-of-161
