### ISSUE TITLE
Shetabit\Multipay\Exceptions\PurchaseFailedException خرید موفقیت‌آمیز نبود.

### ISSUE THREAD

**Issue by MrRezoo** [shetabit/payment#111]
سلام وقتتون بخیر
من از توی قسمت استفاده از متد 
via 
برای فراخوانی درایور (تفیر درایور دیفالت ) به مشکل خوردم و به نظرم کار نمیکنه این متد

**Comment by MrRezoo** [comment]
ممنون میشم راهنمایی کنید
`public function payment($payment_id = null)
    {
        $payment = Payment::with('paymentStatus')->where('id', $payment_id)->first();


        if (isset($payment)) {

            $invoice = (new Invoice)->amount(1000);
            $invoice->via('payir');
            return \Shetabit\Payment\Facade\Payment::purchase($invoice, function ($driver, $transactionId) {
            })->pay()->render();

        }
        return response()->json([
            'status' => '422'
        ]);


    }`

**Comment by khanzadimahdi** [comment]
<div dir="rtl">
متد via رو روی payment باید ران کنید و invoice این متد رو نداره

پیشنهاد میکنم داکیومنت ها رو نگاه کنید و طبق داکیومنت ها پیش برید
</div>
