### ISSUE TITLE
Shetabit\Multipay\Exceptions\PurchaseFailedException . authentication error

### ISSUE THREAD

**Issue by miladbrave** [shetabit/payment#112]
After use in test mode for a long time Unfortunately this error occurred:
`
Shetabit\Multipay\Exceptions\PurchaseFailedException
authentication error
`
laravel => 7.2
"shetabit/payment": "^4.0"
driver => zibal

**Comment by khanzadimahdi** [comment]
error is "authentication" error, so check your gateway credentials. your gateway username or password should be expired.

**Comment by miladbrave** [comment]
I use zibal in test mode. Is there an expiration date for this case? if yes what should I do?

**Comment by khanzadimahdi** [comment]
I think you should refer to Zibal's documents.
you can find zibal driver in below link

https://github.com/shetabit/multipay/blob/master/src/Drivers/Zibal/Zibal.php

if you think there is any bug or error, you could fix it and create pull request. i will merge it.

**Comment by aliwesome** [comment]
@miladbrave did your problem solved? what was your approach?

**Comment by khanzadimahdi** [comment]
please fix the driver and send pull request if you found any problem in it.
