### ISSUE TITLE
At Purchase invoice اطلاعات ارسال شده ناقص است.

### ISSUE THREAD

**Issue by rahx** [shetabit/payment#114]
I managed to install and config this package, and didn't had any problem with $invoice creating, adding amount and details, but as soon as I got to 

`Payment::purchase($invoice, function($driver, $transactionId) {
                    $order->transcode = $transactionId;
                    $order->save();
            });`

The response will be **اطلاعات ارسال شده ناقص است.**

I tried different function of your code about purchase but all are returning the same warning.

Will you please help me out to pass this part ?

I am using 
"laravel/framework": "^6.2",
"shetabit/payment": "^4.0"
Php 7.3.23

Thanks.

**Comment by khanzadimahdi** [comment]
go below steps:

1- php artisan config:clear
2- php artisan vendor:publish
3- configure config/payment.php

then test it again.

**Comment by khanzadimahdi** [comment]
check the below example

https://github.com/shetabit/multipay/blob/master/src/Drivers/Zarinpal/Zarinpal.php

**Comment by rahx** [comment]
Tested and here the result:

1- php artisan config:clear  Ok
2- php artisan vendor:publish  Ok
`Copied Directory [/vendor/shetabit/payment/resources/views] To [/resources/views/vendor/shetabitPayment]
Publishing complete.`
But `configure config/payment.php` Is not working and says: `configure: command not found`

**Comment by khanzadimahdi** [comment]
do you see `payement.php` in your config files?

**Comment by khanzadimahdi** [comment]
download and see the below example.

https://github.com/shetabit/payment/issues/114#issuecomment-712710169

how to run example:

```bash
php artisan migrate
php artisan serve
```

**Comment by rahx** [comment]
> do you see `payement.php` in your config files?

Yes

**Comment by rahx** [comment]
php artisan migrate result: and it has `nothing to migrate`

**Comment by khanzadimahdi** [comment]
<div dir="rtl">
دوست عزیز پکیج مشکلی نداره. نمونه مثالی که لینکشو براتون بالاتر گذاشتم رو دانلود کنید و نمونه کد رو ببینید. به درستی کار میکنه

مایگرشن هایی که گفتم مربوط به نمونه کدی هست که قرار دادم
</div>

**Comment by jpro123** [comment]
مقداری برای merchantId در فایل peyment.php  قراربدید این ارور رفع میشه
