### ISSUE TITLE
صفحه بازگشت از پرداخت

### ISSUE THREAD

**Issue by sedall** [shetabit/payment#115]
سلام . وقت بخیر . تشکر بابت پکیجی که ارائه کردید
در صفحه بازگشت از پرداخت چطور می توانم اطلاعات را بررسی کنم که پرداخت انجام شده و یا کنسل شده
من داخل دیتابیس  ایدی تراکنش را دارم اما اطلاعات بازگشتی را چطور می توانم بررسی کنم

**Comment by khanzadimahdi** [comment]
<div dir="rtl">
سوالی که پرسیدین توی داکیومنت ها توضیح داده شده. پیشنهاد میکنم لینک زیر رو یکبار مطالعه کنید

</div>

https://github.com/shetabit/payment/blob/master/README-FA.md#%D8%A7%D8%B9%D8%AA%D8%A8%D8%A7%D8%B1-%D8%B3%D9%86%D8%AC%DB%8C-%D9%BE%D8%B1%D8%AF%D8%A7%D8%AE%D8%AA
