### ISSUE TITLE
verify

### ISSUE THREAD

**Issue by MmrDev** [shetabit/payment#117]
سلام 
یه مشکلی توی وریفای کردن تراکنش هست روی پکیج من روی زرین و سداد تست کردم بعد از تراکنش موفق موقع وریفای میگه خطای نامشخص 
نکته اینه  ک تا جند هفته پیش اوکی بوده 

و یه مسئله دیگه اون blade که هست رو نمیشه کاستوم معرفی کرد از توی کانفیگ ؟‌

**Comment by khanzadimahdi** [comment]
<div dir=rtl>
پکیج مشکلی نداره و تست شده هست

برای کاستوم کردن بلید میتونید وندور رو پابلیش کنید بعدش به پوشه ی ویوو ها برید فایلشو میتونید پیدا کنید

</div>
