### ISSUE TITLE
please get me sample code for use

### ISSUE THREAD

**Issue by afsanehmh** [shetabit/payment#118]
## Detailed description

Provide a detailed description of the change or addition you are proposing.

Make it clear if the issue is a bug, an enhancement or just a question.

## Context

Why is this change important to you? How would you use it?

How can it benefit other users?

## Possible implementation

Not obligatory, but suggest an idea for implementing addition or change.

## Your environment

Include as many relevant details about the environment you experienced the bug in and how to reproduce it.

* Version used (e.g. PHP 7.2, HHVM 3):
* Operating system and version (e.g. Ubuntu 19.04, Windows 10):
* Link to your project:
* ...
* ...

**Comment by khanzadimahdi** [comment]
see the below link

https://github.com/shetabit/payment/issues/114#issuecomment-712710169
