### ISSUE TITLE
 require ext-soap * -> it is missing from your system

### ISSUE THREAD

**Issue by parsagholipour** [shetabit/payment#121]
Problem 1
    - shetabit/payment[4.0.0, ..., v4.0.1] require ext-soap * -> it is missing from your system. Install or enable PHP's soap extension.
    - Root composer.json requires shetabit/payment ^4.0 -> satisfiable by shetabit/payment[4.0.0, v4.0.1].

To enable extensions, verify that they are enabled in your .ini files:
    - C:\xampp\php\php.ini

It didn't require Soap before

**Comment by khanzadimahdi** [comment]
it will be fixed in new release.
