### ISSUE TITLE
خطا بعد از بازگشت از درگاه

### ISSUE THREAD

**Issue by sedall** [shetabit/payment#123]
سلام . ممنون میشم در مورد خطای زیر راهنمایی کنید.
من بعد از بازگشت از درگاه خطای زیر را دریافت می کنم
 
 Call to a member function getTryPublicId() on null 

![4](https://user-images.githubusercontent.com/32809872/98653562-6db80900-2352-11eb-8cc0-42767c4ea9da.PNG)

**Comment by khanzadimahdi** [comment]
<div dir=rtl>
توی تمامی پکیج هیچ تابعی به نام getTryPublicId نداریم. کدی که خودتون نوشتید رو بررسی کنید. 

مشکل قطعا توی کدهای خودتون هست و مرتبط با پکیج نیست

</div>

**Comment by MehdiAghighi** [comment]
@sedall من هم به همین مشکل خوردم امروز

شما تونستید حل کنید این مورد رو ؟

**Comment by khanzadimahdi** [comment]
https://github.com/shetabit/payment/issues/131#issuecomment-748486564

کامنت بالا رو برای رفع مشکل بررسی کنید. مشکل از سمت زرین پال هست. شناسه تراکنش رو نباید به نوع دیگه ای کست کنید
