### ISSUE TITLE
Code change not affected on document on readme

### ISSUE THREAD

**Issue by aryanfard** [shetabit/payment#124]
Hello

I upgrade your package and get into trouble!

please upgrade your readme and add some note about upgrading to new version and note that we must update config file

* Version used PHP 7.4, nginx
* Operating system : Ubuntu 18.04
* Laravel 8

Thanks

**Comment by khanzadimahdi** [comment]
I close this issue due to inactivity! please follow the docs to update the package. after updating the package you MUST re-publish the configs again.
