### ISSUE TITLE
مشکل ایرانکیش 

### ISSUE THREAD

**Issue by amiralibk** [shetabit/payment#126]
<div dir=rtl>

سلام 
وقتی درایور رو به ایرانکیش تغییر میدم اگه پرداخت ناموفق باشه اطلاعات رو پست میکنه در صورتی که باید گت بکنه رو صفحه !.این مشکل بررسی بشه !!!
وقتی هم اطلاعات کارت وارد میشه برای پرداخت مینویسه دانده کارت مجاز به انجام عملیات نیست .

ناگفته نمونه این مشکلا توی درایور زرین پال وجود نداشت من وقتی اطلاعات درگاه ایرانکیش رو وارد کردم و درایور رو به ایرانکیش تغییر دادم این مشکلات به وجود اومد در صورتی که نباید اینطوری باشه و با تغییر درایور ها بهم بریزه !!!

</div>

**Comment by khanzadimahdi** [comment]
<div dir=rtl>

سلام. لطفا ورژن پکیجی که استفاده میکنید به همراه اون قسمت از کنترلر خودتون که به مشکل خوردین رو قرار بدین تا بررسی کنم

</div>

**Comment by amiralibk** [comment]
سلام 
ورژن 4.0 
اینم کد کنترلر برای ریکوئست و کال بک .
با همین کد برای درگاه زرین پال مشکلی نیست اما درگاه ایرانکیش متصل میشه به درگاه ولی اون مشکلاتی که گفتم رو داره .

`<?php

namespace App\Http\Controllers;

use Shetabit\Multipay\Exceptions\InvalidPaymentException;
use Shetabit\Multipay\Invoice;
use Shetabit\Payment\Facade\Payment as shetabitPayment;

use App\Order;
use App\Payment;
use App\Notifications\invoiceOrder;
use App\Product;
use Artesaos\SEOTools\Facades\SEOMeta;
use Illuminate\Support\Facades\Auth;
use Illuminate\Http\Request;


class PaymentsController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $order = Order::where('order_id', '=', $request->order_id)->first();
        $payment = Payment::where('order_id', '=', $order->id)->first();



        $invoice = (new Invoice)->amount((integer)$payment->price);

        return shetabitPayment::callbackUrl(route('payments.callback'))->config('description',"سفارش شماره $request->order_id")->purchase($invoice, function($driver, $transactionId)use($payment) {

            $payment->update([
                'resnumber' => $transactionId
            ]);

        })->pay()->render();

    }

    public function callback(Request $request)
    {

        // Seo metas
       SEOMeta::setTitle('اصغری شاپ | مشاهده وضعیت سفارش');

       $user = Auth::user();

       $payment = Payment::where('resnumber',$request['Authority'])->first();
       $order = Order::where('id', '=', $payment->order_id)->first();

       $status = $request['Status'] == 'OK' ? 100 : 200;



       try {

           $receipt = shetabitPayment::amount((integer)$payment->price)->transactionId($payment->resnumber)->verify();

           // update product count
           foreach ($order->products as $key => $value){
               Product::find($key)->decrement('count',$value['count']);
           }

           // order and payment update
           $payment->update([
               'status' => 1,
               'errcode' => $receipt->getReferenceId()
           ]);

           $payment->order()->update([
               'status' => 'confrim'
           ]);

           // send email
           if($order->user->email != null){

               $arr = [
                   'order_id' => $order->order_id,
                   'saller' => $order->user->fullname,
                   'date' => jdate($order->created_at)->format('%A, %d %B %y'),
                   'count' => count($order->products),
                   'shipway' => $order->shipping_way,
                   'status' => $order->payment->first()->status == 1 ? 'پرداخت موفق' : 'پرداخت نا موفق',
                   'price' => $payment->price
               ];
               $order->user->notify(new invoiceOrder($arr));
           }

           //send sms to user
           $message = " اصغری شاپ

کاربر گرامی، سفارش شماره $order->order_id با موفقیت برای شما ثبت شد . برای مشاهده جزئیات به پنل کاربریتان مراجعه کنید .
با تشکر،اصغری شاپ
               ";
           $this->sendSMS($order->user->mobile, $message);
           

           return view('orderback', compact('user', 'order', 'payment', 'status'))->with('success', 'سفارش شما با موفقیت پرداخت شد ، برای مشاهده وضعیت این سفارش به پنل کاربری مراجعه کنید ');



       } catch (InvalidPaymentException $exception) {

           $payment->update([
               'status' => 2,
               'errcode' =>  $exception->getMessage()
           ]);

           $payment->order()->update([
               'status' => 'review'
           ]);

           // send email
           if($order->user->email != null){
               $arr = [
                   'order_id' => $order->order_id,
                   'saller' => $order->user->fullname,
                   'date' => jdate($order->created_at)->format('%A, %d %B %y'),
                   'count' => count($order->products),
                   'shipway' => $order->shipping_way,
                   'status' => $order->payment->first()->status == 1 ? 'پرداخت موفق' : 'پرداخت نا موفق',
                   'price' => $payment->price
               ];
               $order->user->notify(new invoiceOrder($arr));
           }

           //send sms
           $message = " اصغری شاپ

کاربر گرامی، سفارش شماره $order->order_id برای شما ثبت نشد .
با تشکر،اصغری شاپ
               ";
           $this->sendSMS($order->user->mobile, $message);

           return view('orderback', compact('user', 'order', 'payment', 'status'))->with('error', $exception->getMessage());

       }

    }

    /**
     * Display the specified resource.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}
`

**Comment by khanzadimahdi** [comment]
<div dir=rtl>
درگاه ها هنگام بازگشت معلوم نیست که متد رو پست میکنن یا گت! این قضیه به بانک ربط داره و هر بانکی یه مدل متفاوت داره باهاش رفتار میکنه. شما متد بازگشتی رو طوری تنظیم کنید که هم با گت و هم با پست به مشکلی نخوره
</div>

**Comment by mohsen-hsh74** [comment]
با یکی از دو روش زیر میتونی مدیریت کنی
Route::any('redirect url', function(){});
Route::match(['get', 'post'], 'redirect url', function(){});

**Comment by amiralibk** [comment]
> درگاه ها هنگام بازگشت معلوم نیست که متد رو پست میکنن یا گت! این قضیه به بانک ربط داره و هر بانکی یه مدل متفاوت داره باهاش رفتار میکنه. شما متد بازگشتی رو طوری تنظیم کنید که هم با گت و هم با پست به مشکلی نخوره

خیر اصلا مشکل از این ها نیست شما کد رو خواستی تا بررسی کنی ولی فکر نکنم اینکارو کرده باشی ولی من اینکارو کردم . 
مشکل از تابع verify() هستش
که توی ی خطی میاد $status != 'OK' رو چک میکنه در صورتی که اصلا هیچ درخواستی به اسم استاتوس نداره . 

اون خط کدو باید برداری و قبلش چک کنی اگه استاتوس وجود داشت واگر != ok بود بیاد پرداختو لغو کنه 

عملا اینکار جلوی پرداختو میگیره و همه هزینه ها برگشت داده میشه به حساب بعد از پرداخت

**Comment by khanzadimahdi** [comment]
<div dir=rtl>

دوست عزیز متد وریفای در درگاه ایرانکیش به صورت زیر هست

</div>

```php
    public function verify() : ReceiptInterface
    {
        $data = array(
            'merchantId' => $this->settings->merchantId,
            'sha1Key' => $this->settings->sha1Key,
            'token' => $this->invoice->getTransactionId(),
            'amount' => $this->invoice->getAmount() * 10, // convert to rial
            'referenceNumber' => Request::get('referenceId'),
        );

        $soap = new \SoapClient($this->settings->apiVerificationUrl);
        $response = $soap->KicccPaymentsVerification($data);

        $status = (int) ($response->KicccPaymentsVerificationResult);

        if ($status != $data['amount']) {
            $this->notVerified($status);
        }

        return $this->createReceipt($data['referenceNumber']);
    }
```
<div dir=rtl>

تمامی درگاه ها تست شده هستن و توی تعداد زیادی پروژه استفاده شدن و نباید مشکلی داشته باشن

به هر حال درصورتی که مشکلی رو پیدا کردین و حلش کردین ممنون میشم پکیج رو فورک کنید و درخواست مرج بدید تا درون پکیج هم حل بشه.

ممنونم از شما

</div>

**Comment by amiralibk** [comment]
توی فایل کانفیگ درایور دیفالت روی زرین پال ست بود و همه برگشت هارو از متد وریفای زرین پال میخوند 

   return shetabitPayment::via('irankish')->callbackUrl(route('payments.callback'))->config('description',"سفارش شماره $request->order_id")->purchase($invoice, function($driver, $transactionId)use($payment) {

            $payment->update([
                'resnumber' => $transactionId
            ]);

        })->pay()->render();

من از via برای انتخاب ایرانکیش موقع پرداخت استفاده کردم
به بانک میرفت اما متد وریفایش با زرین پال میومد کلا مشکل همین بود . 

این via رو باید برای وریفای هم بزارم؟

**Comment by khanzadimahdi** [comment]
<div dir=rtl>

بله باید برای وریفای هم بزارید. در غیر اینصورت با درایوری که توی کانفیگ هست وریفای میکنه

</div>

**Comment by amiralibk** [comment]
مرسی ممنون

**Comment by jalallinux** [comment]
```php
public function verify() : ReceiptInterface
    {
        $data = array(
            'merchantId' => $this->settings->merchantId,
            'sha1Key' => $this->settings->sha1Key,
            'token' => $this->invoice->getTransactionId(),
            'amount' => $this->invoice->getAmount() * 10, // convert to rial
            - 'referenceNumber' => Request::get('referenceId'),              <--- invalid line
            + 'referenceNumber' => Request::post('referenceId'),           <--- correct line
        );

        $soap = new \SoapClient($this->settings->apiVerificationUrl);
        $response = $soap->KicccPaymentsVerification($data);

        $status = (int) ($response->KicccPaymentsVerificationResult);

        if ($status != $data['amount']) {
            $this->notVerified($status);
        }

        return $this->createReceipt($data['referenceNumber']);
    }
```


سلام شما توی وریفای درگاه ایرانکیش کال بک این درگاه رو گت در نظر گرفتی در صورتی که توی اکیومنتای ایران کیش که چندینننن ساله تکون نخورده گفته کالبکشون پست میشه.

بعد چطور شما میگی این درگاه ها تست شده من نمیدونم؟
لطفا این موضوع رو بررسی کنید و درصورت امکان این مشکل رو فیکس کنید.
ممنونم
