### ISSUE TITLE
چطور برای هر پرداخت description متفاوت تعریف کنم؟

### ISSUE THREAD

**Issue by hadidadkhah** [shetabit/payment#127]
<div dir=rtl>
سلام و خسته نباشید.
چطور می‌توانیم در هر تراکنش یک description متفاوت داشته باشیم؟
من تنظیم description را فقط در فایل کانفیگ پیدا کردم که برای همه تراکنش‌ها ثابت است.
</div>

```php
'description' => 'payment in '.config('app.name'),
```

<div dir=rtl>
تشکر.
</div>

**Comment by ahbanavi** [comment]
سلام.
می‌تونید از طریق متد [detail](https://github.com/shetabit/payment#how-to-use) این‌کار رو انجام بدید.

نمونه:

```$invoice->detail('description','your description goes here');```

فقط دقت داشته باشید تنها در درگاه پرداخت هایی که توضیحات یا دیتای اضافه قبول می‌کنند این فیلد تاثیر گذار هست.
