### ISSUE TITLE
 مثال واقعی برای به پرداخت ملت

### ISSUE THREAD

**Issue by alihastam** [shetabit/payment#128]
کسی میتونه یه مثال برای به پرداخت ملت بزنه چطور نوشته میشه؟
من این کارها رو کرده ام ولی قسمت 
callback
رو نمیدونم چطور باید بنویسم.
![2020-12-09_060018](https://user-images.githubusercontent.com/36451636/101567111-78af9900-39e5-11eb-89f2-1151a4deda16.jpg)
![2020-12-09_060101](https://user-images.githubusercontent.com/36451636/101567165-8ebd5980-39e5-11eb-9336-40aeca879495.jpg)

**Comment by khanzadimahdi** [comment]
see the below example

https://github.com/shetabit/payment/issues/101#issuecomment-694091114
