### ISSUE TITLE
error page

### ISSUE THREAD

**Issue by vahidrezaei** [shetabit/payment#129]
$paymetn = Payment::callbackUrl('my-url')->purchase()->pay(
...
)->render();
callback not work. and redirect after cancel bank payment redirect to :
https://mywebsite.com//index.php?&Authority=A00000000000000000000000000000030176&Status=NOK

**Comment by khanzadimahdi** [comment]
see the package docs. it works properly.

**Comment by vahidrezaei** [comment]
Sorry, in pament.php (in Config folder) config variable is $drivers but i use $drive.
thank you...
