### ISSUE TITLE
زرین گیت

### ISSUE THREAD

**Issue by abbaspoor** [shetabit/payment#13]
سلام برای زرین گیت باید چیکار کرد؟

apiPaymentUrl' => 'https://www.zarinpal.com/pg/StartPay/' -->authority <---  '/Zaringate 

به این شکل باید باشه

**Comment by khanzadimahdi** [comment]
درون فایل کانفیگ برید و تغییرات رو اعمال کنید تست کنید

**Comment by abbaspoor** [comment]
drivers' => [
        'zarinpal' => [// set urls to https://sandbox.zarinpal.com/pg/rest/WebGate/ for using sandbox
            'apiPaymentUrl' => 'https://www.zarinpal.com/pg/StartPay/اینجا متغییر باید قرار بگیره/ZarinGate',
           
        ]

**Comment by khanzadimahdi** [comment]
یه درایور جدید برای زرین گیت ایجاد کنید
فایل درایور زرین پال رو کپی کنید بعدش تغییرات رو اعمال کنید در اخر به فایل کانفیگ معرفیش کنید

**Comment by abbaspoor** [comment]
تشکر

**Comment by khanzadimahdi** [comment]
در صورتی که زرین گیت رو اظافه کردین پول ریکوئست بدید تا با پکیج کنونی مرج کنم. 
موفق باشید
