### ISSUE TITLE
عدم بازگشت به صفحه callback

### ISSUE THREAD

**Issue by mahdi-morovati** [shetabit/payment#132]
سلام من از سندباکس زرین پال استفاده میکنم و طبق داکیومنت پیش رفتم ولی 
callbackUrl 
کار نمیکنه و بعد از بازگشت از درگاه میره به صفحه
https://www.zarinpal.com/lab/%D9%86%D9%85%D9%88%D9%86%D9%87-%DA%A9%D8%AF-%D8%A7%D8%B3%D8%AA%D9%81%D8%A7%D8%AF%D9%87-%D8%B3%D8%B1%D9%88%DB%8C%D8%B3-%D8%B3%D9%86%D8%AF-%D8%A8%D8%A7%DA%A9%D8%B3-sandbox-%D9%86%D9%88/
کانفیگ فایل هم طبق داکیومنت تنظیم شده ولی انگار آدرس کال بک رو نمیشناسه و میره به سایت زرین پال

**Comment by khanzadimahdi** [comment]
سلام. نمونه کد زیر رو دانلود کنید و تست کنید

https://github.com/shetabit/payment/issues/101#issuecomment-694091114
