### ISSUE TITLE
پکیج درگاه بانک صادرات

### ISSUE THREAD

**Issue by imhaji** [shetabit/payment#134]
لطفا بانک صاذرات هم اضافه کنید

**Comment by khanzadimahdi** [comment]
بانک صادرات همین الان وجود داره و قابل استفاده هست. داکیومنت ها باید بروز رسانی بشه و ثبت بشه که صادرات وجود داره الان. 

ممنون از اطلاع رسانیتون

**Comment by khanzadimahdi** [comment]
لیست درگاه ها به صورت زیر هستن

https://github.com/shetabit/multipay/tree/master/src/Drivers

درگاه صادرات با نام سپهر وجود داره 

سپهر خدمات بانک صادرات رو ارائه میده
