### ISSUE TITLE
عملیات پرداخت توسط کاربر لغو شد.

### ISSUE THREAD

**Issue by matinwd** [shetabit/payment#135]
سلام وقتتون بخیر
من طبق داکیومنت دارم میرم جلو و این بار اکسپشن عملیات پرداخت توسط کاربر لغو شد. هربار داره تکرار میشه برای من
پکیج ها کاملا اپدیت هستن و من از متود وریفای داخل کلاس زرینپال سعی کردم بفهمم جریانش چیه که دیدم کلا مقدار کوئری استرینگ استاتوس رو نال میده
با اینکه الان ادرس من اینطوری هست:
https://hyper.test:8080/payment/verify?Authority=000000000000000000000000000000260514&Status=OK
اینهم کد من کاملا همونی هست که داخل داکیومنت اومده.
اون پروژه سمپل بکارم نیومد ولی بازهم ممنون
```try {
            $receipt = Payment::amount(1000)->transactionId($transactionId)->verify();
            echo $receipt->getReferenceId();
        } catch (InvalidPaymentException $exception) {
            echo $exception->getMessage();
        }```

**Comment by khanzadimahdi** [comment]
<div dir=rtl>
پروژه سمپل رو ران کردین؟ دقیقا زرین پال هست.فکر نکنم اصن نگاه کرده باشین کداشو

متوجه نمیشم  به کارم نیومد یعنی چی! دقیقا نمونه کد صحیح رو  به عنوام سمپل دادم بهتون.

من کمک دیگه ای از دستم بر نمیاد. نمونه کدی که به عنوان سمپل بهتون دادم رو نصب کنید اجرا کنید بعدش کداشو بررسی کنید

پکیج مشکلی نداره و تست شده هست. قطعا مشکل به دلیل پیاده سازی ناقصیه که انجام دادین
</div>
