### ISSUE TITLE
SoapFault Bad Gateway

### ISSUE THREAD

**Issue by miladbrave** [shetabit/payment#137]
سلام
به تازگی موقع وصل شدن به زرینپال ارور زیر میده.
`
SoapFault
Bad Gateway
`

**Comment by khanzadimahdi** [comment]
ادرس زرین پال توی کانفیگ ها موجوده. میتونید بین ایران و المان جابه جا کنید ادرس ها رو

**Comment by khanzadimahdi** [comment]
<div dir=rtl>
موقع ایجاد issue براش template ایجاد شده که با توجه به اون بیاید گزارش خطا بدید! الان ورژن php و soap شما مشخص نیست و حتی خودتونم پیگیری نکردین. به همین دلیل من این issue رو میبندم. اگه مشکل شما حل نشده بود اطلاعات   مورد نیاز روقرار بدید تا پیگیری کنم
</div>
