### ISSUE TITLE
How edit default driver or merchant setting in admin panel

### ISSUE THREAD

**Issue by chatlovely** [shetabit/payment#138]
i want to change Default driver parameter or merchant setting like zarinpal merchant api or behpardakht terminal id ,username and password in Admin panel with forms
how can i do it ?

**Comment by khanzadimahdi** [comment]
please read the docs before asking questions.

dynamic configs can be used like the below:

```php
// Purchase the given invoice with custom driver configs.
Payment::config('mechandId', 'your mechand id')->purchase(
    $invoice,
    function($driver, $transactionId) {
    // We can store $transactionId in database.
	}
);
```

**Comment by chatlovely** [comment]
ممنون ازتون 
بنده داکیومنت فارسی رو خونده بودم و هیچ اثری از اون کد که فرستادین نبود . چک کردم دیدم توی مستندات انگلیسی گذاشتین اون کد رو
فقط جسارتا سئوال آخر اینکه برای تعیین کردن درایو پیشفرض باید از این کد استقاده بشه ؟
Payment::config('default', 'zarinpal') ?

**Comment by khanzadimahdi** [comment]
این سوال هم جوابش توی داکیومنت ها هست. لطفا داکیومنت ها رو دوباره مطالعه کنید.

موفق باشید
