### ISSUE TITLE
قفل شدن صفحه در رفتن به بانک (درگاه زرین پال)

### ISSUE THREAD

**Issue by rahx** [shetabit/payment#140]
<div dir=rtl>

سلام، من از این Package برای درگاه به پرداخت استفاده میکنم و مشکلی ندارم، ولی الان که میخوام برای زرین پال استفاده کنم هنگام رفتن به بانک قفل میشه، تنظیمات و همه چی همونی هستش که روی به پرداخت کار میکنه، مابقی اطلاعات:

</div>

```php
'default' => 'zarinpal',
'drivers' => [
    'zarinpal' => [
            /* normal api */
            'apiPurchaseUrl' => 'https://ir.zarinpal.com/pg/services/WebGate/wsdl',
            'apiPaymentUrl' => 'https://www.zarinpal.com/pg/StartPay/',
            'apiVerificationUrl' => 'https://ir.zarinpal.com/pg/services/WebGate/wsdl',

            /* sandbox api */
            'sandboxApiPurchaseUrl' => 'https://sandbox.zarinpal.com/pg/services/WebGate/wsdl',
            'sandboxApiPaymentUrl' => 'https://sandbox.zarinpal.com/pg/StartPay/',
            'sandboxApiVerificationUrl' => 'https://sandbox.zarinpal.com/pg/services/WebGate/wsdl',

            /* zarinGate api */
            'zaringateApiPurchaseUrl' => 'https://ir.zarinpal.com/pg/services/WebGate/wsdl',
            'zaringateApiPaymentUrl' => 'https://www.zarinpal.com/pg/StartPay/:authority/ZarinGate',
            'zaringateApiVerificationUrl' => 'https://ir.zarinpal.com/pg/services/WebGate/wsdl',

            'mode' => 'normal', // can be normal, sandbox, zaringate
            'merchantId' => '*******************',
            'callbackUrl' => 'http://yoursite.com/path/to',
            'description' => 'payment using zarinpal',
        ],
]
namespaces:
use Shetabit\Multipay\Invoice;
use Shetabit\Payment\Facade\Payment;
use Shetabit\Multipay\Exceptions\InvalidPaymentException;

use Shetabit\Multipay\Abstracts\Driver;
use Shetabit\Multipay\Exceptions\PurchaseFailedException;
use Shetabit\Multipay\Contracts\ReceiptInterface;
use Shetabit\Multipay\Receipt;
use Shetabit\Multipay\RedirectionForm;
use Shetabit\Multipay\Request;

            $Purchases = new Purchase;
            $Order = $this->find($orderId);
            $callBackUrl = $this->appUrl().'/api/payment/callback';
            $total = (int)($Order->total);

            $invoice = new Invoice;
            $invoice->amount($total);
            $invoice->detail(['email' => $Order->email]);
            $bank = 'zarinpal'; // Bank

            return Payment::via($bank)->callbackUrl($callBackUrl)->purchase($invoice, function($driver, $transactionId) use ($Order){
                $Order->transcode = $transactionId;
                $Order->save();
            })->pay()->render();
```
Result:
![image](https://user-images.githubusercontent.com/10169591/105668225-26bdc680-5ef2-11eb-8848-ff86f58ec61f.png)

Composer.lock:
            "name": "shetabit/multipay",
            "version": "v1.0.9",
            
ممنون میشم راهنمایی کنید.

**Comment by khanzadimahdi** [comment]
متوجه نشدم قفل میشه یعنی چی؟

**Comment by rahx** [comment]
دقیقا روی عکسی که گذاشتم گیر میکنه کار، در صورتی که توی سیستم دیگه توی این نقطه Redirect میشه.
اینجا Redirect نمیشه و صفحه Attach شده رو نشون میده

**Comment by khanzadimahdi** [comment]
<div dir=rtl>
صفحه ی انتقال به درگاه نمایش داده میشه؟ توی اون صفحه یه دکمه هست که اگه اتوماتیک انتقال داده نشه با کلیک روی اون دکمه انتقال انجام میشه

کنسول مرورگر خودتون رو بررسی کنید ببینید شاید به خطا خورده چیزی. توی اون صفحه یه تیکه کد جاوا اسکریپتی هست که روی اون دکمه کلیک میکنه بعد از لود شدن صفحه
</div>

**Comment by khanzadimahdi** [comment]
<div dir=rtl>
دوست عزیز شما همه چیزو داخل کوتیشن و بعدش هم داخل تگ pre گذاشتین انتظار دارین کار کنه؟

اگه دقت کنید کدها از حالت html خارج شدن و دارن به صورت text نمایش داده میشن.

مشکل از کدهای شماست. کدهای مربوط به ریدایرکت رو از حالت html خارج کردین و انتظار دارین اجرا بشه که خیلی عجیبه!
</div>

**Comment by rahx** [comment]
دوست عزیز، ایا چیزیایی نیستن که من نوشته باشم از پکیج شما داره میخونه و این چیزا هیچ ربطی به من نداره وگرنه مریض نیستم وقتمو یه روز بکشم و بیام اینجا چیزی بنویسم

**Comment by khanzadimahdi** [comment]
<div dir=rtl>
لطفا دسترسی ریموت با انی دسک بدید تا نشون بدم کجای کدهای خودتون مشکل داره. این موردی که فرمودین مرتبط با پکیج نیست.

پکیج واسه ریدایرکت کردن یه فرم تولید میکنه و شما دارین اون فرم رو به صورت متن ساده توی صفحه نمایش میدین و از حالت html خارج میکنید. به همین دلیل فرم و کدهای جاوا اسکریپت اون ران نمیشن که صفحه ریدایرکت بشه

</div>

**Comment by khanzadimahdi** [comment]
<div dir="rtl">
فایل های vendor رو بعد از پابلیش کردن نگاه کنید. فایل های viewاصلا توش تگ pre نداره
</div>

**Comment by rahx** [comment]
`
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <title>Forwarding to secure payment provider</title>
        <style>
            .text-center {
                text-align: center;
            }

            .mt-2 {
                margin-top: 2em;
            }

            .spinner {
                margin: 100px auto 0;
                width: 70px;
                text-align: center;
            }

            .spinner > div {
                width: 18px;
                height: 18px;
                background-color: #333;
                border-radius: 100%;
                display: inline-block;
                -webkit-animation: sk-bouncedelay 1.4s infinite ease-in-out both;
                animation: sk-bouncedelay 1.4s infinite ease-in-out both;
            }

            .spinner .bounce1 {
                -webkit-animation-delay: -0.32s;
                animation-delay: -0.32s;
            }

            .spinner .bounce2 {
                -webkit-animation-delay: -0.16s;
                animation-delay: -0.16s;
            }

            @-webkit-keyframes sk-bouncedelay {
                0%, 80%, 100% { -webkit-transform: scale(0) }
                40% { -webkit-transform: scale(1.0) }
            }

            @keyframes sk-bouncedelay {
                0%, 80%, 100% {
                    -webkit-transform: scale(0);
                    transform: scale(0);
                } 40% {
                      -webkit-transform: scale(1.0);
                      transform: scale(1.0);
                  }
            }
        </style>
    </head>
    <body onload="submitForm();">
        <div class="spinner">
            <div class="bounce1"></div>
            <div class="bounce2"></div>
            <div class="bounce3"></div>
        </div>
        <form class="text-center mt-2" method="{{ $method }}" action="{{ $action }}">
            <p>Forwarding to secure payment provider.</p>
            <p>
                If you are not automatically redirected to the payment website with in
                <span id="countdown">10</span>
                seconds...
            </p>

            @foreach($inputs as $name => $value)
                <input type="hidden" name="{{ $name }}" value="{{ $value }}">
            @endforeach

            <button type="submit">Click here</button>
        </form>
        <script>
            // Total seconds to wait
            var seconds = 10;

            function submitForm() {
                document.forms[0].submit();
            }

            function countdown() {
                seconds = seconds - 1;
                if (seconds <= 0) {
                    // submit the form
                    submitForm();
                } else {
                    // Update remaining seconds
                    document.getElementById("countdown").innerHTML = seconds;
                    // Count down using javascript
                    window.setTimeout("countdown()", 1000);
                }
            }

            // Run countdown function
            countdown();
        </script>
    </body>
</html>
`

این کدهای مربوط به بخشی که گفتید.

![image](https://user-images.githubusercontent.com/10169591/105709167-9e0f4c80-5f2a-11eb-8385-99a39310d979.png)

**Comment by rahx** [comment]
این اطلاعات مربوط به همین سیستم هست که روی به پرداخت تنظیمش کردم:

![image](https://user-images.githubusercontent.com/10169591/105710196-03177200-5f2c-11eb-8efb-71dad86045cf.png)


چون آی پی یه جای دیگه روش تنظیمه اینجوری شد، و این سیستم داره روی سایت خودش که آی پیش تنظیمه درست کار میکنه برای به پرداخت.

من روی  لوکال خودم دارم تست نمیگیرم، مستقیم روی سرور هستن اطلاعات.

**Comment by khanzadimahdi** [comment]
<div dir=rtl>
خیلی عجیبه! اون تگ pre از کجا میاد؟
</div>

**Comment by rahx** [comment]
دقیقا مشکل منم همینه، بنظرت چجوری میتونیم، این مشکل رو ردیابی کنیم یا مشابهش رو بوجود بیاریم ؟
چون حتی اگر آدرسشم بدم، پیگیری خطا از روی صفحه مرورگر میشه همینی که من فرستادم، 
توی زرین پال هم فقط این مشکل رو دارم، روی "به پرداخت" بانک ملت دقیق و درست کار میکنه.
چیزی پیشنهاد نمیکنی برای تست بتونم ازش استفاده کنم ؟ نمونه کدی یا بخشی از کد یا هر چیز دیگه ای ؟

**Comment by rahx** [comment]
من حتی توی آدرس:
![image](https://user-images.githubusercontent.com/10169591/107732831-9d3e2f00-6d0e-11eb-8cc7-bd8f216958d2.png)
هم که میرم و قبل از رسیدن کد به blade هم تغییر ایجاد میکنم، بازم داخل pre میندازه همه چیز رو
![image](https://user-images.githubusercontent.com/10169591/107732813-8e577c80-6d0e-11eb-8fbf-c1ab04829548.png)
نتیجه:
![image](https://user-images.githubusercontent.com/10169591/107732895-cd85cd80-6d0e-11eb-845d-09a0fa015b15.png)

این مشکل رو فقط با زرین پال دارم، و با "به پرداخت" و "پارسیان" به راحتی کل سیستم کار میکنه.

**Comment by rahx** [comment]
این هم تنظیمات من:

![image](https://user-images.githubusercontent.com/10169591/107733095-57ce3180-6d0f-11eb-95e2-283fd532e575.png)
![image](https://user-images.githubusercontent.com/10169591/107733081-50a72380-6d0f-11eb-9da1-d64c725647e5.png)

![image](https://user-images.githubusercontent.com/10169591/107733151-7f24fe80-6d0f-11eb-92d9-ef2470fb3c4d.png)
![image](https://user-images.githubusercontent.com/10169591/107733121-6ddbf200-6d0f-11eb-89fa-352a6c282f7a.png)

**Comment by khanzadimahdi** [comment]
download and see the below example

how to run:

```bash
php artisan migrate;
php artisan serve;
```

then open: http://127.0.0.1:8000/invoices

[payment-example.zip](https://github.com/shetabit/payment/files/5237545/payment-example.zip)

**Comment by khanzadimahdi** [comment]
سیستم زرین پال  استیبل نیست. پیشنهاد میکنم از زرین پال استفاده نکنید

نمونه کد بالا رو هم دانلود و ازمایش کنید
