### ISSUE TITLE
Support Laravel Lumen 

### ISSUE THREAD

**Issue by ahbanavi** [shetabit/payment#141]
## Description
I'm proposing an **enhancement** for supporting [Laravel Lumen](https://lumen.laravel.com).  

## Possible implementation
I'm using Lumen for all of my REST APIs service that I write in PHP.  
I use a work around for using this package inside Lumen (since Lumen doesn't support Dispatchable trait), I remove Dispatchable trait in [Event files](https://github.com/shetabit/payment/tree/master/src/Events). you can see it [here](https://github.com/shetabit/payment/compare/master...ahbanavi:fix-for-lumen), but I'm not sure it's correct solution.  
  
Also we need to write additional info in README for registering this package in Lumen by adding this line to bootstrap/app.php  

```php
# in bootstrap/app.php  
$app->register(Shetabit\Payment\Provider\PaymentServiceProvider::class);
```

and add Payment alias to Facade array:
```php
# in bootstrap/app.php  
$app->withFacades(true,[
    'Shetabit\Payment\Facade\Payment' => 'Payment'
]);
```
And since there's no config_path Helper in lumen we must create new service provider for Lumen and don't publish configs at all.  
Also make note that `php artisan vendor:publish` does not include in Lumen and users must manually copy [config/payment.php](https://github.com/shetabit/multipay/blob/master/config/payment.php) and [views/vendor/shetabitPayment/redirectForm.blade.php](https://github.com/shetabit/payment/blob/master/resources/views/redirectForm.blade.php) in their application.
and then enable configuration file:  
```php
# in bootstrap/app.php  
$app->configure('payment');
```

beside what I said above, everything works fine in Lumen and if I knew my work around for Dispatchable trait is a good solution I would make PR myself.  
If you know correct solution for handling dispatcher issue tell me and I fix other problems for supporting Lumen.

**Comment by khanzadimahdi** [comment]
this package is mainly for Laravel, and it's not fully compatible with Lumen.

use the below package instead:

https://github.com/shetabit/multipay

it's a pure PHP package.
