### ISSUE TITLE
عدم امکان استفاده در فریم ورک لومن

### ISSUE THREAD

**Issue by ali-kh84** [shetabit/payment#142]
توی فریم ورک لومن 
در هنگام استفاده به دلیل عدم وجود ایونت ها خطای
Fatal error: Trait 'Illuminate\Foundation\Events\Dispatchable' not found
داده میشود

**Comment by khanzadimahdi** [comment]
با سلام. در فریمورک لومن از پکیج زیر استفاده کنید.

https://github.com/shetabit/multipay/
