### ISSUE TITLE
 عدم ثبت توضیحات در صورتحساب

### ISSUE THREAD

**Issue by alinemone** [shetabit/payment#144]
$invoice = (new Invoice)->amount($sefaresh->amount)
                ->detail(['description'=> $sefaresh->description])
                ->via('zarinpal');

هیچ مشکلی نیست بجز این که توضیحاتی که به همراه صورتحساب ارسال میشه هیچ جایی داخل پنل زرین پال و یا با خروجی گرفتن نشون داده نمیشه

**Comment by khanzadimahdi** [comment]
ممکنه زرین پال از این توضیحات پشتیبانی نکنه. به همین دلیل هیچ جایی نشون داده نمیشه

زرین پال جدیدا خیلی غیر استیبل شده و کلا ساختارش بهم ریخته. قبلا یادمه توضیحات رو نشون میداد

**Comment by mdabbagh-ir** [comment]
درسته زرین پال در قسمت درگاه پرداخت توضیحات نمینویسه متاسفانه.
زرین پال در قسمت تراکنش‌ها در پروفایل خودمون به عنوان توضیحات جمله زیر رو مینویسه
payment using zarinpal


کاش حداقل بشه این جمله رو موقع ایجاد صورت حساب یا هر مرحله دیگه تغییر داد و توضیحات محصول رو نوشت.

**Comment by khanzadimahdi** [comment]
<div dir=rtl>
اگه داکیومنت های پکیج رو یکبار میخوندین گیر نمیکردین توی توسعه

این مورد که گفتین رو میتونید به راحتی تغییر بدید. روی پکیج متد کانفیگ داریم

</div>

```php
// At the top of the file.
use Shetabit\Multipay\Invoice;
use Shetabit\Payment\Facade\Payment;
...

// Create new invoice.
$invoice = (new Invoice)->amount(1000);

// Purchase the given invoice with custom driver configs.
Payment::config('description', 'your description')->purchase(
    $invoice,
    function($driver, $transactionId) {
    // We can store $transactionId in database.
	}
);
```

**Comment by mdabbagh-ir** [comment]
متشکرم
اما کاش خودتون هم یک بار داکیومنت ها رو بررسی میکردید
من از همان ابتدا در داکیومنت فارسی مطالعه داشتم و اگر شما هم الان جستجئ کنید کلمه زیر رو هیچ نتیجه ای نداره
::config
اما برای تست رفتم در داکیومنت انگلیسی کلمه بالارو سرچ کردم و دیدم که اره هست

لطفا داکیومنت فارسی رو اصلاح و تکمیل کنید خیلی از موارد از داکیومنت انگلیسی اونجا منتقل نشده

متشکرم

**Comment by khanzadimahdi** [comment]
اگه جایی مشکلی هست لطفا رفع کنید و درخواست مرج بدید. سعی کنید توی توسعه پکیج مشارکت داشته باشید
