### ISSUE TITLE
چگونگی انتقال به درگاه پرداخت

### ISSUE THREAD

**Issue by mahdi1366** [shetabit/payment#145]
با سلام خدمت شما و تشکر از زحماتتون
یه سوال اساسی داشتم و اون اینه که من صفحه نهایی ام رو طراحی کردم و توش فرم گذاشتم که با تایید این فرم باید به درگاه بانک منتقل بشه کاربر. سوال من اینجاس که من اطلاعات این فرم رو به کجا باس ارسال کنم به صفحه بانک منتقل بشه درضمن من روی درگاه زرین پال کار میکنم
با تشکر

**Comment by abbasfisal** [comment]
@mahdi1366 فکرمیکنم باید [داک تنظیماتشو](https://github.com/shetabit/payment/blob/master/README-FA.md#%D8%AA%D9%86%D8%B8%DB%8C%D9%85%D8%A7%D8%AA) مجدد مطالعه کنید

**Comment by khanzadimahdi** [comment]
see the below example

how to run:

```bash
php artisan migrate;
php artisan serve;
```

then open: http://127.0.0.1:8000/invoices

[payment-example.zip](https://github.com/shetabit/payment/files/5237545/payment-example.zip)

**Comment by khanzadimahdi** [comment]
<div dir=rtl>
مثال بالا رو دانلود و راه اندازی کنید.

کدها رو میتونید بررسی کنید و با توجه به کدها درگاه خودتون رو پیاده سازی کنید
</div>

**Comment by hosseinghanbarpor** [comment]
> مثال بالا رو دانلود و راه اندازی کنید.
> کدها رو میتونید بررسی کنید و با توجه به کدها درگاه خودتون رو پیاده سازی کنید

@khanzadimahdi 

Thank you for your effort in developing this package.
In the project example needs .
in the file VerifyCsrfToken.php
```
     protected $ except = [
         'payment / * / verify',
     ];
```
Must become
```
     protected $ except = [
         'payments / * / verify',
     ];
```
Be based on your route file web.php
`Route::any('payments/{payment}/verify', 'PaymentsController@verify')->name('payment.verify');`
after this correction 419 error disappears.

I also recommend that you consider a new branch for the sample project as a proper way to use the package for new users.
