### ISSUE TITLE
دلیل پرداخت های ناموفق زیاد

### ISSUE THREAD

**Issue by amiralibk** [shetabit/payment#146]
## دلیل پرداخت های ناموفق زیاد

 چرا پرداخت های ی درگاهی مثل زرین پال اکثرا ناموفق میشه . همیچیز طبق مستندات کار کردیم . ؟
تعداد پرداخت های نا موفق بیشتر از پرداخت های موفقه که رفرنس آیدی هم براشون ثبت نمیشه ، لطفا عکس زمینه رو ببینید. 

[https://uupload.ir/files/bn53_capture.jpg](url)

**Comment by khanzadimahdi** [comment]
سلام. مبلغ واریز میشه اما وریفای نمیشه؟

**Comment by khanzadimahdi** [comment]
خودتون مراحل پرداخت رو یکبار انجام بدید ببینید چه اتفاقی میوفته و اگه لاگی دارید چک کنید.

زرین پال اخیرا مشکلات زیادی پیدا کرده و اصلا استیبل نیست

**Comment by amiralibk** [comment]
چه درگاهی استیبله که از اون استفاده کنیم؟

**Comment by amiralibk** [comment]
> سلام. مبلغ واریز میشه اما وریفای نمیشه؟

اره اینجوری هم میشه خیلی وقتا . اما انگار کاربر میره برای پرداخت ناموفق میشه و برمیگرده به حساب

**Comment by amiralibk** [comment]
بعد اصلا اگه پرداخت ناموفق هم بشه رفرنس ایدیو برنمیگردونه باز توی عکسم معلومه

**Comment by khanzadimahdi** [comment]
ترجیحا از ایدی پی + زیبال + یک پی و پولام سعی کنید استفاده کنید

**Comment by khanzadimahdi** [comment]
در هر صورت اگه حس کردید مشکل از پکیج هست و یا باگی پیدا کردین خوشحال میشم راجبش باهم صحبت کنیم و اونو رفع کنیم
