### ISSUE TITLE
user logout after comeback from bank gateway

### ISSUE THREAD

**Issue by nimaamiri92** [shetabit/payment#148]
when user go to bank and return(successful payment or fail payment both of them) user logout from his account.
I  added my `callback url` to my csrf exception route but still user logout from account.

Laravel csrf $except block work perfect because when i remove callback url, I got 419/page expire.

Laravel version 7

**VerifyCsrfToken:**

```php 
class VerifyCsrfToken extends Middleware
{
    /**
     * The URIs that should be excluded from CSRF verification.
     *
     * @var array
     */
    protected $except = [
        'payment/callback'
    ];
}
```

**And here is my route middleware:**

```php 
'web' => [
    \App\Http\Middleware\EncryptCookies::class,
    \Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse::class,
    \Illuminate\Session\Middleware\StartSession::class,
    // \Illuminate\Session\Middleware\AuthenticateSession::class,
    CustomAuthenticationSession::class,
    \Illuminate\View\Middleware\ShareErrorsFromSession::class,
    \App\Http\Middleware\VerifyCsrfToken::class,
    \Illuminate\Routing\Middleware\SubstituteBindings::class,
]
```

**Comment by nimaamiri92** [comment]
After struggling i found problem and i think it's good to share it with you, you can update readme file for others:

### Starting February 18th 2020, Chrome slowly rolled out their updated default for the SameSite attribute. The default behaviour of Chrome changed from allowing cookies in a cross-site or third-party context to denying them, unless specific attributes were included as a part of the cookie.

For resolving this problem you need in `config/session` set `SameSite` to `null` or `'none'` 
For avoiding security issue it's better to set `secure` to `true`

**Comment by khanzadimahdi** [comment]
please update readme and send a pull request. I will merge it.

**Comment by tohidnateghi** [comment]
سلام این مورد رو نمیشه با ترفند دیگه ای حل کرد؟

مثلا اگه transactionId رو عوض ذخیره کردن تو سشن به آخر کالبک اضافه کنیم بنظرتون روش خوبی نیست؟

**Comment by khanzadimahdi** [comment]
میتونید از هر روشی که به نظرتون مناسب میاد استفاده کنی

**Comment by tohidnateghi** [comment]
بله درسته ممنونم
