### ISSUE TITLE
getDrive method returns null

### ISSUE THREAD

**Issue by mvahidkhoo** [shetabit/payment#149]
## Detailed description

calling getDriver method on $invoice object always returns null, even though using default driver or set driver by via method. 

## Context

How to get the driver name on purchase to store gateway in the database?

**Comment by khanzadimahdi** [comment]
the driver will be passed to the callback function as the below

```
// Purchase the given invoice.
Payment::callbackUrl($url)->purchase(
    $invoice, 
    function($driver, $transactionId) {
    // We can store $transactionId in database.
	}
);
```

callback function will  use the invoice's driver if you set it! 
if you don't set the invoice's driver, the callback never sets it on invoice! could you add this feature and send pull request?
