### ISSUE TITLE
problem with callback behpardakht

### ISSUE THREAD

**Issue by miladbrave** [shetabit/payment#151]
HI
After accessing the behpardakht payment gateway if i want cancel payment, I got this error:
`The information you’re about to submit is not secure
Because the site is using a connection that’s not completely secure, your information will be visible to others.`
I got this message only on behpardakht.
Is there any body help me?

**Comment by khanzadimahdi** [comment]
it's related to this package or Behpardakht?

**Comment by mohamdneoo** [comment]
hi yes error callback behpardakht related to this package

**Comment by khanzadimahdi** [comment]
Chrome 86+ to warn users against submitting data to insecure forms.
activate SSL on your domain, then this warning will disappear

https://news.thewindowsclub.com/chrome-86-to-warn-users-against-submitting-data-to-insecure-forms-102405/

**Comment by miladbrave** [comment]
I activated SSL. But now i got 419 error after came back to my app!

**Comment by khanzadimahdi** [comment]
The most common reason for the 419 error is CSRF token failure. 
deactivate CSRF on your callback url.
