### ISSUE TITLE
مشکل عدم دسترسی

### ISSUE THREAD

**Issue by AmirJey** [shetabit/payment#152]
سلام خسته نباشید 

وقتی میخوام به درگاه وصل شم این اررور رو میده
```
Shetabit\Multipay\Exceptions\PurchaseFailedException
عدم دسترسی
```

کدهایی هم که قرار دادم طبق داکیومنت پکیج هستش
ممنون میشم راهنمایی کنید

**Comment by khanzadimahdi** [comment]
<div dir=rtl>
اونو توی صفحه use  کنید

</div>
