### ISSUE TITLE
method callback

### ISSUE THREAD

**Issue by IBMBAROOEI** [shetabit/payment#154]
public  function callback(Request $request){

        try {
           
            $receipt = ShetabitPayment::amount(1000)->transactionId($request->transaction_id)->verify();

            $payment->update([
                'status' => 1
            ]);

            $payment->order()->update([
                'status' => 'completed'
            ]);

            alert()->success('پرداخت شما موفق بود');
            return "پرداخت شما موفق بود";

        } catch (InvalidPaymentException $exception) {
            /**
             * when payment is not verified, it will throw an exception.
             * We can catch the exception to handle invalid payments.
             * getMessage method, returns a suitable message that can be used in user interface.
             **/
            alert()->error($exception->getMessage());
            return "ok";
        }
          وقت بخیر من برای متد برگشت میخاستم بدونم چطوری باید بگی که همون سفارش ک داره میاد همونو اپدیت کنه و یک سوال دیگه

**Comment by khanzadimahdi** [comment]
<div dir=rtl>
شما موقع انتقال کاربر به درگاه یک ادرس به عنوان callback مشخص میکنید. میتونید توی اون ادرس از مدل بایندینگ استفاده کنید و موقع برگشت کاربر به سایت ازش استفاده کنید

</div>

```html
yoursite.com/invoices/1 --> 1 is the id of your invoice
```
