### ISSUE TITLE
قسمت دوم سوال 

### ISSUE THREAD

**Issue by IBMBAROOEI** [shetabit/payment#155]
$receipt = ShetabitPayment::amount(1000)->transactionId($request->transaction_id)->verify(); این خط یعنی چی چرا دوباره اومده وریفای کرده

**Comment by khanzadimahdi** [comment]
<div dir=rtl>
در پرداخت ها سه مرحله داریم

‍۱- رزرو پرداخت که با متد purchase انجام میشه
۲- فرستادن کاربر به درگاه به منظور تکمیل پرداخت که با متد pay انجام میشه
۳- بعد از اینکه مرحله 2 انجام شد کاربر به ادرسی که ما گفتیم فرستاده میشه و اونجا باید با متد verify بررسی کنیم ببینیم ایا پرداخت درست انجام شده یا نه. که با توجه به اینکه پرداخت درست انجام شده یا نشده یه سری کار انجام میدیم
</div>
