### ISSUE TITLE
عدم ارسال شناسه تراکنش توسط درگاه پرداخت سامان کیش

### ISSUE THREAD

**Issue by ahadabasi** [shetabit/payment#157]
سلام
طبق داکیومنت و توسط کد زیر سفارش را جهت پرداخت به درگاه پرداخت ارسال میکنم
```
return ShetabPayment::purchase(
    (new Invoice)->amount((int)request('payable')),
    function($driver, $transactionId) {
        $payment = new Payment();
        $payment->order_id = request('order_id');
        $payment->user_id = auth()->id();
        $payment->transaction_id = $transactionId;
        $payment->save();
    }
)->pay()->render();
```
شناسه تراکنش که در این تست انجام دادم:
```Tig6Fno2K6M/K4CebLnTuP7QZ/tGw6c3SK8Qcc33p0luE+jgkvKXWnSJO/A1PcTTGm19H/dPqLype9oEss6UUw```
و در برگشت از درگاه مقادیری که ارسال شده را توسط دستور زیر نمایش میدم:
‍‍‍‍```return request()->all();```
و خروجی که دریافت میکنم
```
{
    State: "Canceled By User",
    StateCode: "-1",
    ResNum: "a15c85b8-ccb6-461c-bcba-8970df63a318",
    MID: "--------------",
    RefNum: null,
    CID: null,
    TRACENO: null,
    RRN: null,
    SecurePan: null
}
```
ممنون میشم راهنمایی بفرمایید ایراد کار کجاست
در یک نمونه پرداختی که موفق بوده نیز مقدار شناسه تراکنش دریافت شده با شناسه تراکنش در سیستم ما متفاوت است:
```
{
    State: "OK",
    StateCode: "0",
    ResNum: "d6942d5b-5ba3-4604-a5c0-613995ebc9ac",
    MID: "----------",
    RefNum: "GmshtyjwKStV/Io9FTpRnYb9FkTwbjkWS5i4c1Ptff",
    CID: "---------------------------------------------------------------------------------------",
    TRACENO: "823320",
    RRN: "---------------",
    Amount: "1000",
    website: "my website",
    SecurePan: "606373******3180"
}
```
در این مورد هم شناسه تراکنش در دیتابیس ما مقدار
```Tig6Fno2K6M/K4CebLnTuI5x5UE48JVbbGcC4JbNi32PlVPr+Y599bTtEZ096Z3D1ApneiBde1VoQyMhT6UAlw```
را دارد در صورتی که شناسه تراکنش ارسال شده مقدار
```GmshtyjwKStV/Io9FTpRnYb9FkTwbjkWS5i4c1Ptff```
را دارد

**Comment by khanzadimahdi** [comment]
سلام. در صورتی که مشکلی وجود داره لطفا مشکل رو رفع کنید و درخواست مرج بدید

**Comment by progintYasin** [comment]
از هلپر str::uuId() برای تولید کد تراکنش استفاده کنین خب

**Comment by khanzadimahdi** [comment]
شما نباید شماره تراکنش رو دستی ست کنید! کد زیر اشتباه هست
```
        $payment->transaction_id = $transactionId;
```

دوست عزیز لطفا از خودتون روش ابداع نکنید! داکیومنت رو اول یکبار بخونید! و اگه به مشکل خوردید کد مربوط به درایور درگاه رو چک کنید!

https://github.com/shetabit/multipay/blob/master/src/Drivers/Saman/Saman.php#L55

اون شماره ResNum شماره فاکتور شما هست که داره با invoice uuid ست میشه.

https://github.com/shetabit/payment/issues/295#issuecomment-2288619219
