### ISSUE TITLE
امکان تست پکیج

### ISSUE THREAD

**Issue by thezahedi** [shetabit/payment#158]
سلام و عرض ادب

من برای پروژه‌ام تست نوشتم ولی هیچ داکیومنتی برای نوشتن تست برای این پکیج وجود نداره!

آیا امکان Fake و Mock کردن پکیج وجود نداره؟

**Comment by khanzadimahdi** [comment]
با سلام. در حال حاضر این پکیج تست نداره. فرصت نکردم هنوز تست ها رو بنویسم و پاس کنم

در صورتی که مایل هستید میتونید تست بنویسید و درخواست مرج بدید

**Comment by khanzadimahdi** [comment]
https://github.com/shetabit/payment/issues/254
