### ISSUE TITLE
عوض نشدن مود زرین پال از تست 

### ISSUE THREAD

**Issue by mehossein** [shetabit/payment#159]
با عرض سلام و وقت بخیر 
توی یه پروژه از از زرین پال استفاده می کنم اطلاعات درایور زرین پال رو هم داخل
config/payment.php 
کامل وارد کردم و mood=normal 
قرار دادم ولی از sandboxApi 
استفاده میکنه و از رو حالت تست در نمیاد و ارورو 
Undefined property: stdClass::$sandboxApiPurchaseUrl
نمایش میده 
میشه بگید مشکل از کجاست ؟؟

**Comment by khanzadimahdi** [comment]
کش رو پاک کنید و کانفیگ رو دوباره پابلیش کنید
