### ISSUE TITLE
استفاده داینامیک از کانفیگ

### ISSUE THREAD

**Issue by sajadonline** [shetabit/payment#160]
با سلام 
من بتازگی با پکیج شما آشنا شدم و میخوام ازش استفاده کنم که چند مشکل برخوردم ممنون میشم راهنماییم کنید.

- چطور میتونم از داده های داینامیک استفاده کنم بعنوان مثال اطلاعات مرچنت و ترمینال های من در دیتابیس ذخیره هست.
- زمانی که یک درایور پرداخت فعال میکنم و بعد از برگشت از درگاه در callback verify چطور همون درایور رو صدا بزنم برای وریفای کردن ؟

ممنون از توجهتون

**Comment by khanzadimahdi** [comment]
لطفا داکیومنت ها رو بخونید
تمام سوال هایی که مطرح کردین توی داکیومنت ها هست

به صورت زیر میتونید عمل کنید

```php
// You can specify callbackUrl
Payment::callbackUrl('http://yoursite.com/verify')->purchase(
    $invoice, 
    function($driver, $transactionId) {
    	// We can store $transactionId in database.
	}
);
```

واسه کانفیگ هم به صورت زیر

```php
// Purchase the given invoice with custom driver configs.
Payment::config('mechandId', 'your mechand id')->purchase(
    $invoice,
    function($driver, $transactionId) {
    // We can store $transactionId in database.
	}
);

// Also we can change multiple configs at the same time.
Payment::config(['key1' => 'value1', 'key2' => 'value2'])->purchase(
    $invoice,
    function($driver, $transactionId) {
    // We can store $transactionId in database.
	}
);
```

**Comment by sajadonline** [comment]
ممنون از پاسختون . احساس میکنم کمی داکیومنت برای من گنگ هست.
الام من یک کلاس invoice ایجاد کردم و درایور مدنظرم رو داخلش دادم در دیباگ هم درایور انتخابی من رو بر میگردونه اما همچنان از دیفالت استفاده میکنه

` $invoice = new Invoice;
        $invoice->amount(500000);
        $invoice->via('behpardakht');


        return Payment::purchase(
            $invoice,
            function($driver, $transactionId) {
               
                dd($driver);

            }
        )->pay()->render();
`

![Screenshot from 2021-03-28 18-43-53](https://user-images.githubusercontent.com/3065746/112755402-c0d6e380-8ff5-11eb-8e8c-42442d97068a.png)


و اینکه زمانی که در کال بک چطور متوجه بشم از کدوم درایور استفاده شده ؟ ایا باید کلای invoice مجدد ایجاد کنم و getdetail کنم ؟ اینرو هم بیشتر توضیح بدید ممنون میشم

**Comment by khanzadimahdi** [comment]
<div dir=rtl>
موقع purchase کردن باید مشخصات رو نگهداری کنید و در کالبک ازش استفاده کنید
</div>
