### ISSUE TITLE
مشاهده خطای ناشناخته 

### ISSUE THREAD

**Issue by miladparsi** [shetabit/payment#162]
<div dir=rtl>
سلام من مدتیه که از درگاه شما استفاده میکنم و عالیه
از امروز موقع استفاده همش پیام: خ خطای ناشناخته رخ داده است. 
برام نشون داده میشه در صورتی که دیشب کدها کامل اجرا میشد و مشکلی نداشت
چیزی هم نشون نمیده که بدونتم مشکل از کجاست
میتونید راهنمایی کنید
</div>

**Comment by ehsan140** [comment]
بله میتونم براتون اکتیو کنم هزینه داره ۱۰ میلیون تومن هزینه اول

**Comment by khanzadimahdi** [comment]
سلام وقت بخیر

از چه درگاهی استفاده میکنید؟

**Comment by miladparsi** [comment]
سلام زرینپال

**Comment by ehsan140** [comment]
شما کجارو میخواین فقط زرین پال؟

**Comment by miladparsi** [comment]
اره فعلا فقط زرین پال
تا دیشب کار میکرد
امروز این پیامو میده همش

**Comment by khanzadimahdi** [comment]
بهتون پیشنهاد میدم از زرین پال استفاده نکنید. اخیرا ازین مشکلات زیاد پیدا میکنه و یکهو از دسترس خارج میشه

از ایدی پی استفاده کنید خیلی بهتره.

مشکل شما از سمت زرین پال هست و به پکیج مربوط نمیشه

**Comment by miladparsi** [comment]
> 
> 
> سلام وقت بخیر
> 
> از چه درگاهی استفاده میکنید؟
> 
> اگه کار میکرده و یکهو به مشکل خورده ممکنه به خاطر سرویس دهنده درگاه باشه

منظورتون زرینپاله؟ اونجا هم تیکت زدم و گفتن مشکلی نیست
راهی نیست که بشه خطارو دید کامل؟

**Comment by khanzadimahdi** [comment]
لینک زیر رو بررسی کنید کامل پکیج رو اموزش داده

https://ditty.ir/posts/laravel-online-payment-introduction/J0zKn
