### ISSUE TITLE
ارور موقع برگشت از درگاه به سایت

### ISSUE THREAD

**Issue by miladparsi** [shetabit/payment#164]
وقتی درگاه رو روی سندباکس میزارم کار میکنه و برمیگرده به سایت ولی وقتی روی زرین گیت میزارم موقع برگشت از بانک این خطارو میده:

`Shetabit\Multipay\Exceptions\InvalidPaymentException: درخواست مورد نظر آرشيو شده است in`

یعنی پول از حسابم کم میشه ولی برنمیگرده به سایتم و وریفای نمیشه پرداخت  
اینم کد وریفای:

`
 $receipt = Payment::amount(Session::get('cost'))->transactionId(Session::get('transactionId'))->verify();
`
مشکل از همین خطه تا قبل این اجرا میشه کامل
راهنمایی کنید ممنون میشم

**Comment by khanzadimahdi** [comment]
سلام. فکر کنم درگاه زرین پال یه تغییراتی داده که درایورش باید تغییر کنه

پیشنهاد میکنم زرین پال استفاده نکنید. اخیرا خیلی تغییرات میدن

**Comment by khanzadimahdi** [comment]
سلام درگاه زرین پال رو با توجه به اخرین ورژن ای پی آی که ارائه دادن بروز رسانی کردم. لطفا پکیج رو اپدیت کنید و فایل کانفیگ پکیج رو حذف کنید و دوباره پابلیش کنید

**Comment by miladparsi** [comment]
مرسی از پیگیریتون
فردا حتما انجام میدم نتیجه رو بهتون میگم🙏🙏🙏
