### ISSUE TITLE
مشکل گنگ بودن وضعیت پرداخت

### ISSUE THREAD

**Issue by ami-hp** [shetabit/payment#165]
## پیشنهاد

قبلا که از درگاه زرین پال استفاده میکردم، زمان برگشت از درگاه چندین حالت پیش میومد
مثلا:
* خطا توی مقایسه ی قیمت
* موفقیت در پرداخت
* قبلا پرداخت شده
* و غیره

پیشنهاد میکنم این حالتها به جای اینکه به عنوان پیام 
try catch
شده برگردن ، یه کد برگردونن که بشه راحت مدیریتش کرد
ممنون

**Comment by khanzadimahdi** [comment]
با سلام. بعله حرف شما درسته

اگه امکانش هست این موارد رو به درگاه ها اضافه کنید و درخواست مرج بدید تا فیکس بشه

**Comment by khanzadimahdi** [comment]
برگرداندن کد در توسعه کلین نیست. پیشنهاد میکنم کتاب کلین کد رابرت سی مارتین رو مطالعه کنید

موفق باشید
