### ISSUE TITLE
Receipt class after verify doesn't provide enough information to store

### ISSUE THREAD

**Issue by Danger-Mkh** [shetabit/payment#168]
`$receipt = Payment::transactionId($trans_id)->verify();`
`$receipt` just contains two item :
* transaction id and 
* driver.

but bank return more information about payment.
i use idpay.

and one more thing the package doesn't have inquiry functionality.

thank you.

**Comment by khanzadimahdi** [comment]
could you add this features to package and send pull request?

**Comment by hsharghi** [comment]
I have added more information to receipt for some drivers and more to come. e.g `Sadad`

```php
        $receipt = $this->createReceipt($body->SystemTraceNo);
        $receipt->detail([
            'orderId' => $body->orderId,
            'traceNo' => $body->SystemTraceNo,
            'referenceNo' => $body->RetrievalRefNo,
            'description' => $body->description,
            'cardNo' => null,
        ]);

        return $receipt;
```


but I was thinking about more structured way of adding info instead of key value pairs. 
Does anybody have a better idea or it's just fine and I should create a pull request as it is?

**Comment by khanzadimahdi** [comment]
@hsharghi 
It will be fine if you add this.

**Comment by Danger-Mkh** [comment]
@khanzadimahdi and i found another problem.
the `order_id`
there is no way to set it when you reqeusting a payment or redirect to pay.
is just created by uuid without asking or setting some where.

**Comment by khanzadimahdi** [comment]
یکسری از درگاه ها فیکس شد. کامپوزر اپدیت بزنید و پکیج خودتون رو بروز کنید تا بتونید ازش استفاده کنید

باقی درگاه ها هم به زودی توسعه ی بیشتری پیدا میکنن و این مشکل رفع میشه

ممنونم از همه
