### ISSUE TITLE
مشکل خطای ناشناخته

### ISSUE THREAD

**Issue by allllrez** [shetabit/payment#170]
"message": "خطای ناشناخته رخ داده است.",
    "exception": "Shetabit\\Multipay\\Exceptions\\PurchaseFailedException",
    "file": "E:\\royal\\backend-master\\vendor\\shetabit\\multipay\\src\\Drivers\\Zarinpal\\Zarinpal.php",
    "line": 83,
    "trace": [
        {
            "file": "E:\\royal\\backend-master\\vendor\\shetabit\\multipay\\src\\Payment.php",
            "line": 212,
            "function": "purchase",
            "class": "Shetabit\\Multipay\\Drivers\\Zarinpal\\Zarinpal",
            "type": "->"
        },

با تغییر درایور هم باز این ارور میاد

**Comment by khanzadimahdi** [comment]
با سلام. دوست عزیز زرین پال مثل اینکه ساختار خودشو عوض کرده و به همین دلیل این ساختار درون پکیج هم باید تصحیح بشه

کد خودتون رو روی سندباکس بزارید و چک کنید اگه کار کرد یعنی اوکی هست و مشکلی نداره

درایور زرین پال رو تا چند روز اینده بروز رسانی میکنم و پکیج رو اپدیت میکنم تا این مشکل رفع بشه
