### ISSUE TITLE
اطلاعات ناقص در برگشت

### ISSUE THREAD

**Issue by meisam22605** [shetabit/payment#171]
سلام.
مواقعی که پرداخت موفق هست درگاه ها برای سایت مقابل اطلاعاتی را ارسال میکنند، از جمله شماره کارتی (ناقص و هش شده) که با آن پرداخت انجام شده، آیا این پکیج این آیتم را دارد؟

**Comment by khanzadimahdi** [comment]
با سلام. دوست عزیز این قابلیت تازه اضافه شده و تا اخر هفته توی ورژن جدید منتشر میشه

برای اطلاعات بیشتر لینک زیر رو میتونید ببینید

https://github.com/shetabit/payment/issues/168

درصورتی که علاقه دارید میتونید موارد مورد نیاز خودتون رو اضافه کنید و درخواست مرج بدید تا در توسعه ی پکیج سهیم باشید
