### ISSUE TITLE
Unprocessable Entity in payir gateway

### ISSUE THREAD

**Issue by tohidnateghi** [shetabit/payment#172]
سلام در درگاه پرداخت pay.ir خطای Unprocessable Entity میده موقع وریفای کردن

البته با درگاه تست امتحان کردم، درگاه ندارم

**Comment by khanzadimahdi** [comment]
سلام وقت بخیر. لطفا کد خودتون هم قرار بدید

**Comment by tohidnateghi** [comment]
Trying to access array offset on value of type null
 متن خطای اصلی اینه، وقتی تو خط 134 کلاس payir dd($response); میگیرم میبینم استتوس کد 422 بر میگردونه

`
        $transactionId = session()->get('transactionId');
        $amount = session()->get('amount');

        $transaction = Transaction::where('transID', $transactionId)->firstOrFail();

        $order = $transaction->transactionable;

        $gateway_configs = get_gateway_configs($gateway);

        try {
            $receipt = Payment::via($gateway)->config($gateway_configs)->amount($amount)->transactionId($transactionId)->verify();

            DB::table('transactions')->where('transID', $transactionId)->update([
                'status'               => 1,
                'amount'               => $order->price,
                'factorNumber'         => $order->id,
                'mobile'               => $order->mobile,
                'traceNumber'          => $receipt->getReferenceId(),
                'message'              => 'پرداخت موفق با درگاه ' . $order->gateway,
                'user_id'              => $order->user_id,
                'transactionable_type' => Order::class,
                'transactionable_id'   => $order->id,
                "updated_at"           => Carbon::now(),
            ]);

            $order->update([
                'status' => 'paid',
            ]);

            event(new OrderPaid($order));

            return redirect()->route('front.orders.show', ['order' => $order])->with('message', 'ok');
        } catch (\Exception $exception) {
                return redirect()->route('front.orders.show', ['order' => $order])->with('transaction-error', $exception->getMessage());
        }
`

این هم کد من

**Comment by khanzadimahdi** [comment]
فک کنم مستنداتش عوض شده و درگاه باید کدش یه تغییراتی بکنه

میتونید فیکسش کنید و درخواست مرج بدید؟ 

کدش رو میتونید اینجا پیدا کنید

https://github.com/shetabit/multipay/blob/master/src/Drivers/Payir/Payir.php

**Comment by tohidnateghi** [comment]
باشه سعی خودم رو میکنم اکه نتونستم بهتون میگم، ممنون

**Comment by khanzadimahdi** [comment]
فیکس شد. پکیج خودتون رو اپدیت کنید. کامپوزر اپدیت بزنید
