### ISSUE TITLE
مشکل اخیر در درگاه های پرداخت و درخواست راه حل

### ISSUE THREAD

**Issue by mrmmg** [shetabit/payment#173]
## Detailed description

اخیرا درگاه های پرداخت با مرورگر کروم و روش
post
مشکل دارد و خود درگاه ها روش
get
را بعنوان روش پیشفرض قرار میدهند. مشکل از جایی شروع می شود که این پکیج برای تایید تراکنش به مقدار
amount
نیاز دارد و برای مثال آیدی پی این مقدار را برنمیگرداند، راه حلی وجود دارد؟ چون برای وریفای کردن در پکیج جایی پیدا نکردم که خودم بنویسم.

## Your environment

Include as many relevant details about the environment you experienced the bug in and how to reproduce it.

* Version used (e.g. PHP 7.2, HHVM 3): PHP 7.4, Xampp Server
* Operating system and version (e.g. Ubuntu 19.04, Windows 10): Windows 10

**Comment by mrmmg** [comment]
مشکل فوق را حل کرده ام

چرا در این پکیج اطلاعات شماره کارتی که برای مثال idpay 
برمیگرداند در خروجی موجود نیست؟ حتی اینکار از طریق درایور کاستوم نیز امکان پذیر نیست.

@khanzadimahdi

**Comment by khanzadimahdi** [comment]
توی درایور کاستوم (درایوری که خودتون بسازید) همه چیز قابل مدیریت هست و اینکه میگید امکان پذیر نیست اشتباهه

در درایور ایدی پی و تمامی درایور ها یکسری مشخصات مشترک برگردونده میشه.

برای تمام درایور ها اطلاعاتی که از سمت بانک برمیگرده رو به زودی روی پکیج اصلاح میکنیم و منتشر میکنیم
