### ISSUE TITLE
نمایش کد پیگیری در پرداخت ناموفق

### ISSUE THREAD

**Issue by mehdijalalii** [shetabit/payment#174]
قصد دارم تو پرداخت ناموفق به کد پیگیری دسترسی پیدا کنم. چجوری این کار ممکن میشه؟ 

    try {

      $receipt = Payment::transactionId($transaction_id)->verify();
      // کد پیگیری پرداخت موفق
      $receipt->getReferenceId()

    } catch (InvalidPaymentException $exception) {
      // کد پیگیری پرداخت ناموفق
      // ???????????????
    }

**Comment by khanzadimahdi** [comment]
پرداخت ناموفق کد پیگیری نخواهد داشت. کدپیگیری فقط بعد از پرداخت و برای پرداخت موفق ارائه میشه

اگه میخواید پرداخت رو پیگیری کنید میتونید با شماره تراکنش اینکار رو انجام بدید

شماره تراکنش بعد از ران کردن تابع زیر درون کالبک به شما داده میشه

```php
// payment::purchase
```
