### ISSUE TITLE
verify transactions via zarinpal driver

### ISSUE THREAD

**Issue by sajadabs** [shetabit/payment#177]
hi dear
i dont understand how to verify transactions returns success when using zarinpal driver.
when transaction complete system redirect me to callback url and add some queries on url (Authority and Status)!
can you explain me how can i verify transactions using zarinpal driver?
i use seperate backend and frontend and use api for requests.
thanks.

**Comment by khanzadimahdi** [comment]
create a /payment/verification/{id} route and use it as redirect callback url.

the bank will redirect user to this route and you can access the payment `id` and achieve payment's amount and `transactonId`, and verify them using given data.

**Comment by sajadabs** [comment]
but the bank redirect me to this page 
`/payment/%7Bid%7D/verification?Authority=000000000000000000000000000000521875&Status=NOK`
and i can not access to any id!

**Comment by khanzadimahdi** [comment]
what is `%7Bid%7D` in the `/payment/%7Bid%7D/verification` ?????

in `/payment/{id}/verification` we have `{id}` , which means you should create a table for payments and use model binding.
