### ISSUE TITLE
change some property in response body on sadad gateway

### ISSUE THREAD

**Issue by sajadabs** [shetabit/payment#178]
hi,
 some propeties name in response object when you want verify has changed! 
```
        $receipt->detail([
            'orderId' => $body->OrderId, // before : orderId | after : OrderId
            'traceNo' => $body->SystemTraceNo,
            'referenceNo' => $body->RetrivalRefNo, // before : RetrievalRefNo | after : RetrivalRefNo
            'description' => $body->Description, // before : description | after : Description
        ]);
```

**Comment by khanzadimahdi** [comment]
what's wrong with it? please fix it, test it, and finally send a pull request.

**Comment by sajadabs** [comment]
I think you should create a develop branch for pull request.
cuz show me` Choose different branches or forks above to discuss and review changes.`
it's true?

**Comment by khanzadimahdi** [comment]
I close this issue due to inactivity
