### ISSUE TITLE
مبالغ به ریال

### ISSUE THREAD

**Issue by mhd-shf** [shetabit/payment#179]
سلام 
 به نظر من مبالغ باید همه به ریال باشد و بر اساس هر درایور شما تغییرات لازم رو انجام بدین
مثلا زرین پال مبالغ رو به تومان در نظر میگیره که این باید در درایور زرین پال مبلغ ریالی رو بگیره و تقسیم بر 10 کنه و به بانک ارسال کنه
این که ما این بخش از کار رو کنترل کنیم به نظر نامناسب میاد

با تشکر

**Comment by khanzadimahdi** [comment]
با سلام. توی پکیج همه ی مبلغ ها به تومان حساب میشن

دلیلش هم اینه که ما در نهایت پولمون رو به تومان در نظر میگیریم و خرج میکنیم و اینکه همه چیز تومان باشه از لحاظ ذهنیتی مدیریتش راحت تره تا ریال

**Comment by vahidalvandi** [comment]
نه اشتباهه

**Comment by khanzadimahdi** [comment]
@vahidalvandi 

من متوجه نشدم چی فرمودین. اما هرچیزی که مدنظرتون هست رو توسعه بدید و درخواست مرج بزارید براش و توی توسعه ی پکیج مشارکت کنید
