### ISSUE TITLE
Shetabit\Multipay\Exceptions\PurchaseFailedException درخواست مورد نظر يافت نشد.

### ISSUE THREAD

**Issue by farshidahmadianpin** [shetabit/payment#180]
laravel 8.*
تا چند وقت پیش بصورت کامل کار میکرد.، اما یهو بدون هیچ دلیلی شروع کرد این ارور رو برای استفاده از درگاه پرداخت زرین پال میده

**Comment by khanzadimahdi** [comment]
سلام وقت بخیر

زرین پال ساختار درگاه خودشو عوض کرده و استیبل عمل نمیکنه

درایور زرین پال باید با توجه به ساختار جدیدی که ارائه کرده تغییر کنه

اگه امکانش هست درایور زرین پال رو با توجه به اخرین تغییراتی که درگاهش داده بروز رسانی کنید و درخواست مرج بدید

**Comment by khanzadimahdi** [comment]
سلام درگاه زرین پال رو با توجه به اخرین ورژن ای پی آی که ارائه دادن بروز رسانی کردم. لطفا پکیج رو اپدیت کنید و فایل کانفیگ پکیج رو حذف کنید و دوباره پابلیش کنید
