### ISSUE TITLE
استفاده از درگاه پرداخت پی پال 

### ISSUE THREAD

**Issue by eniiack** [shetabit/payment#181]
سلام وقت بخیر ، ممنون از شما بابت ارائه این پکیج خوب وکاربردی.
میخواستم بپرسم درگاه پرداخت پی پال رو ارائه نمیکنید؟چون خیلی وقت هست که منتظرم اضافه بشه به این پکیج

**Comment by khanzadimahdi** [comment]
https://github.com/shetabit/payment/issues/102#issuecomment-863122903

**Comment by khanzadimahdi** [comment]
it is a duplicate of #102 so I closed this.
