### ISSUE TITLE
please add paypal 

### ISSUE THREAD

**Issue by vahidalvandi** [shetabit/payment#182]
please add plugin paypal

**Comment by khanzadimahdi** [comment]
I don't have its documentations and any API for testing. please add it and send a pull request, I will merge it.

**Comment by vahidalvandi** [comment]
also i dont have any document but i found same tutorial about it

https://websolutionstuff.com/post/how-to-integrate-paypal-payment-gateway-in-laravel
https://clickysoft.com/how-to-integrate-paypal-payment-gateway-in-laravel/

**Comment by khanzadimahdi** [comment]
please add it and send pull request, i will merge.

**Comment by khanzadimahdi** [comment]
you can find Paypal driver's structure in the below address

https://github.com/shetabit/multipay/blob/master/src/Drivers/Paypal/Paypal.php
