### ISSUE TITLE
Adding status code in exceptions

### ISSUE THREAD

**Issue by MOstadi** [shetabit/payment#183]
I think it can be helpful if exceptions returns error code in their code property.
![SharedScreenshot](https://user-images.githubusercontent.com/26692474/123545726-d2539700-d76e-11eb-8214-52b434ec8c83.jpg)
It's easier to check for integers instead of message to create appropriate response.

**Comment by khanzadimahdi** [comment]
please fix it and send pull request

**Comment by MOstadi** [comment]
I sent it in multipay repo
