### ISSUE TITLE
داکیومنت ها خیلی ایراد داره

### ISSUE THREAD

**Issue by vahidalvandi** [shetabit/payment#184]
## Detailed description

Provide a detailed description of the change or addition you are proposing.

Make it clear if the issue is a bug, an enhancement or just a question.

## Context

Why is this change important to you? How would you use it?

How can it benefit other users?

## Possible implementation

Not obligatory, but suggest an idea for implementing addition or change.

## Your environment

Include as many relevant details about the environment you experienced the bug in and how to reproduce it.

* Version used (e.g. PHP 7.2, HHVM 3):
* Operating system and version (e.g. Ubuntu 19.04, Windows 10):
* Link to your project:
* ...
* ...

**Comment by khanzadimahdi** [comment]
پکیج اوپن سورس هست. هرجایی که ایراد پیدا کردین تصحیح کنید و درخواست مرج بدید تا مشکل رفع بشه

موقعی که ایشو میزنید محتوای اون رو نیز وارد کنید. صرفا یه تایتل نزنید و اسپم نکنید
