### ISSUE TITLE
مشکل نسخه جدید

### ISSUE THREAD

**Issue by vahidalvandi** [shetabit/payment#187]
دوست گرامی من آماتور نیستم . ولی چرا مثالی که گذاشتی با کانفیگ زیرپال نسخه ۴ جواب نمیده ؟؟
همش پیام میده 

اطلاعات ارسال شده ناقص است.

ولی طبق مثال خودت کار میکنه

   ```
     'zarinpal' => [
            /* normal api */
            'apiPurchaseUrl' => 'https://ir.zarinpal.com/pg/services/WebGate/wsdl',
            'apiPaymentUrl' => 'https://www.zarinpal.com/pg/StartPay/',
            'apiVerificationUrl' => 'https://ir.zarinpal.com/pg/services/WebGate/wsdl',

            /* sandbox api */
            'sandboxApiPurchaseUrl' => 'https://sandbox.zarinpal.com/pg/services/WebGate/wsdl',
            'sandboxApiPaymentUrl' => 'https://sandbox.zarinpal.com/pg/StartPay/',
            'sandboxApiVerificationUrl' => 'https://sandbox.zarinpal.com/pg/services/WebGate/wsdl',

            /* zarinGate api */
            'zaringateApiPurchaseUrl' => 'https://ir.zarinpal.com/pg/services/WebGate/wsdl',
            'zaringateApiPaymentUrl' => 'https://www.zarinpal.com/pg/StartPay/:authority/ZarinGate',
            'zaringateApiVerificationUrl' => 'https://ir.zarinpal.com/pg/services/WebGate/wsdl',

            'mode' => 'sandbox', // can be normal, sandbox, zaringate
            'merchantId' => '1ff82d2a-305f-11e6-8dbd-005056a205be',
            'callbackUrl' => 'http://yoursite.com/path/to',
            'description' => 'payment using zarinpal',
        ],
```

با این جدید و پروژه مثال شما این کانفیگ کار نمیکنه

      ```
  'zarinpal' => [
            /* normal api */
            'apiPurchaseUrl' => 'https://api.zarinpal.com/pg/v4/payment/request.json',
            'apiPaymentUrl' => 'https://www.zarinpal.com/pg/StartPay/',
            'apiVerificationUrl' => 'https://api.zarinpal.com/pg/v4/payment/verify.json',

            /* sandbox api */
            'sandboxApiPurchaseUrl' => 'https://sandbox.zarinpal.com/pg/services/WebGate/wsdl',
            'sandboxApiPaymentUrl' => 'https://sandbox.zarinpal.com/pg/StartPay/',
            'sandboxApiVerificationUrl' => 'https://sandbox.zarinpal.com/pg/services/WebGate/wsdl',

            /* zarinGate api */
            'zaringateApiPurchaseUrl' => 'https://ir.zarinpal.com/pg/services/WebGate/wsdl',
            'zaringateApiPaymentUrl' => 'https://www.zarinpal.com/pg/StartPay/:authority/ZarinGate',
            'zaringateApiVerificationUrl' => 'https://ir.zarinpal.com/pg/services/WebGate/wsdl',

            'mode' => 'normal', // can be normal, sandbox, zaringate
            'merchantId' => '',
            'callbackUrl' => 'http://yoursite.com/path/to',
            'description' => 'payment using zarinpal',
        ],
```

**Comment by khanzadimahdi** [comment]
<div dir=rtl>
دوست عزیز شما رگباری داری ایشو میزنی و اصلا داکیومنت رو هم نمیخونی تا به ارور یا خطا میخوری ایشو میزنی
خودت ببین از صبح چندتا ایشو زدی که یکدونه هم بدردبخور و درست نبود

به هر حال نمونه کد براتون میزارم براتون که درست هم کار میکنه و تست شده
</div>

[laravel.zip](https://github.com/shetabit/payment/files/6729019/laravel.zip)

```bash
php artisan migrate
php artisan serve
```

then go to http://127.0.0.1:8000/invoices/1/pay

**Comment by vahidalvandi** [comment]
ممنونم ازت
واقعا دستت درد نکنه من هم در توسعه بهت کمک میکنم شما باید در نظر داشته باشی که داکیومنت ها قدیمی هستند و دچار سردرگمی میکنن

**Comment by vahidalvandi** [comment]
فقط با زرین پال کار میکنه با ملت کار نمیکنه وقتی از درگاه میخواد برگرده یا تایید یا لغو کاربر در همان روت خطای 419 میده

**Comment by vahidalvandi** [comment]
یک اشتباهی که وجود داره اینه که بانک ها ریال دریافت میکنن و واسط ها تومان و این تداخل دارد . بهتر است متدی داشته باشد که بر اساس درگاه واحد ورودی را خودکار به ریال تبدیل کند

**Comment by khanzadimahdi** [comment]
توی پکیج همه تومان هستن

**Comment by vahidalvandi** [comment]
اون خطای چهارصد و نوزده هم به خاطر این هست که سی اس ار اف توکن مشکل میخوری باید روی روت وریفای غیر فعالش کنی


در همان میدلور 
verifyCsrf except?

**Comment by vahidalvandi** [comment]
خدایش خیلی مشکل داره 
ببین من یک ایده بهت میدم چون ساختار پکیج نمی شناسم
شما عددی را که از کاربر میگیری بعدش یک واحد ارزی هم بگیر با یک متد به نام
currecny
** واگر ورودی تومان بود ولی واحد ارزی درگاه  ریال بود تومان را به ریال تبدیل کند** 
**برعکس اگر ورودی ریال بود و درگاه تومان بود عدد ریال را به تومان تبدیل کند** 
چون ممکنه سایت واحد ریال داشته باشد یا تومان یا ممکنه چند ارزی باشد نمیشه که کلا به تومان تبدیل کنیم بعد به پکیج ارسال کنیم . !!!
