### ISSUE TITLE
Irankish driver error

### ISSUE THREAD

**Issue by amirhossein-edalati** [shetabit/payment#188]
Hello,
I have a problem with irankish driver.
Please help me

`Uncaught SoapFault exception: [WSDL] SOAP-ERROR: Parsing WSDL: Couldn't load from 'https://ikc.shaparak.ir/XToken/Tokens.xml' : failed to load external entity "https://ikc.shaparak.ir/XToken/Tokens.xml" in`

**Comment by khanzadimahdi** [comment]
Do you run it on a local server? you must introduce your server IP to Irankish gateway.

**Comment by khanzadimahdi** [comment]
I close this issue due to inactivity.
