### ISSUE TITLE
chera class payment khodesh return nadare va bayad to controller return konim ?

### ISSUE THREAD

**Issue by imhaji** [shetabit/payment#189]
## Detailed description

Provide a detailed description of the change or addition you are proposing.

Make it clear if the issue is a bug, an enhancement or just a question.

## Context

Why is this change important to you? How would you use it?

How can it benefit other users?

## Possible implementation

Not obligatory, but suggest an idea for implementing addition or change.

## Your environment

Include as many relevant details about the environment you experienced the bug in and how to reproduce it.

* Version used (e.g. PHP 7.2, HHVM 3):
* Operating system and version (e.g. Ubuntu 19.04, Windows 10):
* Link to your project:
* ...
* ...

**Comment by khanzadimahdi** [comment]
به دلیل اینکه شما نمیدونید چجوری ایشو بزنید و فرمت ایشو رو رعایت نکردین اونو میبندم

**Comment by imhaji** [comment]
az shoma barname nevis montakhab keshavar baeede intori harf zadan mohandes
man soal miporsam ke yad begiram na inke ba raftar shoma zade besham ba in
kar az baraneme nevisi
shoma yek farde ba savad hastin kholase man kheili narahat shodam

**Comment by khanzadimahdi** [comment]
دوست عزیز فرمت ایشو خودتون رو تصحیح کنید و دسکریپشن کامل بزارید

واسه زمان همه ارزش قائل بشید. اینکه سریع یه تایتل بنویسید ایشو بزارید و من نیم ساعت وقت بزارم و بیستا سوال بپرسم تا منظور اصلی شما رو متوجه بشم کار درستیه؟

**Comment by khanzadimahdi** [comment]
در مورد سوال شما باید بگم که ریترن باید انجام بدید به این دلیل که رسپانس اماده میشه و باید از کنترلر برگشت داده بشه

**Comment by imhaji** [comment]
ممنون مهندس چشم چون بلد نبودم این کارو نکردم حتما سعی میکنم دیسکریپشن
بنویسم براش مممنونننننننننننننننننننننننننننننن❤
