### ISSUE TITLE
عدم برگشت دادن جزئیات بیشتر تراکنش مثل شماره کارت

### ISSUE THREAD

**Issue by tohidnateghi** [shetabit/payment#190]
سلام خیلی پکیج خوبی هست من خیلی وقته ازش استفاده میکنم فقط چرا جزئیات بیشتر مربوط به تراکنش رو برنمیگردونه؟
مثلا شماره کارت کاربر پرداخت کننده

اگه این بخش رو اضافه کنیم مرج میکنید؟

**Comment by khanzadimahdi** [comment]
سلام. بعله اضافه کنید مرج میشه

**Comment by arbabi2010** [comment]
سلام . ایا شماره کارت به جزییات اضافه شده ؟
