### ISSUE TITLE
Trying to access array offset on value of type null 

### ISSUE THREAD

**Issue by zzzz6663** [shetabit/payment#191]
سلام و وقت به خیر
کد من موقع ریدایرکت شد به زرین پال این ارور رو  میده 

کارهایی که توی 
این 
[لینک](https://github.com/shetabit/payment/issues/73)
گفتید رو انجام دادم 
باز نشد 
لاراول 8  php7.4

**Comment by zzzz6663** [comment]
البته در حالت sanbox
درست کار میکنه ولی در حالت نرمال ین ارور  رو میده

**Comment by khanzadimahdi** [comment]
ورژنی که استفاده میکنید چیه؟

**Comment by khanzadimahdi** [comment]
ورژن پکیج  مولتی پی رو به اخرین ورژن اپدیت کنید. فایل کانفیگ رو پاک کنید و دوباره پابلیش کنید بعدش چک کنید ببینید مشکل حل شده یا نه

```
composer update shetabit/multipay
```

**Comment by zzzz6663** [comment]
ممنون چک میکنم خبرتون میکنم

‫‪mahdikhanzadi‬‏ ***@***.***‬‏> در تاریخ یکشنبه ۲۵ ژوئیهٔ
۲۰۲۱ ساعت ۱۰:۵۲ نوشت:‬

**Comment by khanzadimahdi** [comment]
https://github.com/shetabit/multipay/pull/97
