### ISSUE TITLE
استفاده از مد sandobx

### ISSUE THREAD

**Issue by Abolfazl-Dalily** [shetabit/payment#192]
سلام 
برای استفاده از مد سندباکس آدرس تابع کال بک در تنظیمات چی باید ست بشه ؟‌ ( برای درگاه زرین پال) 
من وقتی آدرس روت لوکالی که تعریف کردم می زارم بعد از ریدایرکت اول صفحه زیر رو می بینم 
![Screenshot from 2021-07-11 18-02-59](https://user-images.githubusercontent.com/52946636/125197329-6135d880-e272-11eb-9e5e-444520dacdc4.png)
بعد وقتی گزینه پرداخت موفق رو انتخاب می کنم صفحه زیر برام باز می شه 
![Screenshot from 2021-07-11 18-03-10](https://user-images.githubusercontent.com/52946636/125197331-63983280-e272-11eb-8e80-0d9da2f8c74c.png)

**Comment by rezasm** [comment]
اگر توی فایل کانفیگ ست کردی و نشد میتونی کال بک رو توی کد به این شکل هم تعریف کنی 
`return Payment::callbackUrl("http://mysite.dev/payment-result")->purchase($invoice, function($driver, $transactionId) {
            // Store data in database

        })->pay()->render();`
