### ISSUE TITLE
ارور SOAP-ERROR: Parsing WSDL هنگام رفتن به درگاه پرداخت 

### ISSUE THREAD

**Issue by mehossein** [shetabit/payment#193]
با سلام 
هنگام رفتن به درگاه پرداخت این ارور به من نمایش داده میشه 
"SOAP-ERROR: Parsing WSDL: Couldn't load from 'https://www.zarinpal.com/pg/rest/WebGate/PaymentRequest.json' : failed to load external entity "https://www.zarinpal.com/pg/rest/WebGate/PaymentRequest.json"
میشه راهنمایی کنید .
(soap فعاله )

**Comment by khanzadimahdi** [comment]
از ورژن چند استفاده میکنید؟ درگاه روی چه حالت هست؟

وقتی سوال میپرسید جزییات رو هم لطفا بگید. مثل اینکه زنگ بزنید اژانس بگید یه تاکسی بفرست ادرس ندید

**Comment by mehossein** [comment]
من از ورژن 3 پکیج استفاده میکنم 
رو حالت normal این ارور رو نشون میده

**Comment by mehossein** [comment]
مشکل حل کردم 
ممنون

**Comment by Saeeed-B** [comment]
@mehossein چطور حل شد 
من هم این مشکل رو دارم.
@khanzadimahdi 
وقتی انتقال دادم روی سرور این ارور رو داد

**Comment by khanzadimahdi** [comment]
https://github.com/shetabit/payment/issues/228
