### ISSUE TITLE
redirectForm.blade.php

### ISSUE THREAD

**Issue by bahiraei** [shetabit/payment#195]
سلام این امکان وجود داره که بتونیم ریدایرکت ویو رو  سفارشی سازی کنیم؟

اگر بله به چه صورت؟

**Comment by khanzadimahdi** [comment]
سلام. بعله امکانش هست. وندور رو پابلیش کنید بعدش ریداریکت ویوو در دسترس شما خواهد بود

```bash
php artisan vendor:publish
```
