### ISSUE TITLE
Undefined index: message 

### ISSUE THREAD

**Issue by kamalgharejeloo** [shetabit/payment#196]
when verify zarinpal payment , i get this error:

ErrorException
Undefined index: message
http://127.0.0.1:8000/panel/vip/verify?Authority=A00000000000000000000000000XXXXXXXXX&Status=OK 

vendor\shetabit\multipay\src\Drivers\Zarinpal\Strategies\Normal.php:165

**Comment by khanzadimahdi** [comment]
update `shetabit/multipay` to latest version.

```bash
composer update shetabit/multipay
```

**Comment by kamalgharejeloo** [comment]
tnx mahdi
This error was resolved but one line below I encountered a new error 

Undefined index: code 
$code = $result['errors']['code'];

**Comment by khanzadimahdi** [comment]
please fix it and send merge request.

**Comment by kamalgharejeloo** [comment]
when i push my request :
remote: Permission to shetabit/multipay.git denied to kamalgharejeloo.

This problem occurred when verify occurred in code 101

**Comment by khanzadimahdi** [comment]
fork the repository, and send a pull request.
