### ISSUE TITLE
درگاه لوکال

### ISSUE THREAD

**Issue by hooman-mirghasemi** [shetabit/payment#199]
این درگاه لوکال توی لاراول چطوری کار میکنه؟
ای کاش یه توضیحاتی توی مستندات میدادین من امتحان کردم به همون روتی که از قبل بوده برمیگرده و در نهایت هم چون اون روت سی اس ار اف داره خطای 419 میده
تو لیست اکسکلود هم قرار دادم اون روت رو که افتاد تو حلقه بی نهایت و همین طور هی به خودش ریدایرکت میشد.

**Comment by khanzadimahdi** [comment]
سلام وقت بخیر. درگاه لوکال توی لاراول هنوز کامل قابل تست نیست. توی لاراول یکسری مشکلات داره که باید رفع بشه

**Comment by amirehsan** [comment]
سلام ،
من با لاراول و درگاه تست سند باکس برای درایور ای دی پی استفاده میکنم و هنگام ->pay()-render() فقط صفحه سفید میبینم. این موضوع هم شامل همین مشکلی هست که گفتید؟ و اگر آره کی برطرف میشه که بتونم تست کنم؟

**Comment by khanzadimahdi** [comment]
سلام وقت بخیر. درگاه لوکال بر روی فریمورک لاراول در حال حاضر قابل استفاده نیست. یکسری مشکلات داره که هنوز فرصت نشده رفع کنیم.

**Comment by hos3ein** [comment]
با این کد مشکل Local برای من حل شد.
```php
\Shetabit\Multipay\Payment::setRedirectionFormViewRenderer(function ($view, $action, $inputs, $method) {
    return Blade::render(
        Str::replace('</form>', '@csrf</form>', file_get_contents($view)),
        [
            'action' => $action,
            'inputs' => $inputs,
            'method' => $method,
        ]
    );
});
```

**Comment by khanzadimahdi** [comment]
@hos3ein لطفا تغییرات رو درون پکیج اعمال کنید و درخواست مرج بدید

**Comment by hos3ein** [comment]
> @hos3ein لطفا تغییرات رو درون پکیج اعمال کنید و درخواست مرج بدید

#263
