### ISSUE TITLE
Set MerchantID dynamically

### ISSUE THREAD

**Issue by ehsan1011** [shetabit/payment#200]
درود. وقت بخیر
جسارتا آیا همونطور که میشه نوع درگاه را در کنترلر بصورت دینامیک مشخص کرد، میتوان مرچنت کد و سایر تنظیمات درگاه که در فایل کانفیگ 
هست را هم در کنترلر تنظیم کرد؟ اگر خیر چه روشی برای این مورد پیشنهاد میدید
سپاس

**Comment by khanzadimahdi** [comment]
همیشه قبل از پرسیدن اول داکیومنت ها رو بخونید

```php
// Purchase the given invoice with custom driver configs.
Payment::config('mechandId', 'your mechand id')->purchase(
    $invoice,
    function($driver, $transactionId) {
    // We can store $transactionId in database.
	}
);
```

**Comment by ehsan1011** [comment]
بله ممنون. البته تو مستندات فارسی این موردقید نشده. مستندات انگلیسی آپدیت تر هست
