### ISSUE TITLE
ارسال شماره کارت های مجاز جهت پرداخت

### ISSUE THREAD

**Issue by awminux** [shetabit/payment#202]
سلام
طبق مستندات زیبال و زرین پال امکان ارسال شماره کارت هایی که کاربر میتونه با اونها پرداخت رو انجام بده وجود داره
ایا توی این پکیج متدی جهت ارسال این اطلاعات وجود داره؟

**Comment by khanzadimahdi** [comment]
سلام این امکان در حال حاضر وجود نداره

https://github.com/shetabit/multipay/blob/master/src/Drivers/Zarinpal/Strategies/Normal.php

میتونید به درایور مورد نظرتون اضافه کنید و درخواست مرج بدید

**Comment by khanzadimahdi** [comment]
به علت عدم فعالیت من این ایشو رو میبندم

**Comment by ehsan-ej** [comment]
سلام میشه یه توضیحات درباره اضافه کردن پارمتر هایی مانند شماره تلفن و شماره کارت در هنگام ارسال درخواست پرداخت بدید ممنون

**Comment by khanzadimahdi** [comment]
اگه درگاه پارامتر ها رو قبول کنه میتونید با متد detail اون مقادیر رو به درگاه پاس بدید. لطفا قبلش کد درگاه مورد نظرتون رو چک کنید

https://github.com/shetabit/multipay/tree/master/src/Drivers
