### ISSUE TITLE
Trying to access array offset on value of type null on another file

### ISSUE THREAD

**Issue by MehdiAghighi** [shetabit/payment#203]
سلام وقتتون بخیر

توی وبسایت 
tsapp.ir
چند وقتی بود از درگاه استفاده می‌کردیم و مشکلی نداشتیم. یهو بعد از چند روز متوجه شدیم که دیگه درگاه پرداخت کار نمی‌کنه ، بدون این که هیچ تغیری هیچ کاری بکنیم. چک کردم ارور زیر رو میده.

```
exception: "ErrorException"
file: "/home1/tsappir/vendor/shetabit/multipay/src/Drivers/Zarinpal/Strategies/Normal.php"
line: 104
message: "Trying to access array offset on value of type null"
```

گویا همین ارور برای یه فایل دیگه دوستان گرفته بودن که مشکل از کانفیگ و کش و ... شون بود. ولی من چند باری کش کانفیگ رو پاک کردم کار نکرد دستوری‌های زیر رو امتحان کردم.
```
php artisan config:clear
php artisan clear
php artisan route:clear
```
و هیچکدوم کمکی نکرد.

چک کردم فایل مورد نظر رو دیدم خط ۱۰۴ اون فایل چک می‌کنه اگر توی ریکوئست اروری باشه اونجا اکسپشن میده ! یعنی به نظر میاد که ارور از سمت زرین‌پال میاد که احتمالش خیلی کمه واقعا گیج شدم ممنون میشم کمک کنید.

**Comment by qmeyti** [comment]
سلام. منم به همین خطا خوردم

**Comment by amirhossein-shakeri-work** [comment]
درود بنده هم به این خطا خوردم و حدس میزنم مشکل رو هم پیدا کردم

`\vendor\shetabit\multipay\src\Drivers\Zarinpal\Strategies\Normal.php:104`

```php
// some error has happened
if (!empty($result['errors']) || empty($result['data']) || $result['data']['code'] != 100) {
    throw new PurchaseFailedException($result['errors']['message'], $result['errors']['code']);
}
```

قسمت سوم شرط رو توجه کنید ...
ممکنه مشکل از اونجا باشه

**Comment by qmeyti** [comment]
تکه کد 
`$response->getBody()->getContents()`

`        $result = json_decode($response->getBody()->getContents(), true);
`
یک همچین چیزی رو بر میگردونه:


`<?xml version="1.0" encoding="UTF-8" standalone="no" ?>
<wsdl:definitions
    xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
    xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    xmlns:s="http://www.w3.org/2001/XMLSchema"
    xmlns:tns="http://zarinpal.com/"
    targetNamespace="http://zarinpal.com/"
    name="PaymentGatewayImplementationService">
    <wsdl:types>
        <s:schema elementFormDefault="qualified" targetNamespace="http://zarinpal.com/">
            <s:element name="PaymentRequest">
                <s:complexType>
                    <s:sequence>
                        <s:element minOccurs="1" maxOccurs="1" name="MerchantID" type="s:string"/>
                        <s:element minOccurs="1" maxOccurs="1" name="Amount" type="s:int"/>
                        <s:element minOccurs="1" maxOccurs="1" name="Description" type="s:string"/>
                        <s:element minOccurs="0" maxOccurs="1" name="Email" type="s:string" nillable="true"/>
                        <s:element minOccurs="0" maxOccurs="1" name="Mobile" type="s:string" nillable="true"/>
                        <s:element minOccurs="1" maxOccurs="1" name="CallbackURL" type="s:string"/>
                    </s:sequence>
                </s:complexType>
            </s:element>
            <s:element name="PaymentRequestResponse">
                <s:complexType>
                    <s:sequence>
                        <s:element minOccurs="1" maxOccurs="1" name="Status" type="s:int"/>
                        <s:element minOccurs="1" maxOccurs="1" name="Authority" type="s:string"/>
                    </s:sequence>
                </s:complexType>
            </s:element>
            <s:element name="PaymentRequestWithExtra">
                <s:complexType>
                    <s:sequence>
                        <s:element minOccurs="1" maxOccurs="1" name="MerchantID" type="s:string"/>
                        <s:element minOccurs="1" maxOccurs="1" name="Amount" type="s:int"/>
                        <s:element minOccurs="1" maxOccurs="1" name="Description" type="s:string"/>
                        <s:element minOccurs="1" maxOccurs="1" name="AdditionalData" type="s:string"/>
                        <s:element minOccurs="0" maxOccurs="1" name="Email" type="s:string" nillable="true"/>
                        <s:element minOccurs="0" maxOccurs="1" name="Mobile" type="s:string" nillable="true"/>
                        <s:element minOccurs="1" maxOccurs="1" name="CallbackURL" type="s:string"/>
                    </s:sequence>
                </s:complexType>
            </s:element>`


یعنی قبلا هم همین رو برمیگردوند؟!

**Comment by khanzadimahdi** [comment]
اگه حس میکنید مشکلی هست پکیج رو فورک کنید مشکل رو رفع کنید و مرج بزارید

تعداد درگاه ها زیاده و ممکنه هرکدوم بنا به تغییراتی که سرویس دهنده میده به مرور زمان به مشکل بخورن و باید به مرور زمان فیکس بشن و من نمیرسم که هر روز همه رو چک کنم! زرین پال هم که هر چند ماه یه بار همه چیزو تغییر میده و اصلا بهش اعتماد نمیشه کرد و حتی اعلام هم نمیکنه که بقیه بتونن خودشون رو بروزرسانی کنن
