### ISSUE TITLE
دریافت اطلاعات از کالبک فانکشن

### ISSUE THREAD

**Issue by mohammad79-ch** [shetabit/payment#206]
سلام وقتتون بخیر ، ممنون از پکیج خوبتون ، مشکلی که هس اینه که ما برا پرداخت قیمت و حالا اون ترانزیشن آیدی رو میدیم بهش ، ولی تو 
   کالبکش  فقط یه آرایه میفرسته که شامل دو مقدار هس یکی وضعیت پرداخت و دیگری آتوریتی هس  ، ولی ما مقدار های دیگه ای هم نیاز داریم که از کالبک به سمت ما ارسال بشن 

و اینکه ما همه مراحلی که در داکیومنت گفته بودید رو امتحان کردیم  ، ولی اون مقدارهای قیمت و ترانزیشن آیدی که میخواهیم رو از طریق کالبک دریافت نمیکنیم .

، ممنون میشم پاسخگو باشید با تشکر

**Comment by khanzadimahdi** [comment]
سلام. کدوم کالبک؟ کدخودتون رو قرار بدید

ورژنی که استفاده میکنید هم ذکر کنید! واسه ایشو زدن یه قالب خاص داریم که رعایت نکردین

**Comment by mohammad79-ch** [comment]
به کد فعلا دسترسی ندارم ، ولی از ورژن 7 استفاده میکنیم ، و اینکه دقیقا همین کد رو به  پروژه اضافه کردیم

`return Payment::purchase(
    (new Invoice)->amount(1000), 
    function($driver, $transactionId) {
    	// Store transactionId in database.
        // We need the transactionId to verify payment in the future.
	}
)->pay()->render();`

و حالا یه متد دیگ هم هس که زمانی که کاربر از درگاه برمیگرده، اجرا میشه ، و هیچ اطلاعات مناسبی رو برنمیگردونه 

`array:2 [▼
  "Authority" => "A00000000000000000000000000285423304"
  "Status" => "OK"
]`

 ولی طبیعتا ما به ترانزیشن اکشن آیدی و قیمت نیاز داریم که بتونیم اونا رو از جدول  پرداختی که ثبت کردیم فراخونی کنیم و حالا وضعیت رو به پرداخت شده تغییر بدیم

**Comment by khanzadimahdi** [comment]
شما نباید با ترانزکشن ایدی دیتا رو از دیتابیس در بیاری. شما باید قبلا دیتا رو توی دیتابیس گذاشته باشی و بعدا ازش استفاده کنی

**Comment by mohammad79-ch** [comment]
خب آره قبل از رفتن به درگاه دیتاها توی دیتابیس که ذخیره میشن ، ولی به اون دیتا ها در متد کالبک دسترسی نداریم ، چون من با حالا دو یا سه درگاه دیگه هم کار میکردم معمولا خودش اطلاعات مورد نیاز رو برمیگردوند ، ولی خب الان شما میگید اطلاعات مورد نیازمون رو همون اول به اون آدرس کالبکی اضافه کنیم و بگیریم درسته ؟

**Comment by khanzadimahdi** [comment]
ادرس کالبک رو یه چیزی شبیه زیر بسازید

```
payments/100/verify
```

بعدش موقع برگشت از درگاه اون 100 رو میتونید بگیرید و رکورد مورد نظرتون رو پیدا کنید و وریفای کنید

دقت کنید که بهتره به جای اون 100 یه چیز رندم خودتون بسازید بزارید و از مدل بایندینگ میتونید استفاده کنید واسه بدست اوردن دیتا

**Comment by mohammad79-ch** [comment]
من ترانزیشن آیدی رو بصورت کوئری استرینگ به کالبک دادم و حالا که بعد از پرداخت برگشته به درستی اطلاعات رو میاره ، ولی باز یه مشکلی که هس 

`Payment::amount(1000)->transactionId(request()->trans_number)->verify()`

اینجا به ما خطا نشون میده دلیلش رو واقعا متوجه نمیشم 

`The input params invalid, validation error.`

**Comment by khanzadimahdi** [comment]
این روش اشتباه هست چون شما به ازای هر درگاه پارامتر های متفاوتی توی رکوئست دریافت میکنید و اینجوری باید بیستا شرط بزارید چک کنه کدوم پارامتر رو استفاده کنید

راه درستش رو گفتم بهتون. شما کلا یه راه اشتباه داری میری

**Comment by mohammad79-ch** [comment]
تو داکیومنت اشاره نشده که کالبک باید متد پست داشته باشه ، ولی خب الان باز هم متد پست رو قرار دادم چنین خطایی میده 

`Route::post('/form-wizard/{unique}/callback', [FormWizardController::class,'callback'])->name('formwizard.callback');`
`The GET method is not supported for this route. Supported methods: POST.`

با اینکه متد پست هس و مشکلی نداره ، و از روش شما رفتم جلو
