### ISSUE TITLE
The POST method is not supported for this route. Supported methods: GET, HEAD in callback  sadad Melli

### ISSUE THREAD

**Issue by boobProgrammer** [shetabit/payment#208]
سلام

توی درگاه سداد ملی وقتی به سایت برمیگرده خطای زیر را میده
The POST method is not supported for this route. Supported methods: GET, HEAD.

در صورتی که درگاه های زرین پال و پی پینگ هم گذاشتم مشکلی ندارن و به درستی پرداخت انجام میشه
توی ملی فقط این مشکل هست
چطور میشه برطرفش کرد ؟

**Comment by khanzadimahdi** [comment]
<div dir=rtl>

دوست عزیز روتر خودتون رو تغییر بدید که متد post رو هم قبول کنه

هر سوالی پیش میاد درجا issue نزنید. یکم تلاش کنید اول خودتون بگردید اگه پیدا نشد بپرسید

</div>

**Comment by ferasat** [comment]
@khanzadimahdi 
متد post هم گذاشته ایم ولی کار نداد .
میگه page expire .

**Comment by khanzadimahdi** [comment]
@ferasat 

مشکل شما به خاطر csrf هست. توی کانفیگ خود لاراول حلش کنید
