### ISSUE TITLE
سویچ کردن بین واحد پولی ریال و تومان

### ISSUE THREAD

**Issue by ferasat** [shetabit/payment#210]
سلام
چطور می تونم توی این پکیج بین ریال و تومان سویچ کنم ؟
پیش فرضش چرا تومان هست .؟
اگر بخوام تغییر بدم باید چیکار کنم

**Comment by ferasat** [comment]
ممنون از راهنماییتون .

**Comment by hasanmonfared** [comment]
سلام 
ممنون میشم این موضوع رو جایی از مستندات بیان کنید.
من دو روزه دارم دیباگ میکنم :)
