### ISSUE TITLE
I wish you would use semver

### ISSUE THREAD

**Issue by mokhosh** [shetabit/payment#212]
## Detailed description

The package has had breaking changes without bumping up the major version number, and that has caused one of my websites to totally break with a simple composer update for a couple of days.

The changes that I had to fix was updating all of my imports, and the way the `pay` method on the drivers performs the redirect.

## Possible implementation

If you could bump the major version instead of minor ones when you make a breaking change to the API things like this won't happen hopefully.

**Comment by khanzadimahdi** [comment]
thanks for your notice.
after each update, you should publish new configs. we use semver for code changes, not configs.

I second that. we will keep semver for configs in the next releases.
