### ISSUE TITLE
the Gateway Url

### ISSUE THREAD

**Issue by miladbrave** [shetabit/payment#213]
Hi
I need to add  extra data in end of my gateway link(which to select my gateway instead of random select)
how can u help me?

**Comment by khanzadimahdi** [comment]
gateway link? I didn't understand your meaning.

**Comment by miladbrave** [comment]
the link that send data to bank!(I mailed u)

**Comment by khanzadimahdi** [comment]
the bank is not responsible to hold your data!!! hold them on your behalf.
if Zarinpal provides this, it doesn't mean other providers offer that.
