### ISSUE TITLE
مشکل در ارتباط با درگاه بانک ملت

### ISSUE THREAD

**Issue by MortezaHallaji** [shetabit/payment#216]
سلام من موقع اتصال با درگاه با این ارور مواجه میشم

`Unmarshalling Error: For input string: ""`

اطلاعات رو به درستی ست کردم و ارور هم ازین قسمت میباشد
```
vendor/shetabit/multipay/src/Drivers/Behpardakht/Behpardakht.php:71

 $response = $soap->bpPayRequest($this->preparePurchaseData());

```

**Comment by MortezaHallaji** [comment]
مشکل از فایل کانفیگ بود که انگار نمیشد اطلاعات رو از فایل env به صورت درست بخونه و باید مستقیم پاس میدادم

**Comment by khanzadimahdi** [comment]
کش کانفیگ رو پاک کنید و وندور رو پابلیش کنید مشکل باید حل بشه
