### ISSUE TITLE
soap-error

### ISSUE THREAD

**Issue by farshidah** [shetabit/payment#218]
سلام مهندس جان. من از shetabit/payment v4.0.1

و shetabit/multipay v1.1.2
استفاده میکنم. هم توی هاست هم توی لوکال هاست این ارورو دارم.

یه وبسایت دیگه دارم دقیقا با همین ورژن روی همون هاست و لوکال هاست. گکیج کاملا درست کار میکنه. ممنون میشم راهنماییم کنی

```
SoapFault
SOAP-ERROR: Parsing WSDL: Couldn't load from 'https://www.zarinpal.com/pg/rest/WebGate/PaymentRequest.json' : failed to load external entity "https://www.zarinpal.com/pg/rest/WebGate/PaymentRequest.json"
```

**Comment by khanzadimahdi** [comment]
سلام وقت بخیر. لطفا کد رو بررسی کنید اگه مشکلی داره فیکس کنید

https://github.com/shetabit/multipay/tree/master/src/Drivers/Zarinpal/Strategies

سه مدل استراتژی داریم توی زرین پال
همچنین ورژن پکیج خودتون رو به اخرین ورژن اپدیت کنید. زرین پال درایورش اپدیت شده که حدس میزنم شما تغییرات رو ندارین

**Comment by saeednikookalam** [comment]
I found your problem.
Update all of API URLs in your payment config file

Good luck

**Comment by khanzadimahdi** [comment]
اگه پکیج رو اپدیت کردین کانفیگ رو پاک کنید و دوباره پابلیش کنید. کانفیگ ها ممکنه تغییر کرده باشن

**Comment by farshidah** [comment]
سلام خیلی ممنونم از راهنمایتون. من الان سعی کردن با دستور 
composer update shetabit/payment

پکیج رو اپدیت کنم. این ارور رو دریافت کردم.
![image](https://user-images.githubusercontent.com/13726910/144103319-7069b20c-bae2-4939-b19b-93fff42d1205.png)

**Comment by farshidah** [comment]
مهندس جان مثل اینکه برای اپدیتش اول باید مولتی پی رو آپدیت میکردم. بعد پیمنت رو.
حالا من 
shetabit/payment -> v4.2.0

shetabit/multipay -> v1.10.0

آپدیت کردم. الان موقعانتقال به درگاه زرین پال این ارور رو دریافت میکنم:
![image](https://user-images.githubusercontent.com/13726910/144106570-265c02fc-4d02-4d8a-b2a4-e6c8d72ee4e8.png)
![image](https://user-images.githubusercontent.com/13726910/144106617-eab7bfda-1bab-4881-a6e5-0234bbdb3d6d.png)

**Comment by saeednikookalam** [comment]
You should replace the new config with current config in payment.php

The now version, change API rest routes from zarinpal.

You can copy config from package vendor path

**Comment by khanzadimahdi** [comment]
کانفیگ رو پاک کنید دوباره وندور رو پابلیش کنید

**Comment by farshidah** [comment]
سلام این کارو انجام دادم و مرچنت و.... رو توی کانفیگ جدید گذاشتم. این ارور بعد از انجام این کارا هست.

**Comment by farshidah** [comment]
![image](https://user-images.githubusercontent.com/13726910/144124008-c8d70f4e-6487-4f9e-a2de-8e4d7c09013f.png)
این کانفیگ داخل پوشه وندور هست که کپیش کردم تو پوشه کانفیگ اصلی، و مرچنت و... رو بهش اضافه کردم

**Comment by farshidah** [comment]
سلام مهندس جان. ممنون میشم راهنماییم کنین

**Comment by khanzadimahdi** [comment]
خطایی که برای شما میاد از سمت زرین پال هست. درگاه شما فعال هست؟ تنظیمات درگاه رو توی فایل کانفیگ انجام دادین؟

**Comment by farshidah** [comment]
سلام بله کد مرچنت و... رو اضافه کردم

**Comment by farshidah** [comment]
❤🌹خییلی ممنونمهندس جان. متاسفانه زیرن پال اینماد رو الزامی کرده .و درگاه پرداخت منو بسته. . و پکیج ایرادی نداره. ممنونم ازتون
