### ISSUE TITLE
Using $this when not in object context

### ISSUE THREAD

**Issue by mohammad79-ch** [shetabit/payment#219]
سلام خسته نباشید زمانی که میخوام از درگاه شما استفاده کنم به ارور زیر مواجه میشم 

Using $this when not in object context

```php
App\vendor\shetabit\multipay\src\Payment.php:206

return Pay::purchase(
    (new Invoice)->amount(1000),  <- اینجا از کار میفته
        function ($driver, $transactionId)  {
            // something
        }
)->pay()->render();
```

 مقدارهای مورد نیاز درست رو وارد کردم و انگار از خود هسته کدها خطا میده و کار نمیکنه

**Comment by khanzadimahdi** [comment]
سلام. کد کامل خودتون رو قرار بدید اینجا هیچی مشخص نیست

**Comment by mohammad79-ch** [comment]
این همه کدی هس که برای اتصال به درگاه پرداخت نوشته شده ، فقط یه سری کد در فانکشن نوشته شد که مربوط به ذخیره سازی ترانزیشن آیدی هس ، وگرنه همه کد همینه که فرستادم

**Comment by khanzadimahdi** [comment]
همه کد قطعا همین نیست. مثلا فضای نامی که استفاده میکنید چیه؟
کد رو کامل بزارید. من الان نمیدونم Pay اصلا از کجا اومده. همچین چیزی نداریم توی پکیج

**Comment by mohammad79-ch** [comment]
`use Shetabit\Multipay\Payment as pay;`  

چون خودم هم مدل مشابه دارم برای همین از فضای نام استفاده کردم

**Comment by khanzadimahdi** [comment]
شما دارید به اشتباه از فضای نام نامناسب استفاده میکنید. داکیومنت های پکیج رو یکبار دیگه مطالعه کنید

**Comment by mohammad79-ch** [comment]
آها درسته باید از فساد فراخونی بشه ، حل شد 
فقط اینکه یه مشکلی که هس 

`Shetabit\Multipay\Receipt {#1556 ▼
  #referenceId: "70022011102"
  #driver: "payping"
  #date: Carbon\Carbon @1638946504 {#1557 ▶}
  #details: []
}`

این تمام دیتاهایی هس که در زمان برگشت از درگاه بهم داده میشه ولی ترانزیشن آیدی رو برنمیگردونه با اینکه برای وریفای کردن به ترانزیشن آیدی نیاز هس

`$receipt = Payment::amount(1000)->transactionId($transaction_id)->verify();`

**Comment by khanzadimahdi** [comment]
ترانزکشن ایدی رو باید خودتون ذخیره کنید توی دیتابیس و موقع برگشت ازش استفاده کنید

**Comment by mohammad79-ch** [comment]
بصورت کوئری استرینگ باید به کالبک پاس داده بشه ؟ این روش امنی هس؟
