### ISSUE TITLE
با درگاه ملت مشکل داره

### ISSUE THREAD

**Issue by ferasat** [shetabit/payment#220]
سلام
هنگام استفاده از درگاه بانک ملت ، به درگاه میره ولی اگر پرداخت بشه و یا انصراف زده بشه و ... اررور زیر را میدهد : 
Symfony\Component\HttpKernel\Exception\MethodNotAllowedHttpException
The POST method is not supported for this route. Supported methods: GET, HEAD.
اگر هم پول پرداخت بشه پول را بر میگردونه .
متد بازگشتی را هم post کردم ولی بازم ارور 
419
PAGE EXPIRED

را داد و  پول را برگردوند

**Comment by khanzadimahdi** [comment]
مشکل از csrf token هست. توی کانفیگ خود لاراول حلش کنید

**Comment by ferasat** [comment]
ممنون میشم بیشتر توضیح بدی . اخه از  سمت بانک داره میاد من درون صفحه او تگ :
<meta name="csrf-token" content="{{ csrf_token() }}">
 را دارم .
 چه کار ی باید در کانفیگ بکنم ؟

**Comment by khanzadimahdi** [comment]
توی لاراول یه middleware csrf داریم. روی اون روت غیر فعالش کنید. 

تاپیک مربوط به پکیج نیست لطفا سرچ بزنید
