### ISSUE TITLE
ارسال شماره شبا برای درگاه تسهیم سداد

### ISSUE THREAD

**Issue by luckyboy1001** [shetabit/payment#221]
چجوری باید بفرستم؟ 
شماره شبا رو

**Comment by khanzadimahdi** [comment]
درگاه تسهیم سداد پیاده سازی نشده. اگه امکانش رو دارید خودتون این قابلیت رو به درگاه اضافه کنید و درخواست مرج بزارید

**Comment by luckyboy1001** [comment]
سلام برای خودم پیاده کردم سابمیت میکنم

**Comment by khanzadimahdi** [comment]
مرسی

**Comment by khanzadimahdi** [comment]
این ایشو رو به دلیل عدم فعالیت بستم. هر موقع اماده بودید مرج بزارید تا بررسی بشه

**Comment by bahramsadin** [comment]
https://github.com/shetabit/multipay/pull/195#issue-1754740812
