### ISSUE TITLE
قیمت در درگاه زرین پال 

### ISSUE THREAD

**Issue by hadis6673** [shetabit/payment#222]
سلام و عرض ادب من از درگاه زرین پال استفاده میکنم موقع کال بک برای قیمت ارور میده که به صورت init نیست در صورتی که درسته لطفا راهنمایی کنید ممنونم 

 $payment = \App\Models\Payment::where('resnumber', $request->Authority)->firstOrFail();
        $price =$payment->price;
        try {

            if(Payment::amount($price)->transactionId($request->Authority)->verify()) {

                if (request('Status') == 'OK') {

                    $payment->update([
                        'status' => 1
                    ]);
                    $carts = Cart::where('user_id', $payment->order['user']->id)->get();
                    foreach ($carts as $cart) {

                        $cart->delete();
                    }
                    $payment->update([
                        'status' => 1
                    ]);
                    $payment->order()->update([
                        'status' => 'paid'
                    ]);
               
                    return response([
                        'data' => 'پرداخت با موفقیت انجام شد',
                        'status' => 'error'
                    ], 200);

                }
            }
        } catch (InvalidPaymentException $exception) {
            echo $exception->getMessage();
        }

**Comment by khanzadimahdi** [comment]
مقدار قطعا عدد صحیح نیست. اون رو کست کنید به عدد صحیح

**Comment by hadis6673** [comment]
ok mamnon
