### ISSUE TITLE
مشکل ریدایرکت نشدن به درگاه پرداخت در لایوایر

### ISSUE THREAD

**Issue by mohammad79-ch** [shetabit/payment#224]
سلام وقتتون بخیر ، زمانی که پکیج رو تو لایوایر تست میکنم همه چیز اوکی هس و ثبت میشه ولی به درگاه پرداخت منتقل نمیشه 

```
 return Pay::callbackUrl(route("order.verify",["token"=>$token]))->purchase(

            (new Invoice)->amount(1000),

            function ($driver, $transactionId) use ($totalPrice, $order,$token) {

                $this->createPayment($order, $totalPrice, $transactionId, $token);

            }

        )->pay()->render();
```

**Comment by khanzadimahdi** [comment]
وندور رو پابلیش کنید و خودتون اونو به کامپوننت لایو وایر تغییر بدید

**Comment by jpro123** [comment]
> وندور رو پابلیش کنید و خودتون اونو به کامپوننت لایو وایر تغییر بدید

منظورتون فایل redirectForm.blade.php  هست ؟ اگر اینو کامپوننت لایووایر کنیم مشکل حل میشه؟

**Comment by 6000850** [comment]
> من اینجوری حلش کردم شاید به درد شما هم بخوره:
> 
> ```
> $shetabiJSON = $shetabiPayment->pay()->toJson(); 
> $shetabiResponse = json_decode($shetabiJSON, true);
> return redirect($shetabiResponse['action']);
> ```
> 
> البته Error Handling هم باید بکنم که هنوز نکردم

سلام وقت بخیر
وقتی با این حالت ریدایرکت میکنم  از بانک خطا میاد که refID ارسال نشده
