### ISSUE TITLE
گزارش تغییرات درگاه نکست پی

### ISSUE THREAD

**Issue by sama20** [shetabit/payment#225]
درگاه نکست پی درست کار نمیکند. باید تغییرات زیر در آن داده شود.
 
مقادیر فایل کانفیگ payment.php باید به مقادیر زیر اصلاح شود.

```
            'apiPurchaseUrl' => 'https://nextpay.org/nx/gateway/token',
            'apiPaymentUrl' => 'https://nextpay.org/nx/gateway/payment/',
            'apiVerificationUrl' => 'https://nextpay.org/nx/gateway/verify',
```

همچنین در فایل `Nextpay.php` خط 138 غلط املایی وجود دارد. لطفا اصلاح شود.
`'خطای ناشناخته ای رخت داده است'` => `رخ`

**Comment by khanzadimahdi** [comment]
سلام. لطفا تغییرات رو اعمال کنید اگه درست کار کرد درخواست مرج بزارید

**Comment by sama20** [comment]
بله من دارم با همین روش کار میکنم و آدرسها به شکل گفته شده تغییر کردند.

یک مقداری سرم شلوغ بود و اگر شما خودتون زحمت این تغییر رو بکشید رو بهتر هست

با تشکر

**Comment by sama20** [comment]
مستند سایت نکست پی که آدرسها در اون بشکلی هست که گفتم.

https://nextpay.org/nx/docs

**Comment by khanzadimahdi** [comment]
لطفا پکیج رو فورک کنید و درخواست مرج بزارید. ممنونم

**Comment by sama20** [comment]
یک درخواست مرج گذاشتم ببین درست ارسال کردم ؟

**Comment by khanzadimahdi** [comment]
سلام دوست عزیز. درخواست شما reveiw و merge خواهد شد. ممنونم ازتون.
