### ISSUE TITLE
Soap Error Parsing WSDL in Melat

### ISSUE THREAD

**Issue by Saeeed-B** [shetabit/payment#228]
@khanzadimahdi @atipaydev 
i get this error in `Behpardakht Drivre`.
note : all be find in local but get this error in server centos.

`
SOAP-ERROR: Parsing WSDL: Couldn't load from
`

**Comment by Saeeed-B** [comment]
![image](https://user-images.githubusercontent.com/36485982/149619506-3fcb44dc-9708-4381-ba91-9bca7d978501.png)

**Comment by khanzadimahdi** [comment]
رسپانس بهپرداخت رو بررسی کنید

**Comment by khanzadimahdi** [comment]
دوست عزیز درایور درگاه بهپرداخت در ادرس زیر موجود هست

https://github.com/shetabit/multipay/tree/master/src/Drivers/Behpardakht

لطفا بررسی کنید و اگه درگاه بهپرداخت تغییراتی داشته , لطفا درایور رو اصلاح کنید و درخواست مرج بزارید. ممنونم از شما

**Comment by khanzadimahdi** [comment]
I close this issue due to inactivity.
