### ISSUE TITLE
ادامه #229

### ISSUE THREAD

**Issue by sajaddp** [shetabit/payment#230]
#229 

@khanzadimahdi 

همان طور که خدمتتون نوشتم قبل از ارسال به درگاه بانکی در تابع `callback` مقدار `invoice` تغییر می کند.

الان که کدهای پکیج را بررسی کردم به نظر می رسد دلیل این موضوع این هست که در تابع `purchase` میاید و یک `invoice` جدید و اصطلاحا `fresh` می سازید که در نتیجه باعث می شود مقدار `transactionId` که تنظیم شده از بین برود بعد این مقدار را به بانک ارسال می کنید.

```
///shetabit/multipay/src/Payment.php
    /**
     * Purchase the invoice
     *
     * @param Invoice $invoice|null
     * @param $finalizeCallback|null
     *
     * @return $this
     *
     * @throws \Exception
     */
    public function purchase(Invoice $invoice = null, $finalizeCallback = null)
    {
        if ($invoice) { // create new invoice
            $this->invoice($invoice);
        }

        $this->driverInstance = $this->getFreshDriverInstance();

        //purchase the invoice
        $transactionId = $this->driverInstance->purchase();
        if ($finalizeCallback) {
            call_user_func_array($finalizeCallback, [$this->driverInstance, $transactionId]);
        }

        // dispatch event
        $this->dispatchEvent(
            'purchase',
            $this->driverInstance,
            $this->driverInstance->getInvoice()
        );

        return $this;
    }
```

پیشنهاد می کنم روی نحوه رفتارتان بازنگری کنید.

**Comment by khanzadimahdi** [comment]
بله درسته. به این دلیل هست که بانک کد تراکنش رو از ما دریافت نمیکنه!!! بانک کد رو جنریت میکنه و ما باید از چیزی که بانک داده استفاده کنیم. به همین دلیل دیتایی که پاس داده میشه با دیتای بانک سینک میش

**Comment by khanzadimahdi** [comment]
اگه مشکل یا باگی وجود داره لطفا پکیج رو فورک کنید و باگ یا مشکل رو رفع کنید و درخواست مرج بزارید.

موفق و پیروز باشید
