### ISSUE TITLE
how to find transactionid in Verify payment

### ISSUE THREAD

**Issue by AzadGh95** [shetabit/payment#231]
سلام
قبل از ارسال به بانک مقدار ‍‍`transactionId‍‍` را برای من تنظیم میکند و در دیتابیس ذخیره میکنیم 

و `url` هم که برای من برمیگرداند به این صورت هست :
`http://localhost/payment/payping/verify?refid=1&clientrefid=05228631-cf02-4e40-8240-bb4a1642475e`

در این قسمت [Verify payment](https://github.com/shetabit/payment#verify-payment)چطور باید مقدار `$transactionId`  را بدست بیاورم ؟
چون در `url` مقدار `transactionid` که پکیج تنظیم کرده برنمیگردد و با این متغییر نمیتوان تراکنش انجام شده را شناسایی کرد
ولی درمثال شما این مقدار ضروری هست 
لطفا راهنمایی کنید.

**Comment by khanzadimahdi** [comment]
سلام وقت شما بخیر. ابتدا داکیومنت و مثال هایی که داره رو مرور کنید.

توی ادرس برگشت یا همون وریفای بهتره از مدل بایندینگ استفاده کنید

بدین صورت ابتدا یک صورتحساب درون دیتابیس بسازید و بعد از purchase ترنزکشن ایدی اون صورتحساب رو اپدیت کنید و ادرس وریفایل رو با ایدی صورتحساب بایند کنید

```
/payments/1/verify
```

یه چیزی شبیه بالا میشه ادرس برگشت. حالا موقع برگشت شماره تراکنش رو لود کنید و وریفای کنید

**Comment by MahdiNb** [comment]
سلام
وقت بخیر

توی درگاه آسان پرداخت قبل از انتقال به درگاه transactionId رو به درستی دریافت و در دیتابیس ذخیره میکنم و در برگشت از درگاه صورتحساب رو با استفاده از بایند کردن به دست میارم اما transactionId ای که ذخیره شده امکان verify کردن نداره و خطای bad request دریافت میکنم.
