### ISSUE TITLE
ایراد در شماره تراکنش درگاه سپرده

### ISSUE THREAD

**Issue by MobinS** [shetabit/payment#233]
سلام شماره تراکنشی که موقع پرداخت ذخیره میکنی با شماره ای که برمیگردونه(تا وریفای کنی) فرق داره ایراد از چیه؟

**Comment by khanzadimahdi** [comment]
سلام. این درگاه رو یکی از توسعه دهنده های ازاد نوشته. کدشو میتونید توی ادرس زیر بررسی کنید

https://github.com/shetabit/multipay/blob/master/src/Drivers/Sepordeh/Sepordeh.php

اگه مشکلی پیدا کردین فیکس کنید و درخواست مرج بزارید
