### ISSUE TITLE
405 در برگشت از درگاه سپهر

### ISSUE THREAD

**Issue by MahdiRad313** [shetabit/payment#234]
سلام
من توی پروژم از پکیج shtabit/payment استفاده کردم و به درگاه زرین پال و سپهر بانک صادرات وصلش کردم.
همه چی خوبه تا زمانی که پرداخت انجام میشه و میخواد به من رسپانس بده، ولی توی صفحه ی نتیجه پرداختم وقتی که از درگاه سپهر استفاده میکنم بهم خطای 405 میده در صورتیکه با همون کد و روی درگاه زرین پال نتیجه ی پرداخت رو به درستی نشون میده
مشکلش چیه بنظرتون؟
و اینکه توی برگشت Authority و Status نیست توی url
@khanzadimahdi

**Comment by khanzadimahdi** [comment]
سلام وقت بخیر. کد درگاه سپهر رو میتونید توی مسیر زیر ببینید

https://github.com/shetabit/multipay/blob/master/src/Drivers/Sepehr/Sepehr.php

لطفا اگه باگ یا مشکلی هست بررسی کنید و درخواست مرج بزارید

راجب خطای 405 باید بگم به خاطر روتر شما هست. این خطا به معنی method not allowed هست. روتینگ رو روی any قرار بدید تا درخواست ها رو به هر دو صورت get و post بتونه مدیریت کنه
