### ISSUE TITLE
how add multi params in verify callback methd

### ISSUE THREAD

**Issue by hameddalvand67** [shetabit/payment#235]
how add multi params in verify callback methd

**Comment by khanzadimahdi** [comment]
multi-params for what? I didn't understand your meaning.

**Comment by hameddalvand67** [comment]
سلام مهندس  من از اپ وب ویو برای اندروید استفاده می کنم و توی وب ویو برای
پرداخت از توی اپ خارج میشه و کروم رو باز میکنه و دیگه به ششن دسترسی نداریم
برای اینکه توی کالبک بتونم اون ترنساکشن رو تکمیل کنم نیاز دارم که
ترنساکشن ای دی رو توی پارامتر url ارسال و دریافت کنم تا بتونم تکمیل کنم
تشکر بابت راهنمایی

**Comment by khanzadimahdi** [comment]
I close this issue due to inactivity.
