### ISSUE TITLE
order id در درگاه زیبال

### ISSUE THREAD

**Issue by Ehgod** [shetabit/payment#236]
سلام ضمن تشکر بابت پکیج کاملتون من چند تا مشکل برخورد کردم
اولی uuid در درگاه زیبال با order id همخوانی نداره ! یعنی هرچی ست میکنیم در برگشت order id رندوم از طرف زیبال میاد !

دوم اینکه ایا امکانش هست اطلاعاتای مانند شماره تلفن ایمیل و .... که خود درگاه زیبال از ما قبول میکند هم ارسال کنیم و همچنین اطلاعاتی که زیبال نوشته در بازگشت verify برای ما برمیگرداند مانند تاریخ پرداخت و ... رو هم داشته باشیم
با تشکر

**Comment by khanzadimahdi** [comment]
وقت بخیر. لطفا ابتدا داکیومنت پکیج رو مطالعه کنید. 
درایور زیبال به صورت زیر هست

https://github.com/shetabit/multipay/blob/master/src/Drivers/Zibal/Zibal.php

لطفا بررسی کنید. اوردر ایدی و uuid  و نجوه عملکردشون درون کد مشخص هست.
اگه فیچر بیشتری نیاز دارید اون رو اضافه کنید و درخواست مرج بزارید.

**Comment by ehsan-ej** [comment]
خیلی ممنون متوجه کامل شدم در ارسال درخواست
ولی نتونستم وریبال هایی که زیبال در زمان برگشت از تابع verify در مستندات خود وبسایتش میفرسته رو پیدا کنم

**Comment by ehsan-ej** [comment]
در هنگام صدا زدن order_id این مشکل میاد

Call to a member function orderId() on null 
یا 
Call to a member function order_id() on null

**Comment by khanzadimahdi** [comment]
لطفا فیکس کنید و درخواست مرج بزارید.

**Comment by khanzadimahdi** [comment]
دوست عزیز این مشکل به پکیج مرتبط نیست! پکیج هیچ متدی با نام order_id یا orderId نداره! لطفا مشکل رو درون کد خودتون حل کنید.
