### ISSUE TITLE
مشکل merchantId در درگاه زیبال

### ISSUE THREAD

**Issue by mramzani** [shetabit/payment#237]
سلام
یه مشکلی  در کار با  درگاه زیبال وجود داره که اگر فایل payment و مقدار  merchantId مربوط به درگاه زیبال رو اینطور تنظیم کنید
` 'merchantId' => 'zibal', `
و در درایور زیبال 
`dd($this->settings);`
این کد رو قرار بدید 
مقدار  merchantId رو خالی برمیگردونه
این مورد رو لطفا بررسی کنید 
سپاس

**Comment by khanzadimahdi** [comment]
با سلام. اگه مشکلی هست لطفا فیکس کنید و درخواست مرج بزارید

https://github.com/shetabit/multipay/tree/master/src/Drivers

لیست درایورها در ادرس  بالا موجود است

**Comment by khanzadimahdi** [comment]
لطفا کش کانفیگ رو یکبار پاک کنید و دوباره تست کنید. ممکنه به خاطر کش بودن کانفیگ نیز باشه.

**Comment by aliazizi77** [comment]
> سلام یه مشکلی در کار با درگاه زیبال وجود داره که اگر فایل payment و مقدار merchantId مربوط به درگاه زیبال رو اینطور تنظیم کنید `'merchantId' => 'zibal',` و در درایور زیبال `dd($this->settings);` این کد رو قرار بدید مقدار merchantId رو خالی برمیگردونه این مورد رو لطفا بررسی کنید سپاس


من هم این مشکل رو داشتم از این متد استفاده کردم مشکلم برطرف شد

https://github.com/shetabit/payment#config-set-driver-configs-on-the-fly
