### ISSUE TITLE
شمارش معکوس اشتباه درگاه پرداخت سپهر

### ISSUE THREAD

**Issue by MahdiRad313** [shetabit/payment#241]
سلام
بنده درگاه پرداخت سپهر رو با استفاده از پکیج shtabit/payment راه اندازی کردم.
خداروشکر همه چیز اوکیه ولی بعد از پرداخت و توی صفحه ی تکمیل شمارش معکوسش از 0 شروع میشه و به -1 میررسه.
یه مشکلی هست بعضی وقت ها اونم اینه که بعد از پرداخت و گرفتن استاتوس اوکی اکسپشن "تراکنش ناموفق بعد از 72 ساعت مبلغ به حساب شما بر میگردد" میده درحالی که هم تو پنل خودم و هم تو پنل درگاه، تراکنش تایید شده و توی لاگ هام هم کد استاتوسش موفقه
ممنون میشم اگه راهنمایی کنید

@khanzadimahdi

**Comment by khanzadimahdi** [comment]
سلام وقت بخیر. بابت تاخیر در پاسخ عذرخواهی میکنم.
اگه مشکلی پیدا کردین لطفا اونو  فیکس کنید و درخواست مرج بزارید.
بابت پرداخت از کدوم درگاه استفاده میکنید؟ کلی درگاه داریم!

**Comment by MahdiRad313** [comment]
درگاه پرداخت سپهر (بانک صادرات)

**Comment by khanzadimahdi** [comment]
I close this issue due to inactivity.
