### ISSUE TITLE
مشکل verify کردن تراکنش در idpay

### ISSUE THREAD

**Issue by jpro123** [shetabit/payment#242]
سلام

آی دی پی برای وریفای کردن تراکنش  id , order_id را میخاد  . که Id در پکیج شما transactionid هست و order_id هم خودمون پاس میدیم . 

در موقع وریفای شما 
	$receipt = Payment::amount(1000)->transactionId($transaction_id)->verify();
 
مقدار AMOUNTرو ارسال میکنین که بدرد درگاه آی دی پی نمیخوره و بجای اون باید order_id جایگزین بشه یا همون peyment_d که اکثرا اسمشو این میزارن . 

حالا چگونه بجای amount مقدار order_id را به درگاه برای وریفای پاس بدیم.

**Comment by jpro123** [comment]
درگاه آی دی پی برای وریفای order_id و id رو میخاد  با amount کاری نداره این مورد رو چگونه حل میکنین ؟

**Comment by jpro123** [comment]
$receipt = Payment::amount(1000)->transactionId($transaction_id)->verify();

بجای این کد چیز دیگه باید بنویسم ؟

**Comment by khanzadimahdi** [comment]
سلام. برای اینکه جزئیات رو بدونید کد زیر رو بررسی کنید

https://github.com/shetabit/multipay/blob/master/src/Drivers/Idpay/Idpay.php

**Comment by jpro123** [comment]
اگه زحمت نمونه کدشو بکشین ممنون میشم

**Comment by jpro123** [comment]
من بلد نیستم تازه کارم اگه لطف کنین برام بزارین ممنون میشم
