### ISSUE TITLE
خروج از سایت پس از بازگشت از درگاه سداد به سایت

### ISSUE THREAD

**Issue by boobProgrammer** [shetabit/payment#244]
سلام و عرض ادب
وقتی توی درگاه سداد ملی میشیم و پرداخت انجام میدیم یا اگر بازگشت (لغو پرداخت) میزنیم هنگام بازگشت به سایت به جای اینکه بره توی redirectBack route که تعریم کردیم از پنل کاربر خارج میشه و به صفحه login میره

این مشکل را فقط توی درگاه سداد داریم و توی payping و mellat مشکلی نداریم
توی فایل config/session.php هم مقدار same_site را روی none گذاشتیم بازم فرقی نکرد
مقدار http_only هم true گذاشتم و secure هم true
ممکنه راهنمایی کنین چیکار کنیم که موقع برگشت از سداد سشن کاربر از بین نره ؟
سپاس

**Comment by saeednikookalam** [comment]
سلام رفیق
خوب دقت کن که آدرس callback متفاوت نباشه
مثلا با آدرس htttps میری توی درگاه ولی به آدرس http داری callback میکنی
