### ISSUE TITLE
incompatible php version

### ISSUE THREAD

**Issue by shdehnavi** [shetabit/payment#25]
hi, what's wrong when installing payment ?

` [InvalidArgumentException]
  Package shetabit/payment at version  has a PHP requirement incompatible with your PHP version (7.1.29)`

**Comment by khanzadimahdi** [comment]
php version must be 7.2+

**Comment by shdehnavi** [comment]
My php version in xampp is 7.3.5, but `php -v` output in cmd is 7.0.33
i don't know what was goes wrong !
but i try installing with `--ignore-platform-reqs`  composer arguement and shetabit/payment has been installed successfully and it hasn't any issues in laravel.

Thank you so much.

**Comment by khanzadimahdi** [comment]
you have 2 configs for php. 
a php for your websites.
and a CLI php.
your cli php version is 7.3.5 but your php which used for processing websites is not.
