### ISSUE TITLE
مشکل در ارتباط درگاه   سداد

### ISSUE THREAD

**Issue by esmaily** [shetabit/payment#250]
### سلام از دیروز این مشکل برای درگاه پرداخت ما پیش اومده:
 `
ErrorException
Undefined property: stdClass::$PaymentIdentity
`
### این خطا داخل مسیر زیر خط 75 پیش هست 

`vendor\shetabit\multipay\src\Drivers\Sadad\Sadad.php:75`

  ### بعد اینکه وارد اون فایل رو باز می کنی همچین چیزی می بینی

`   array(
            'MerchantId' => $this->settings->merchantId,
            'ReturnUrl' => $this->settings->callbackUrl,
            'PaymentIdentity' => $this->settings->PaymentIdentity,
            'LocalDateTime' => $iranTime->format("m/d/Y g:i:s a"),
            'SignData' => $signData,
            'TerminalId' => $terminalId,
            'Amount' => $amount,
            'OrderId' => $orderId,
        );`

 ### که `PaymentIdentiry` داخل تنظیمات فایل `config/payment.php` نیست . بعد اینکه دستسی اینو اضافه می کنم دوباره همچین خطای برای `mode` می گیره بعد اینکه اون رو هم اضافه می کنم یعنی تنظیمات درگاه سداد اینجوری می شه با اینکه داخل مستندات و وقتی پکیج رو نصب می کنی اینا نیستن.
این تنظیمات درگاه سداد البته همشو نیاوردم
`  'merchantId' => '',
            'terminalId' => '',
            'PaymentIdentity' => '',
            'mode' => 'normal',
            'callbackUrl' => 'https:/sample.com/buy/verify'
,`

بعد اینکه این ها رو اضافه کردم این خطا رفع می شه اما خطای زیر رو می ده حتی روی سرور اصلی

`دسترسی به صفحه مورد نظر امکان پذیر نمی باشد`

* ورژن نرم افزار ها:

* Version used ( PHP 7.4,Laravel 7.30, Package Version: v4.3.0 and v3.1):
 
سوال : آیا درگاه سداد تغییراتی داشته ؟
اگر تغییراتی داشته مقدار `PaymentIdentity`و `mode` چی می شه؟

**Comment by khanzadimahdi** [comment]
سلام وقت بخیر.  شما پکیج رو اپدیت کردین؟
اگه پکیج رو اپدیت کردین و از ورژن قدیمی به ورژن جدید اومدین قطعا تغییراتی داشته. فایل کانفیگ رو کامل پاک کنید و وندور رو دوباره پابلیش کنید.

**Comment by esmaily** [comment]
من پکیج رو اپدیدت نکرده بودم. بعد اینکه یه سری تغییرات داخل سایت انجام دادیم پکیجی هم نصب نکردم .ولی باز اینطوری شد .
منم فایل کانفیگ رو حذف کردم دوباره publishکردم درست شد
