### ISSUE TITLE
Connecting to the payment gateway by the get method

### ISSUE THREAD

**Issue by bardiaabasirad** [shetabit/payment#255]
با سلام
بنده از درگاه پرداخت سامان کیش در وبسایتم استفاده میکنم و مشکلی هم نداره و به خوبی هم کار میکنه ولی یک اپلیکیشن هم برای سایت درست کردم که در مرحله پرداخت آدرسی که دریافت میکنم متد آن از نوع پست هست و امکان اینکه با مرورگر درخواست از نوع پست ارسال کنم از داخل اپلیکیشن وجود ندارد.
نمیدانم امکان اتصال به درگاه پرداخت با متد get امکان پذیر هست یا نه
با استفاده از متد toJson مقداری که برگشت می‌دهد یک پارامتر دارد که متد آن post هست، توی اپلیکیشن فقط میتوان درخواست های get را با مرورگر باز کرد

`->pay()->toJson()`

`{action: https://sep.shaparak.ir/payment.aspx, inputs: {Token: Tig6Fno2K6M........., RedirectUrl: https://mywebsite.ir/api/v1/payment/verify}, method: POST}`

با تشکر

* Version used (PHP 7.2):
"shetabit/payment": "^4.0"

**Comment by khanzadimahdi** [comment]
اینکه متد پست هست مربوط به بانک میشه و مرتبط با پکیج نیست. بانک متد پست قبول میکنه.
شما میتونید یک فرم بزارید و اون رو با کد سابمیت کنید تا به صفحه ی مورد نظر بره. میتونید یک فریم وب باز کنید.
