### ISSUE TITLE
log-out  کاربر بعد از برگشت از سایت

### ISSUE THREAD

**Issue by aragornq** [shetabit/payment#257]
با سلام . چرا هنگام برگشت از درگاه پارسیان کاربر logout می شود و باید مجدد ورود انجام دهد . 
Route::controller(Parsian::class)->group(function (){
    Route::post('pay','sendData')->name('pay'); // ذخیره اطلاعات پرداخت و اتصال
    Route::any('verify','verify')->name('verify');// روت برگشت
});

**Comment by khanzadimahdi** [comment]
ادرسی که به بانک پاس میدید https هست؟

**Comment by khanzadimahdi** [comment]
این مشکل مرتبط با پکیج نیست. لطفا issue های قبلی رو چک کنید دوستان پاسخ دادن.

**Comment by aragornq** [comment]
بله

**Comment by aragornq** [comment]
بررسی کرد ولی مشکل حل نشده

**Comment by vahidalvandi** [comment]
منم این مشکل را دارم خیلی عجیبه
