### ISSUE TITLE
Cannot change default gateway dynamically

### ISSUE THREAD

**Issue by msalehi-d** [shetabit/payment#258]
I'm trying to change the payment method based on user selected option, but user always redirects to default gateway the that defined in config/payment.php

```php
// default payment method is payir
$invoice = (new Invoice)->amount($total);
$invoice->detail('tel', $order->tel);
$invoice->via($order->payment_method); // $order->payment_method is zibal or Zibal (both tested)
...
// user redirects to payir gateway!
```
I would appreciate if u helped me with this.

* Laravel 9
* shetabit/multipay 1.17.1

**Comment by msalehi-d** [comment]
Oops, I have to use `via` on `Payment`, not `Invoice`.
Still don't know what does `via` do on `Invoice` object, it seems it doesn't have any effect.

**Comment by khanzadimahdi** [comment]
it works. follow the documents.

**Comment by Abedi98** [comment]
لطفاً نمونه بفرستید بدید چجوری این مشکل رو برطرف کردید . من در دیاکیومنت ندیدم چطوری میشه درگاه را در controller تغییر داد

**Comment by khanzadimahdi** [comment]
see: https://github.com/shetabit/payment#via-change-driver-on-the-fly
