### ISSUE TITLE
امکان نتیجه (موفق یا ناموفق) پرداخت قبل از اجرای متد verify وجود دارد؟

### ISSUE THREAD

**Issue by jalallinux** [shetabit/payment#260]
امکان نتیجه (موفق یا ناموفق) پرداخت قبل از اجرای متد verify وجود دارد؟

**Comment by khanzadimahdi** [comment]
شما تا وریفای نکنید از کجا میدونید پرداخت موفق بوده یا نه!!! امکانش وجود ندارد.
