### ISSUE TITLE
مشکلات درگاه آیدی پی

### ISSUE THREAD

**Issue by honeyamin** [shetabit/payment#261]
استفاده نکنید ازین درگاه که بدبخت میشید پنجاه میلیون پول مشتری منو نمیده افتاده دنبال شکایت از طریق فتا و … منم به عنوان برنامه نویس از گیتهاب گرفته تا هرجا میشه دارم اطلاع رسانی میکنم ،انقدرام شناخته شده نیست بنظر من همون درگاه مستقیم بانکی از همه بهتره
ازین پکیج هم استفاده کردیم براش متاسفانه

**Comment by khanzadimahdi** [comment]
دوست عزیز اینجا فقط یه پکیج داریم که درگاه رو پیاده سازی کرده و به شما قابلیت استفاده رو میده. اینکه درگاه چه رفتاری با شما داره به این پکیج مربوط نمیشه. اونو باید از طریق مراجع قضایی پیگیری کنید. و همیشه قبل از استفاده تحقیق کنید.
