### ISSUE TITLE
دریافت اطلاعات در زمان اعتبارسنجی

### ISSUE THREAD

**Issue by mamadjavadrasty** [shetabit/payment#262]
سلام خسته نباشید
وقتی کاربر پرداخت رو با موفقیت انجام میده باید اطلاعاتی ارسال بشه مثل
InvoiceId
TraceNumber
CardNumber
ReferenceId
ولی در داکیومنت فقط متود getReferenceId هست 
چجوری میشه این اطلاعات رو گرفت؟
ممنون

**Comment by khanzadimahdi** [comment]
سلام. به driver مورد نظرتون برید و کدشو چک کنید.

https://github.com/shetabit/multipay/tree/master/src/Drivers
