### ISSUE TITLE
مشاهده خطای ناشناخته در درگاه سامان بعد از عوض کردن سرور

### ISSUE THREAD

**Issue by ferasat** [shetabit/payment#264]
سلام
 بعد از عوض کردن سرور دیگه وارد درگاه بانکی نمی شود . آی پی را هم به بانک دادیم و مشکل از ای پی نیست و فقط ارور میده :
 `Shetabit\Multipay\Exceptions\PurchaseFailedException: خطای ناشناخته ای رخ داده است. in /var/www/html/vendor/shetabit/multipay/src/Drivers/Saman/Saman.php:181
Stack trace:
#0 /var/www/html/vendor/shetabit/multipay/src/Drivers/Saman/Saman.php(74): Shetabit\Multipay\Drivers\Saman\Saman->purchaseFailed()`

و کلی خط دیگه از فایل ها میگه .

ممنون میشم راهنمایی بفرمایید مشکل چی هست .
اخه نه کد تغییر کرده و نه درگاه فقط سرور جابجا شده است .

**Comment by khanzadimahdi** [comment]
سلام وقتتون بخیر. احتمالا آیپی سرور رو به بانک ندادین!
میتونید از ادرس زیر کدهای مربوط به درگاه سامان رو چک کنید:
https://github.com/shetabit/multipay/blob/master/src/Drivers/Saman/Saman.php

**Comment by ferasat** [comment]
حق با شما بود .درگاه سامان عذر خواهی کرد و گفت آی پی را اشتباهی ست کرده است و اصلاح ای پی انجام شد .

ممنون از شما
