### ISSUE TITLE
مشکل با درگاه پاسارگاد

### ISSUE THREAD

**Issue by aragornq** [shetabit/payment#265]
simplexml_load_file(): I/O warning : failed to load external entity.
سلام .خطای فوق حین ارسال اطلاعات به درگاه پاسارگاد بابت چیست؟

**Comment by khanzadimahdi** [comment]
لطفا ورژن php و همچنین پکیجی که استفاده میکنید را ذکر کنید تا بهتر بتونم کمکتون کنم.

همچنین اطمینان حاصل کنید که ایپی شما توسط بانک وایت لیست شده باشه.

درایور درگاه پاسارگاد در ادرس زیر قابل دسترسی هست. میتونید کد را بررسی کنید:

https://github.com/shetabit/multipay/tree/master/src/Drivers/Pasargad

**Comment by abolfazlahmadiweb** [comment]
این مشکل به علت ناهماهنگ بودن کلید خصوصی با کلیدی هستش که وارد کردید (در زمان ثبت نام درگاه بانک پاسارگاد).
مشکل قطعا از کلید شماست،درخواست کلید جدید رو صادر کنید براتون ارسال کنن،و کلید خصوصی جدید رو جایگزین بفرمایید،موفق باشید

**Comment by abolfazlahmadiweb** [comment]
@khanzadimahdi @aragornq 
مشخصا خطای شما مربوط به لود نشدن فایل xml که نتونسته کلید خصوصی رو لود کنه،از آدرس استاتیک استفاده کنید.
یا اینکه تایپ رو به string تبدیل کنید و محتویات فایل key.txt خودتون رو داخلش قرار بدید

**Comment by yasharomranie** [comment]
ممنون از راهنماییتون ولی من با پشتیبانی صحبت کردم اصلا همچین کد در اختیار ما نگذاشتند وگفتند ساختار زیر ساخت خودنو اصلاح کیند

**Comment by abolfazlahmadiweb** [comment]
حدود دو ماه تغییراتی در زیر ساخت دادن که داکیومنتشون کامل مطالعه کنید ولی اصول یکیه

**Comment by khanzadimahdi** [comment]
وقت شما بخیر. این ایشو رو به دلیل عدم فعالیت میبندم.
