### ISSUE TITLE
Method Illuminate\Support\Str::replace does not exist.

### ISSUE THREAD

**Issue by gener0us** [shetabit/payment#267]
پکیج رو همین دیشب روی سیستم لاراول نصب کردم و با این کد قصد داشتم به درگاه سداد وصل بشم

```
$sadad = (new Invoice())->amount($order_total);

$back = route('checkout.complete.store', ['orderId' => $order->id, 'paymentMethod' => 'sadad']);

$response = Payment::via('sadad')->callBackUrl($back)->purchase($sadad, function ($driver, $transID) {
 })->pay()->render();
```
اما با این خطا مواجه شدم :‌ {message: "Method Illuminate\Support\Str::replace does not exist."}

**Comment by khanzadimahdi** [comment]
FYI: @hos3ein 

https://github.com/shetabit/payment/commit/f1a086744439909e3622f6e1f9ce4bd5ef8af08b#diff-54ea86b9002326c12454c150b9331fcc83aaecd9abcc13ff2d4628327ca775b2R70

**Comment by khanzadimahdi** [comment]
this method introduced in Laravel 8.41.0, we should also support lower versions, please use `str_replace` instead and left a PR to fix it.

FYI: https://stackoverflow.com/questions/67974632/method-illuminate-support-strreplace-does-not-exist

**Comment by mohsenesmaeili** [comment]
last update not support laravel 6 and 7!

open this file : vendor/shetabit/payment/src/Provider/PaymentServiceProvider.php
clear all code and use this code:


[PaymentServiceProvider.zip](https://github.com/shetabit/payment/files/10320774/PaymentServiceProvider.zip)



`
<?php

namespace Shetabit\Payment\Provider;

use Shetabit\Multipay\Payment;
use Illuminate\Support\ServiceProvider;
use Shetabit\Multipay\Request;
use Shetabit\Payment\Events\InvoicePurchasedEvent;
use Shetabit\Payment\Events\InvoiceVerifiedEvent;

class PaymentServiceProvider extends ServiceProvider
{
    /**
     * Perform post-registration booting of services.
     *
     * @return void
     */
    public function boot()
    {
        $this->loadViewsFrom(__DIR__.'/../../resources/views', 'shetabitPayment');

        /**
         * Configurations that needs to be done by user.
         */
        $this->publishes(
            [
                Payment::getDefaultConfigPath() => config_path('payment.php'),
            ],
            'config'
        );

        /**
         * Views that needs to be modified by user.
         */
        $this->publishes(
            [
                __DIR__.'/../../resources/views' => resource_path('views/vendor/shetabitPayment')
            ],
            'views'
        );
    }

    /**
     * Register any package services.
     *
     * @return void
     */
    public function register()
    {
        Request::overwrite('input', function ($key) {
            return \request($key);
        });

        /**
         * Bind to service container.
         */
        $this->app->bind('shetabit-payment', function () {
            $config = config('payment') ?? [];

            return new Payment($config);
        });

        $this->registerEvents();

        // use blade to render redirection form
        Payment::setRedirectionFormViewRenderer(function ($view, $action, $inputs, $method) {
            return view('shetabitPayment::redirectForm')->with(
                [
                    'action' => $action,
                    'inputs' => $inputs,
                    'method' => $method,
                ]
            );
        });
    }

    /**
     * Register Laravel events.
     *
     * @return void
     */
    public function registerEvents()
    {
        Payment::addPurchaseListener(function ($driver, $invoice) {
            event(new InvoicePurchasedEvent($driver, $invoice));
        });

        Payment::addVerifyListener(function ($reciept, $driver, $invoice) {
            event(new InvoiceVerifiedEvent($reciept, $driver, $invoice));
        });
    }
}
`

**Comment by khanzadimahdi** [comment]
@mohsenesmaeili send a PR.

**Comment by khanzadimahdi** [comment]
https://github.com/shetabit/payment/pull/268
