### ISSUE TITLE
درایور درگاه پاسارگاد

### ISSUE THREAD

**Issue by Mohammadrezababaei** [shetabit/payment#27]
سلام 
برای درگاه پاسارگاد درایوری تنظیم نشده؟

**Comment by khanzadimahdi** [comment]
سلام. به دلیل اینکه بنده دسترسی به مستندات این درگاه نداشتم به همین منظور هیچ درگاهی براش ساخته نشده.

در صورتی که مستندات + نمونه کد + سطح دسترسی برای تست درگاه رو دارید اگه مایل هستید اون رو به صورت موقت در اختیار من قرار بدید تا من این درگاه رو ایجاد کنم و داخل پکیج قرار بدم.

برای ارتباط بیشتر با شماره زیر از طریق تلگرام یا واتس اپ با من در ارتباط باشید.

09373620353
مهدی خانزادی

موفق باشید

**Comment by khanzadimahdi** [comment]
من همچنان منتظر پاسخگویی شما هستم تا درگاه پاسارگاد رو بتونیم باهم اظافه کنیم
درصورتی که توانایی همکاری دارید با من در ارتباط باشید. در غیر اینصورت این issue رو میبندم تا 48 ساعت اینده

**Comment by khanzadimahdi** [comment]
درگاه پاسارگاد رو از روی مستنداتش ایجاد کردم. اگه کسی از دوستان ازش استفاده کرد به خطا خورد اطلاع بده یا درستش کنه درخواست مرج بده!

اگه هم درست کار میکنه اطلاع بدید  تا توی داکیومنت ثبت کنم که درست کار میکنه

**Comment by MehdiAghighi** [comment]
سلام آقای خانزادی.
من درگاه پاسارگاد رو تست کردم درست کار نمی‌کنه.
به ارور زیر بر می‌خورم.
"Undefined property: stdClass::$apiGetToken"
داخل فایل:
/vendor/shetabit/payment/src/Drivers/Pasargad/Pasargad.php"

**Comment by MehdiAghighi** [comment]
توی لیست هم تست شده زدین مثل این که

**Comment by khanzadimahdi** [comment]
@MehdiAghighi 

<div dir="rtl">
مشکل شما به این دلیل هست که وندور رو پابلیش نکردین و فایل کانفیگ موجود نیست

وندور رو پابلیش کنید بعدش کانفیگ کش رو کلیر کنید
</div>

```bash
php artisan vendor:publish
php artisan config:clear
```

**Comment by MehdiAghighi** [comment]
@khanzadimahdi سلام

این کارایی که میگید رو انجام دادم.
سایت داشت با درگاه زرین‌پال با پکیج شما کار می‌کرد ولی الان دارم تغییرش میدم به درگاه بانک پاسارگاد اطلاعات رو هم وارد کردم.

**Comment by MehdiAghighi** [comment]
```php
$zarinpalInvoice = (new Invoice)->amount((int)$course->price);

        // You can specify callbackUrl
        $payment = Payment::callbackUrl(env('APP_URL') . "/course/invoice/paid/" . $course->id)->purchase(
            $zarinpalInvoice,
            function($driver, $transactionId) {
                // We can store $transactionId in database.
            }
        )->pay();

        $targetUrl = $payment->getTargetUrl();
```

این هم کد ساخت فاکتور و پرداخت که اون متغیر آخر وقتی زرین‌پال بود ، لینک پرداخت رو دریافت می‌کرد و برمی‌گردوند که من توی فرانت برای پرداخت ازش استفاده می‌کردم.

**Comment by khanzadimahdi** [comment]
<div dir="rtl">
شما از اخرین ورژن پکیج استفاده نمیکنید.

اخرین ورژن رو نصب کنید. تنظیمات و کدها کمی تغییر کرده

کانفیگ رو پاک کنید و دوباره پابلیش کنید

</div>

**Comment by MehdiAghighi** [comment]
@khanzadimahdi ببخشید این مورد رو چک نکرده بودم و خیلی ممنون.
مشکل حل شد

**Comment by MehdiAghighi** [comment]
@khanzadimahdi 
این من بعد از ساختن فاکتور می‌خوام لینک پرداخت رو از درگاه بگیرم ولی وقتی از کد زیر استفاده می‌کنم:

```php
$zarinpalInvoice = (new Invoice)->amount((int)$course->price);

        $customInvoice = new CustomInvoice([
            "course_id" => $course->id,
        ]);

        // You can specify callbackUrl
        $payment = Payment::callbackUrl(env('APP_URL') . "/course/invoice/paid/" . $course->id)->purchase(
            $zarinpalInvoice,
            function($driver, $transactionId) {
                // We can store $transactionId in database.
            }
        )->pay();

        $targetUrl = json_decode($payment->toJson(), true);
```

اما وقتی از `$targetUrl` پارامتر `action` رو میگیرم یک لینک خالیه که هیچ پارامتری نداره 

اما یک فیلد دیگه توی اون json هست به اسم token که من نمی‌دونم دقیقا اون رو باید به چه شکل استفاده کنم یا کجای url بزارم

توی مستندات خود بانک نوشته بود که چون درخواست 
Post 
هست خود کاربر با درخواست ریدایرکت میشه ولی من فقط می‌خوام لینک رو بگیرم.

ممنون میشم اگر کمک کنید

**Comment by khanzadimahdi** [comment]
درگاه پاسارگاد لینک پرداخت نمیده بهتون. باید یه فرم با اکشن و اینپوت های بالا بسازید و  سابمیتش کنید تا کاربر به صورت متد پست به اکشن ارسال بشه

**Comment by MehdiAghighi** [comment]
@khanzadimahdi 
یعنی هیچ‌جوره نمیشه من توی بک‌اند درخواست 
POST 
رو بزنم و لینک پرداخت رو بگیرم از ریسپانس و به فرانت بدم ؟

**Comment by khanzadimahdi** [comment]
<div dir="rtl">
دلیل اینکه باید خود فرانت اینکار رو انجام بده این هست که از ایپی خود کاربری که میخواد پرداخت انجام بده این درخواست باید فرستاده بشه. در غیر اینصورت با ایپی سرور درخواست های زیادی ارسال میشه و بانک حس میکنه دارین بروت فورس میکنید و ایپی شما رو مسدود میکنه

توی ورژن جدید پکیج تمامی درخواست ها به همین صورت هست

میتونید فرمی که خود پکیج براتون میسازه رو استفاده کنید تا ریدایرکت رو براتون انجام بده

</div>

**Comment by MehdiAghighi** [comment]
@khanzadimahdi 
خب مشکل اینجاست من اپ فرانتم با بک‌اندم کلا متفاوتن و یه جای دیگن !
یعنی من اپ فرانتم ریکت هست و بک‌اند لاراول

**Comment by khanzadimahdi** [comment]
<div dir=rtl>

توی اپ فرانت یه فرم با مشخصات جی سانی که بکند بهتون میده بسازید و بعدش سابمیتش کنید. حتی نیاز نیست فرم دیده بشه. میتونید توی صفحه ی فعلی دیسپلی فرم رو مخفی کنید

</div>
