### ISSUE TITLE
تغییر توضیحات ارسال به درگاه به پرداخت

### ISSUE THREAD

**Issue by 6000850** [shetabit/payment#276]
سلام وقت بخیر
در پرتال درگاه به پرداخت یک فیلد description وجود دارد ، که مقدار payment using behpardakht را دارد و این مقدار از فایل config/payment.php ارسال میشود . چگونه میتوانم این مقدار را برای هر تراکنش به صورت اختصاصی ارسال کنم؟؟

ممنون

**Comment by khanzadimahdi** [comment]
publish vendor, then modify it as you wish.

https://github.com/shetabit/payment#publish-vendor-files
