### ISSUE TITLE
نوع ستون transactionId رو در دیتابیس باید چی بزاریم؟

### ISSUE THREAD

**Issue by pichanak** [shetabit/payment#278]
سلام نوع ستون  transactionId رو باید در دیتابیس چی بزاریم این و اصلا جایی مشخص نکردید!
مثلا باید varchar بزاریم اگه درسته باید طولشو چند در نظر بگیریم یا اگه int هست طولش چقدر هست ممنون میشم بفرمائید
و اینکه این $transactionId تولید شده توسط پکیج یونیک هست؟

چرا این امکان و نزاشتین که خودمون شماره سفارش رو به عنوان transactionId  ارسال کنیم و حتما باید از transactionId  ایجاد شده توسط پکیج استفاده کنیم؟

**Comment by khanzadimahdi** [comment]
سلام. نوعش بهتره varchar باشه.
این دیتا از سمت بانک میاد و به همین دلیل نمیتونید خودتون مشخص کنید.
