### ISSUE TITLE
Class "SoapClient" not found

### ISSUE THREAD

**Issue by voicerecordist** [shetabit/payment#280]
سلام
من SoapClient رو در php ini (زمپ) فعال کردم و کلاسش رو هم use کردم اما همچنان برای استفاده از سندباکس زرین پال این ارور رو میده
لاراول 10
پی اچ پی 8.1

**Comment by mohsenmehribusinesss** [comment]
منم همین ارور رو دارم ؟ داستان چیه ؟!
