### ISSUE TITLE
تنظیمات درایور دلخواه در کنترولر

### ISSUE THREAD

**Issue by aliashrafi051** [shetabit/payment#283]
سلام خداقوت 🙌

میشه تنظیمات یک درایور رو از طریق فرم به کنترلر فرستاد؟ دیگه نخاد اصلا به پوشه config بریم و فایل payment.php رو ویرایش کنیم
اگه شدنیه، لطفا نمونه کد بزارین 🙇‍♂️

**Comment by shdehnavi** [comment]
You can set driver configs on the fly:

https://github.com/shetabit/payment?tab=readme-ov-file#config-set-driver-configs-on-the-fly
