### ISSUE TITLE
getPaymentUrl as a public method 

### ISSUE THREAD

**Issue by mvonline** [shetabit/payment#29]
Hi 
You implement getPaymentUrl as a protected method (Zarinpal Driver in my case). 
In some implementation developers need to pass the full payment URL to client Side (maybe Vue) via API and redirect from client Browser. 

is there any way to change getPaymentUrl as a public method ?

**Comment by khanzadimahdi** [comment]
you can retrieve URL like the below:
```php
dd($payment->callbackUrl($url)->pay()->getTargetUrl()); // shows the url
```

**Comment by khanzadimahdi** [comment]
in version 3+ you should get redirection form or JSON (for api usage) like the below

```php
// in your restful api

dd($payment->callbackUrl($url)->pay()->toJson()); // shows the url and fields information
```
or if you want to redirect user in browser, run the below code

```php
return $payment->callbackUrl($url)->pay()->render();
```
