### ISSUE TITLE
مشکل در درگاه پی پینگ

### ISSUE THREAD

**Issue by bahramiholding** [shetabit/payment#291]
سلام وقت بخیر
پکیج در قسمت verify payment اررور نال میده احتمالا نمیتونه api رو کال به سمت payping و نال میده

ورژن لاراول 10
ورژن php 8.2
درگاه پی پینگ

**Comment by bahramiholding** [comment]
`https://static.roocket.ir/images/editor/2023/8/31/2AjmLcROJoxxw8U1jpCX245m6rayYJeb3BZjIWbE.png`

**Comment by khanzadimahdi** [comment]
شما باید از facade استفاده کنید (طبق داکیومنت). اینجا یکراست از کلاس پیمنت استفاده کردید! اون کلاس اصلا متدش استاتیک نیست + شما باید اول ازش یک ابجکت بسازید و بهش کانفیگ رو پاس بدید.

لطفا قبل از استفاده از پکیج ابتدا داکیومنت ها را مطالعه کنید.
