### ISSUE TITLE
خطای 404 درگاه idpay

### ISSUE THREAD

**Issue by ErfKS** [shetabit/payment#294]
دیروز متوجه شدم که زمانی که درایور پرداخت روی idpay تنظیم میشه، کاربر به این url ریدایرکت میشه:
https://idpay.ir/404
قبلاً این مشکل نبود و به تازگی با این مشکل مواجه شدم

**Comment by khanzadimahdi** [comment]
سلام لطفا از طریق خود ایدی پی بررسی کنید. من این تیکت رو میبندم.
