### ISSUE TITLE
پیداکردن transaction  در کال بک

### ISSUE THREAD

**Issue by sajadonline** [shetabit/payment#295]
سلام

با توجه به اینکه هر درایور یکجوری داره دیتاسمت ما در کال بک پاس میده (مثلا یکی نوشته transid یکی نوشته transaction یکی tid ...) چطور میتونیم بصورت داینامیک این مقدار رو پیدا کنیم و در دیتابیس جستجو کنیم ؟

 $receipt = Payment::amount(1000)->transactionId($transaction_id)->verify();
اینجا خودش درایور رو تشخیص میده ؟ من چجوری توی کال بک بفهمم کدوم درایور بوده و بصورت داینامیک $transaction_id رو بهش بدم ؟ 

ممنون از راهنماییتون .

**Comment by khanzadimahdi** [comment]
سلام. توی کالبک فانکشنی که به purchase میدین میتونید کد تراکنش رو ذخیره کنید و بعدا ازش استفاده کنید.

**Comment by bidram** [comment]
سلام $transactionId تولید شده در purchase  با برگشتی سامان متفاوت است
![Screenshot from 2024-08-14 15-45-15](https://github.com/user-attachments/assets/6d58155f-5083-4841-bd52-3e44a3e83660)

در هنگام برگشت برای verify کردن برگشتی سامان را ببنید؟
![Screenshot from 2024-08-14 15-45-15](https://github.com/user-attachments/assets/5fdc2333-10ec-4fe7-866f-82869462a2b2)

مشکل عدم تطابق $transactionId هست.

**Comment by khanzadimahdi** [comment]
وقت شما بخیر! عجیبه این مورد. میتونید کدشو توی ادرس زیر پیدا کنید و بررسی کنید؟

https://github.com/shetabit/multipay/tree/master/src/Drivers

**Comment by bidram** [comment]
سلام مشکل حل شد و سپاسگزارم

**Comment by MH-Zarkhani** [comment]
> سلام مشکل حل شد و سپاسگزارم

salam manam daghighan hamin moshkel daram .. chikar kardin ok shod ?

**Comment by bidram** [comment]
> > سلام مشکل حل شد و سپاسگزارم
> 
> salam manam daghighan hamin moshkel daram .. chikar kardin ok shod ?

سلام
بررسی کنید درایوی که قبل ارسال به درگاه  با درایوی که بعد از برگشت از درگاه برای وریفایی استفاده میشه یکی هست یا خیر

**Comment by MH-Zarkhani** [comment]
> > > سلام مشکل حل شد و سپاسگزارم
> > 
> > 
> > salam manam daghighan hamin moshkel daram .. chikar kardin ok shod ?
> 
> سلام بررسی کنید درایوی که قبل ارسال به درگاه با درایوی که بعد از برگشت از درگاه برای وریفایی استفاده میشه یکی هست یا خیر

are fargh mikard ... felan chon dargah site yeki hastesh .. default gateway ro gozashtam saman ok shod ... vali age bekham chanta dargah ro hamzaman handle konam ... moshkel mikhore ... shoma chegori hal kardin in moshkel ro ?

**Comment by khanzadimahdi** [comment]
> > > > سلام مشکل حل شد و سپاسگزارم
> > > 
> > > 
> > > salam manam daghighan hamin moshkel daram .. chikar kardin ok shod ?
> > 
> > 
> > سلام بررسی کنید درایوی که قبل ارسال به درگاه با درایوی که بعد از برگشت از درگاه برای وریفایی استفاده میشه یکی هست یا خیر
> 
> are fargh mikard ... felan chon dargah site yeki hastesh .. default gateway ro gozashtam saman ok shod ... vali age bekham chanta dargah ro hamzaman handle konam ... moshkel mikhore ... shoma chegori hal kardin in moshkel ro ?

شما باید نام درگاهی که استفاده میکنید رو به عنوان یک فیلد مرتبط با پرداخت توی دیتابیس ذخیره کنید. بعدش که کاربر از درگاه برمیگرده دقیقا قبل از وریفای کردن پیمنت باید اطلاعات پیمنت رو که شامل اون فیلد هم میشه از دیتابیس بکشید بیرون و باهاش پرداخت رو وریفای کنید اینجوری میتونید مطمئن بشید که موقع پیپمنت و وریفای از درگاه یکسانی استفاده میکنید

**Comment by MH-Zarkhani** [comment]
> > > > > سلام مشکل حل شد و سپاسگزارم
> > > > 
> > > > 
> > > > salam manam daghighan hamin moshkel daram .. chikar kardin ok shod ?
> > > 
> > > 
> > > سلام بررسی کنید درایوی که قبل ارسال به درگاه با درایوی که بعد از برگشت از درگاه برای وریفایی استفاده میشه یکی هست یا خیر
> > 
> > 
> > are fargh mikard ... felan chon dargah site yeki hastesh .. default gateway ro gozashtam saman ok shod ... vali age bekham chanta dargah ro hamzaman handle konam ... moshkel mikhore ... shoma chegori hal kardin in moshkel ro ?
> 
> شما باید نام درگاهی که استفاده میکنید رو به عنوان یک فیلد مرتبط با پرداخت توی دیتابیس ذخیره کنید. بعدش که کاربر از درگاه برمیگرده دقیقا قبل از وریفای کردن پیمنت باید اطلاعات پیمنت رو که شامل اون فیلد هم میشه از دیتابیس بکشید بیرون و باهاش پرداخت رو وریفای کنید اینجوری میتونید مطمئن بشید که موقع پیپمنت و وریفای از درگاه یکسانی استفاده میکنید

are hamin kar mikonam va transaction_id ro ham zakhire mikonam ... moskel injast toye callback url transaction_id k set kardam barnemigarde va hamon callback_url env set mishe bedon transaction_id

**Comment by khanzadimahdi** [comment]
> > > > > > سلام مشکل حل شد و سپاسگزارم
> > > > > 
> > > > > 
> > > > > salam manam daghighan hamin moshkel daram .. chikar kardin ok shod ?
> > > > 
> > > > 
> > > > سلام بررسی کنید درایوی که قبل ارسال به درگاه با درایوی که بعد از برگشت از درگاه برای وریفایی استفاده میشه یکی هست یا خیر
> > > 
> > > 
> > > are fargh mikard ... felan chon dargah site yeki hastesh .. default gateway ro gozashtam saman ok shod ... vali age bekham chanta dargah ro hamzaman handle konam ... moshkel mikhore ... shoma chegori hal kardin in moshkel ro ?
> > 
> > 
> > شما باید نام درگاهی که استفاده میکنید رو به عنوان یک فیلد مرتبط با پرداخت توی دیتابیس ذخیره کنید. بعدش که کاربر از درگاه برمیگرده دقیقا قبل از وریفای کردن پیمنت باید اطلاعات پیمنت رو که شامل اون فیلد هم میشه از دیتابیس بکشید بیرون و باهاش پرداخت رو وریفای کنید اینجوری میتونید مطمئن بشید که موقع پیپمنت و وریفای از درگاه یکسانی استفاده میکنید
> 
> are hamin kar mikonam va transaction_id ro ham zakhire mikonam ... moskel injast toye callback url transaction_id k set kardam barnemigarde va hamon callback_url env set mishe bedon transaction_id

شما بایدcallbackUrl رو قبل از purchase کال کنید. در غیر اینصورت اعمال نمیشه چون purchase درون بانک انجام شده و قابل تغییر نخواهد بود

**Comment by MH-Zarkhani** [comment]
> > > > > > > سلام مشکل حل شد و سپاسگزارم
> > > > > > 
> > > > > > 
> > > > > > salam manam daghighan hamin moshkel daram .. chikar kardin ok shod ?
> > > > > 
> > > > > 
> > > > > سلام بررسی کنید درایوی که قبل ارسال به درگاه با درایوی که بعد از برگشت از درگاه برای وریفایی استفاده میشه یکی هست یا خیر
> > > > 
> > > > 
> > > > are fargh mikard ... felan chon dargah site yeki hastesh .. default gateway ro gozashtam saman ok shod ... vali age bekham chanta dargah ro hamzaman handle konam ... moshkel mikhore ... shoma chegori hal kardin in moshkel ro ?
> > > 
> > > 
> > > شما باید نام درگاهی که استفاده میکنید رو به عنوان یک فیلد مرتبط با پرداخت توی دیتابیس ذخیره کنید. بعدش که کاربر از درگاه برمیگرده دقیقا قبل از وریفای کردن پیمنت باید اطلاعات پیمنت رو که شامل اون فیلد هم میشه از دیتابیس بکشید بیرون و باهاش پرداخت رو وریفای کنید اینجوری میتونید مطمئن بشید که موقع پیپمنت و وریفای از درگاه یکسانی استفاده میکنید
> > 
> > 
> > are hamin kar mikonam va transaction_id ro ham zakhire mikonam ... moskel injast toye callback url transaction_id k set kardam barnemigarde va hamon callback_url env set mishe bedon transaction_id
> 
> شما بایدcallbackUrl رو قبل از purchase کال کنید. در غیر اینصورت اعمال نمیشه چون purchase درون بانک انجام شده و قابل تغییر نخواهد بود

nokte dg inke ba tavajoh b code verify

```$receipt = Payment::amount(1000)->transactionId($transaction_id)->verify();```

driver bayad ba tavojeh b transaction_id khodesh tashkhis dade beshe ...

**Comment by khanzadimahdi** [comment]
شما باید ادرس کالبک رو خودتون بسازید و متکی به چیزی که بانک بهتون میده نباشید

```
/payment/{id)
```
شما اول باید پیمنتی که میخواید انجام بدید رو توی دیتابیس ذخیره کنید بعدش یه ایدی دارید که باهاش میتونید یه روت مثل بالا بسازید و بدید به کالبک. موقع برگشت هم دقیقا همونو بهتون میده و میتونید با ایدی برید و رکورد رو از دیتابیس بکشید بیرون. برای ساختن روت هم میتونید از تابع خود لاراول با نام route استفاده کنید که بهش پارامتر ایدی و نام روت رو میدید بهتون روت رو برمیگردونه

**Comment by khanzadimahdi** [comment]
> > > > > > > > سلام مشکل حل شد و سپاسگزارم
> > > > > > > 
> > > > > > > 
> > > > > > > salam manam daghighan hamin moshkel daram .. chikar kardin ok shod ?
> > > > > > 
> > > > > > 
> > > > > > سلام بررسی کنید درایوی که قبل ارسال به درگاه با درایوی که بعد از برگشت از درگاه برای وریفایی استفاده میشه یکی هست یا خیر
> > > > > 
> > > > > 
> > > > > are fargh mikard ... felan chon dargah site yeki hastesh .. default gateway ro gozashtam saman ok shod ... vali age bekham chanta dargah ro hamzaman handle konam ... moshkel mikhore ... shoma chegori hal kardin in moshkel ro ?
> > > > 
> > > > 
> > > > شما باید نام درگاهی که استفاده میکنید رو به عنوان یک فیلد مرتبط با پرداخت توی دیتابیس ذخیره کنید. بعدش که کاربر از درگاه برمیگرده دقیقا قبل از وریفای کردن پیمنت باید اطلاعات پیمنت رو که شامل اون فیلد هم میشه از دیتابیس بکشید بیرون و باهاش پرداخت رو وریفای کنید اینجوری میتونید مطمئن بشید که موقع پیپمنت و وریفای از درگاه یکسانی استفاده میکنید
> > > 
> > > 
> > > are hamin kar mikonam va transaction_id ro ham zakhire mikonam ... moskel injast toye callback url transaction_id k set kardam barnemigarde va hamon callback_url env set mishe bedon transaction_id
> > 
> > 
> > شما بایدcallbackUrl رو قبل از purchase کال کنید. در غیر اینصورت اعمال نمیشه چون purchase درون بانک انجام شده و قابل تغییر نخواهد بود
> 
> nokte dg inke ba tavajoh b code verify
> 
> `$receipt = Payment::amount(1000)->transactionId($transaction_id)->verify();`
> 
> driver bayad ba tavojeh b transaction_id khodesh tashkhis dade beshe ...

درایور چطور تشخیص بده که شماره تراکنش مرتبط با کدوم درگاه بانکی هست؟ درایور هیچ چیزی رو جایی ذخیره نمیکنه و فقط مسئول تبادل اطلاعات بین شما و بانک هست. شما خودتون موظف هستید اطلاعاتی که نیاز دارید رو توی دیتابیس ذخیره کنید. من حدس میزنم شما داکیومنت های پکیج رو نخوندید و یکراست شروع به پیاده سازی کد کردین! لطفا یکبار دیگه مستندات پکیج رو مطالعه کنید.

**Comment by khanzadimahdi** [comment]
> > شما باید ادرس کالبک رو خودتون بسازید و متکی به چیزی که بانک بهتون میده نباشید
> > ```
> > /payment/{id)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > شما اول باید پیمنتی که میخواید انجام بدید رو توی دیتابیس ذخیره کنید بعدش یه ایدی دارید که باهاش میتونید یه روت مثل بالا بسازید و بدید به کالبک. موقع برگشت هم دقیقا همونو بهتون میده و میتونید با ایدی برید و رکورد رو از دیتابیس بکشید بیرون. برای ساختن روت هم میتونید از تابع خود لاراول با نام route استفاده کنید که بهش پارامتر ایدی و نام روت رو میدید بهتون روت رو برمیگردونه
> 
> hame in kara anjam shode
> 
> in issue k man baz kardam bebinin
> 
> [#335](https://github.com/shetabit/payment/issues/335)

بعله روی ایشو به شما پاسخ دادم. کدی که شما نوشتید اشتباه هست. وقتی که متد purchase رو کال میکنید این متد میاد درگاه بانک رو کال میکنه و تراکنش رو ثبت میکنه. شما بعد از کال کردن این متد اومدید و callbackUrl رو کال کردید که باعث میشه ادرس کالبک ست بشه. مشکل اینجاست که شما متد ها رو به ترتیب استفاده نکردید. بعد از ساخته شدن تراکنش نمیشه ادرس کالبک اون رو توی بانک تغییر داد. شما باید قبل از کال کردن purchase تمامی اطلاعات مورد نیاز رو ست کنید و در اخر purchase رو کال کنید تا تراکنش توی بانک ساخته بشه و با متد pay کاربر رو به درگاه ببرید تا پرداخت کنه. لطفا طبق داکیومنت های پکیج پیش برید و یکبار دیگه داکیومنت ها رو بررسی کنید
