### ISSUE TITLE
از بین رفتن درگاه پرداخت دلخواه بعد از بروزرسانی شدن پکیج

### ISSUE THREAD

**Issue by Saberqadimi** [shetabit/payment#299]
وقت بخیر و امیدوارم خسته نباشین,موردی که من نیاز دارم این هستش که ممکنه سایت من از درگاه پرداخت زرین پال یا هر بانک دیگه ای دوتا نیاز داشته باشه بعنوان مثال درگاه پرداخت زرین پال اصلی و درگاه پرداخت دوم (زرین پال) با این حال درگاه پرداخت دلخواه رو میسازم منتها بعداز بروزرسانی شدن پکیج درگاه پرداخت های دلخواه از بین میرن راه حلی برای این موضوع دارین پیشنهاد بدین ؟

**Comment by khanzadimahdi** [comment]
شما میتونید درگاه پرداخت مورد نظر خودتون رو پیاده سازی کنید و بعد درون فایل [payment.php](https://github.com/shetabit/multipay/blob/master/config/payment.php) تنظیماتش رو قرار بدید و شروع به استفاده از درگاه مورد نظر خودتون کنید. مادامی که تنظیمات درگاه شما به صورت صحیح درون این فایل موجود باشه باید بتونید از درگاه استفاده کنید.

من متوجه نمیشم چرا ممکنه درگاه شما حذف بشه؟ شما تا هنگاهی که وندور رو پابلیش نکنید فایل تنظیماتتون تغییری نمیکنه. وقتی هم که وندور رو پابلیش کنید قطعا آگاهی دارید که ممکنه تنظیماتتون تغییر کنه و میتونید دوباره تنظیمات رو به حالت قبل برگردونید.

**Comment by Saberqadimi** [comment]
ممنونم مهندس , چون ممکنه پکیج جدیدی تو پروژه استفاده بشه و کمپوزر اپدیت بشه مجددا وندور پابلیش میشه و همین حذف شدن درگاه اتفاق میفته میخواستم ببینم راه حلی داره یا نه که گویا فقط باید مجددا بیام و کلاس و بسازم و کانفیگش رو انجام بدم .

**Comment by khanzadimahdi** [comment]
دوست عزیز شما وقتی پکیجی رو اپدیت میکنی یا وندور رو پابلیش میکنی پروسه به این صورت هست که بعدش باید کانفیگ ها یا باقی فایل هایی که ممکنه رونویسی شده باشن رو چک کنید و تصحیح کنید. این مشکل نیست و کلا پروسه پابلیش کردن وندور به همین صورت هست.
