### ISSUE TITLE
خطای "تراکنش توسط خریدار کنسل شده است." 

### ISSUE THREAD

**Issue by AfshinEfati** [shetabit/payment#30]
سلام 
درگاه رو همونطوری که نوشته بودید ست کردم . زمانی که ارسال میشه برای پرداخت خطا میده که 
تراکنش توسط خریدار کنسل شده است.
درگاه sep  رو استفاده میکنم

**Comment by khanzadimahdi** [comment]
<div dir=rtl>
سلام اگه امکان داره کد خودتون رو قرار بدید تا بررسی کنم. 
</div>

**Comment by khanzadimahdi** [comment]
من منتظر هستم تا کدی که نوشتین رو درج کنید تا باهم بررسی کنیم مشکلتون رو حل کنیم. در صورتی که کد رو قرار ندید این ایشو رو تا ۴۸ ساعت اینده میبندم. 

موفق باشید

**Comment by AfshinEfati** [comment]
سلام
باز اینترنت دچار مشکل شده و باز نمیشه سایت گیت هاب . همینجا براتون میفرستم
فایل ها رو


‫‪mahdikhanzadi‬‏ <‪notifications@github.com‬‏> در تاریخ چهارشنبه ۱۸ دسامبر
۲۰۱۹ ساعت ۲۲:۵۵ نوشت:‬

**Comment by AfshinEfati** [comment]
File payment config 
`
'default' => 'saman',
`
`'saman' => [
            'apiPurchaseUrl' => 'https://sep.shaparak.ir/Payments/InitPayment.asmx?WSDL',
            'apiPaymentUrl' => 'https://sep.shaparak.ir/payment.aspx',
            'apiVerificationUrl' => 'https://sep.shaparak.ir/payments/referencepayment.asmx?WSDL',
            'merchantId' => '21173252',
            'callbackUrl' => 'https://www.xdgbit.com/customer/confirm_pay_customer',
            'description' => 'payment in '.config('app.name'),
        ],`

PayController
`
$invoice=(new Invoice)->amount($price);
        return Payment::purchase($invoice, function ($driver, $transactionId) {
            // store transactionId in database, we need it to verify payment in future.
            $res = new Payment_pay();
            $res->transactionId = $transactionId;
            $res->user_id = auth()->user()->id;
            $res->price=2000;
            $res->save();
        })->pay();
`
Call back function 

`
 $res=Payment_pay::where('user_id','=',auth()->user()->id)->orderBy('id','desc')->get();
        foreach ($res as $row)
        {

            $transaction_id=$row['transaction_id'];
        }
        try {
            $receipt = Payment::amount(2000)->transactionId($transaction_id)->verify();

            echo $receipt->getReferenceId();

        } catch (InvalidPaymentException $exception) {

            echo $exception->getMessage();
        }
`

**Comment by khanzadimahdi** [comment]
موقعی که وریفای میکنید کد تراکنش رو بردارید و دوباره تست کنید.  به صورت زیر عمل کنید و نتیجه رو بهم بدید

```
        $transaction_id=$row['transaction_id'];
    try {
        $receipt = Payment::amount(2000)->verify();

        echo $receipt->getReferenceId();
    } catch (InvalidPaymentException $exception) {
        echo $exception->getMessage();
    }
```

**Comment by AfshinEfati** [comment]
اصلا به وریفای نمیرسه  
زمانی که درخواست میره برای درگاه ، همون اولش خطا میده و بر میگرده 
خود درگاه این خطا رو نشون میده 

> خطا! .اطلاعات نامعتبر مي باشد

بعد که دکمه بازگشت رو میزنم اونجا این مسیج رو میده 

> تراکنش توسط خریدار کنسل شده است.

**Comment by khanzadimahdi** [comment]
اها. پس مشکلی که دارین از اطلاعاتیه که واسه سرور ارسال میکند.

مرچند ایدی رو به درستی وارد  کردین؟ و لینک برگشت به درستی ست شده؟

**Comment by AfshinEfati** [comment]
> اها. پس مشکلی که دارین از اطلاعاتیه که واسه سرور ارسال میکند.
> 
> مرچند ایدی رو به درستی وارد کردین؟ و لینک برگشت به درستی ست شده؟

درگاه سامان مرچنت آیدی ندادن اصلا 
3 تا عدد چند رقمی داده . 
تک تک رو تست کردم . روی 2 تا همون اول میزنه اطلاعات اشتباه است . روی یکی هم خطایی نمیده که همون رو  توی فایل کانفیک payment  ست کردم

**Comment by khanzadimahdi** [comment]
اوکی. میشه با تلگرام من در ارتباط باشید تا مشکلتون رو حل کنم؟ میخوام که اطلاعات درگاهتون رو اگه امکانش هست در اختیار من قرار بدید تا خودم تست کنم.
اگه مایل به انجام اینکار هستید با شماره زیر توی تلگرام اطلاعات درگاه خودتون رو به صورت موقت در اختیار من قرار بدید تا بررسی کنم و بهتون اطلاع بدم که مشکل از چی میتونه باشه

**09373620353**

**Comment by AfshinEfati** [comment]
چشمممنونSent from my Samsung Galaxy smartphone.
-------- Original message --------From: mahdikhanzadi <notifications@github.com> Date: 19/12/2019  13:13  (GMT+03:30) To: shetabit/payment <payment@noreply.github.com> Cc: Afshin <afshin.efati@gmail.com>, Author <author@noreply.github.com> Subject: Re: [shetabit/payment] خطای "تراکنش توسط خریدار کنسل شده است."  (#30) اوکی. میشه با تلگرام من در ارتباط باشید تا مشکلتون رو حل کنم؟ میخوام که اطلاعات درگاهتون رو اگه امکانش هست در اختیار من قرار بدید تا خودم تست کنم.
اگه مایل به انجام اینکار هستید با شماره زیر توی تلگرام اطلاعات درگاه خودتون رو به صورت موقت در اختیار من قرار بدید تا بررسی کنم و بهتون اطلاع بدم که مشکل از چی میتونه باشه
09373620353

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/shetabit/payment/issues/30?email_source=notifications\u0026email_token=AJP3MQCWDGP3BNRPIC26DUTQZM64FA5CNFSM4J4IE7E2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEHJBA2Q#issuecomment-567414890",
"url": "https://github.com/shetabit/payment/issues/30?email_source=notifications\u0026email_token=AJP3MQCWDGP3BNRPIC26DUTQZM64FA5CNFSM4J4IE7E2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEHJBA2Q#issuecomment-567414890",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by khanzadimahdi** [comment]
مشکل از تایپ کست بود که حل شد. مرسی از همکاریتون واقعا خوشحال شدم.

https://github.com/shetabit/payment/commit/c51a2e93c212286fd1db289a753057de4edc3acf

موفق باشید.

**Comment by khanzadimahdi** [comment]
ورژن جدید پکیج رو نصب کنید. دستور کامپوزر اپدیت بزنید تا بروز بشه و مشکل حل بشه
