### ISSUE TITLE
دریافت کد پذیرنده معتبر نیست در به پرداخت ملت

### ISSUE THREAD

**Issue by majidjamhsidi** [shetabit/payment#305]
سلام وقت بخیر . وقتی درگاه به پرداخت رو فعال میکنم میگه کد پذیرنده معتبر نیست . در صورتی که چند بار با پیگیری به پرداخت دیدیم همه چیز درسته . 

علت از چی میتونه باشه ؟ ممنون میشم راهنمایی کنید

* Version used : 8.1
* Operating system and version : centos 7
* Link to your project: https://orginalqeshm.ir

**Comment by khanzadimahdi** [comment]
سلام. وقت شما بخیر. 
میتونید کد مربوط به درگاه بهپرداخت رو از ادرس زیر پیدا کنید

https://github.com/shetabit/multipay/tree/master/src/Drivers/Behpardakht

چون درگاه ها ممکنه تغییر کنن لطفا چک کنید ببینید پیاده سازی درگاه متناسب با داکیومنت درگاه هست یا نه! همچنین کانفیگ مرتبط با درگاه رو درون برنامه خودتون دوباره چک کنید

**Comment by khanzadimahdi** [comment]
وقت شما بخیر. این ایشو رو به دلیل عدم فعالیت میبندم.
