### ISSUE TITLE
خطا در استفاده از درگاه سپهر(صادرات)

### ISSUE THREAD

**Issue by mohsen1851** [shetabit/payment#307]
سلام.وقت بخیر
من از ورژن 4.3.3 استفاده میکنم
موقع درخواست پرداخت خطای زیر رو میده
"درگاه مورد نظر پاسخگو نمی‌باشد، لطفا لحظاتی بعد امتحان کنید."
لطفا راهنمایی کنید

**Comment by khanzadimahdi** [comment]
وقت شما بخیر. این ایشو رو به دلیل عدم فعالیت میبندم.

**Comment by daniyal1396m** [comment]
@khanzadimahdi سلام issue  من و حذف کردید ؟
