### ISSUE TITLE
مشکل در درگاه پاسارگاد

### ISSUE THREAD

**Issue by yasharomranie** [shetabit/payment#308]
مشکل در درگاه پاسارگاد 

سلام وقت بخیر 

زیر ساخت عوض شده اند و دیگه با certificate  کار نمیکنه ایا امکان به روز رسانی هست ؟
با پشتیبانی بانک در تماس بودم گفت زیر ساخت به روز کنید

**Comment by khanzadimahdi** [comment]
سلام. پکیج اوپن سورس هست. شما میتونید طبق مستندات درگاه بانکی مورد نظرتون رو ایجاد کنید یا تغییر بدید و درخواست مرج بزارید.

کد مربوط به درگاه پاسارگاد رو میتونید در ادرس زیر پیدا کنید

https://github.com/shetabit/multipay/blob/master/src/Drivers/Pasargad/Pasargad.php
