### ISSUE TITLE
نبود راهی برای گرفتن لینک درگاه پرداخت

### ISSUE THREAD

**Issue by Blankevoort** [shetabit/payment#310]
## Detailed description

سلام و خسته نباشید.  خواستم بدونم که راهی برای گرفتن لینک درگاه پرداخت نیست قبل اینکه یوزر به درگاه پرداخت redirect بشه؟ پروژه من داره به صورت API کار میکنه و داشتم داکیومنت شمارو مطالعه میکردم و تنها راهی که شبیه به این موضو دیدم toJson بود ولی باز هم لینکی برای response برنمیگردونه

## Environment

* Version used PHP 8.3.6:
* Laravel 8
* Operating system and version Windows 10
* Prject Link:
 * https://github.com/Blankevoort/TikSystem

**Comment by khanzadimahdi** [comment]
درود و وقت بخیر.
توی ساختار جی سان لینک رو میتونید ببینید. 
به کدهای زیر دقت کنید:

https://github.com/shetabit/multipay/blob/master/src/RedirectionForm.php#L190

https://github.com/shetabit/multipay/blob/master/src/RedirectionForm.php#L29

توی رسپانس json فیلد action لینک پرداخت رو درون خودش جای میده.

**Comment by Blankevoort** [comment]
با این کدها برگردونده میشه ولی ریسپانس من خالی هست. داخل هدر هارو هم نگاه کردم کاملا خالی هستن.
            return $payment->purchase($invoice, function($driver, $transactionId) use ($transaction) {
                $transaction->transaction_id = $transactionId;
                $transaction->save();
            })->pay()->toJson();
![image](https://github.com/shetabit/payment/assets/89256783/1601b56d-61ff-474b-bdfb-360eb8797209)
![image](https://github.com/shetabit/payment/assets/89256783/602514da-9de5-4f94-81a9-68de1bd8b8f7)

**Comment by khanzadimahdi** [comment]
اونی که عکسشو گذاشتین preflight request هست همینطور ک توی عکس مشخصه متدش هم option هست! دومین رکوئست رو طبق تصویری ک گذاشتین چک کنید.

**Comment by Blankevoort** [comment]
اگر میتونید لطفا کدی که دارم رو ببینین من خودم نتونستم راهی پیدا بکنم ممنون میشم 🙌

https://github.com/Blankevoort/TikSystem/blob/main/TikSystem%20BackEnd/app/Http/Controllers/PurchaseController.php

**Comment by Blankevoort** [comment]
ببخشید راهی نیست چک کنید و مشکل کدم رو بهم بگین؟
