### ISSUE TITLE
مشکل متد ارسال در درگاه سامان

### ISSUE THREAD

**Issue by hamedm94** [shetabit/payment#311]
هنگام انتقال به درگاه سامان از متد GET استفاده شده که درگاه سامان فقط متد POST را قبول می کند. این متد در درایور سامان باید تصحیح شود تا درگاه به درستی کار کند.

**Comment by khanzadimahdi** [comment]
سلام وقت بخیر. قبلا به این صورت نبوده و احتمالا درگاه سامان سمت خودشون این تغییرات رو دادن بدون اینکه به کاربرها اطلاع بدن! (کاری که زرین پال هر چند وقت میکنه و همه چیز بهم میریزه)

لطفا توی کد تغییرات مورد نظرتون رو بدید و درخواست مرج بزارید. پکیج اوپن سورس هست و سعی کنید مشارکت داشته باشید.

ممونم ازتون.

**Comment by Rayiumir** [comment]
@hamedm94 

سلام وقت بخیر.
آره
اول پروژه را فورک کنید و بعد که ویرایش انجام دادید را Pull Requests کنید.

**Comment by khanzadimahdi** [comment]
وقت شما بخیر. این ایشو رو به دلیل عدم فعالیت میبندم.
