### ISSUE TITLE
مشکل تغییر درگاه default

### ISSUE THREAD

**Issue by Maniheshmati** [shetabit/payment#314]
سلام من طبق مراحل نصب رو انجام دادم و جلو رفتم و قسمت default فایل کانفیگ Payment رو به sepehr تغییر دادم ولی باز هم درگاه default رو درگاه زرین پال در نظر میگیره.
ورزژن لاراولم 8.8 هست و ورژن php هم 8.1
Payment.php:
```
    'default' => 'sepehr',
```
![image](https://github.com/user-attachments/assets/7fdc9f75-781a-40ec-92e4-04e5f9d8b15d)

**Comment by progintYasin** [comment]
سلام
اینجوری بنویس

` try {
            $invoice = (new Invoice)->amount(1000);
            return shetabitPayment::via('parsian')->callbackUrl(route('payment.callback2'))
                ->purchase($invoice)->pay()->render();
        } catch (\Exception $e) {
            Log::error('Payment error: ' . $e->getMessage());
            return $e->getMessage();
        }`

**Comment by Maniheshmati** [comment]
آره یک مرحله جلو رفت و آیپی سرور رو که برای بانک مجاز کرده بودیم قبول میکنه خیلی ممنونم ولی الان داخل request میاد به این صفحه و اتفاقی نمی افته


![image](https://github.com/user-attachments/assets/e1ffdee3-abba-465b-a2da-fa422eb0e17c)

**Comment by progintYasin** [comment]
اینجا اگر توی درگاه نمیره 2 تا دلیل داره
یا قندشکن روشن داری
یا تداخل js داری که باید رفع کنین
توی inspect console ببین خطا چی  داری رفعش کن

**Comment by Maniheshmati** [comment]
تنها تداخلی که داره اینه که یه جا دنبال یه عکس میگرده ولی پیدا نمیکنه که سمت فرانته این requrest:
![image](https://github.com/user-attachments/assets/35537a62-9999-4587-ae3c-f54ac7041505)

**Comment by Maniheshmati** [comment]
اینجا هم یه مشکل شبیه مشکل خودم دیدم ولی متوجه نشدم نتیجش چی شده:
https://github.com/shetabit/payment/issues/140
