### ISSUE TITLE
مشکل در درایور لوکال

### ISSUE THREAD

**Issue by Amirhossein256** [shetabit/payment#316]
با سلام، هنگام استفاده از درایور Local جهت تست فرایند پرداخت مشکلاتی وجود داره از جمله عدم ریدایرکت صحیح و عدم وجود local-form در composer publish
فقط فایل redirectForm وجود داره

و اینکه جهت ریدایرکت آدرسی دهی درستی انجام نشده.
![image](https://github.com/user-attachments/assets/b4ae8073-5332-4a8e-bb89-f0a6a8e513d5)

با این تفاصیر، آیا راه حلی یا روش دیگه ای برای تست فرایند روی لوکال وجود داره یا خیر؟

**Comment by khanzadimahdi** [comment]
سلام وقت بخیر. 
متوجه مشکل شما نشدم! لطفا کدی که نوشتید رو نیز به اشتراک بزارید. 
اگه مشکلی پیدا کردید و امکانش رو دارید لطفا PR ایجاد کنید. درگاه لوکال رو یکی از دوستان به پکیج اضافه کرده و قطعا یکسری کم و کسری داره و ویژگی های مورد نظر برای custom کردن فرم رو احتمالا نداره (مثلا فرم باید پابلیش بشه توی vendor)
اما مشکل ریدایرکت نباید وجود داشته باشه و به درستی باید کار کنه.

**Comment by Amirhossein256** [comment]
@khanzadimahdi 
عذرخواهم بابت توضیحات ناکافی در این issue
یکسری مشکلات وجود داره در درگاه local
از جمله پابلیش نشدن فایل view و نبود csrf_token 
در اسرع وقت بابت مواردی که گفتم pr رو ایجاد میکنم روی ریپو multipay.
