### ISSUE TITLE
Paystart

### ISSUE THREAD

**Issue by RezaParsian** [shetabit/payment#327]
### سلام

زمانی که می‌خوام با درگاه **Paystar** کار کنم با خطای زیر مواجه می‌شم!

![127 0 0 1_8000_dashboard_user_orders_add](https://github.com/user-attachments/assets/792938d0-cc29-447a-ada4-4205fb129329)

**Comment by RezaParsian** [comment]
این مشکل هم دارم!

![127 0 0 1_8000_dashboard_user_orders_add (1)](https://github.com/user-attachments/assets/835ccb2d-98a4-4c6a-a481-cd24b7e1dacb)

**Comment by khanzadimahdi** [comment]
please run `update-ca-certificates` on your machine.

see: https://stackoverflow.com/questions/28858351/php-ssl-certificate-error-unable-to-get-local-issuer-certificate

this issue is not related to this package.
