### ISSUE TITLE
SOAP-ERROR: Parsing WSDL: Couldn't load from

### ISSUE THREAD

**Issue by akarimeee65** [shetabit/payment#329]
## Detailed description

Provide a detailed description of the change or addition you are proposing.

Make it clear if the issue is a bug, an enhancement or just a question.

## Context

Why is this change important to you? How would you use it?

How can it benefit other users?

## Possible implementation

Not obligatory, but suggest an idea for implementing addition or change.

## Your environment

Include as many relevant details about the environment you experienced the bug in and how to reproduce it.

* Version used (e.g. PHP 7.2, HHVM 3):
* Operating system and version (e.g. Ubuntu 19.04, Windows 10):
* Link to your project:
* ...
* ...

بعد از پرداخت و در متد verify در لاراول 11 با این مشکل روبرو میشم:
SOAP-ERROR: Parsing WSDL: Couldn't load from 'https://pec.shaparak.ir/NewIPGServices/Confirm/ConfirmService.asmx?wsdl' : failed to load external entity "https://pec.shaparak.ir/NewIPGServices/Confirm/ConfirmService.asmx?wsdl"

**Comment by khanzadimahdi** [comment]
سلام. تمپلیت issue رو درست پر کنید! هرچی دیفالت بوده گذاشتین تهش یه متن نوشتین! این تمپلیت رو برای شما ساختیم که اطلاعات کافی بدید. 

آیپی سرور شما توسط شاپرک وایت لیست شده؟

**Comment by akarimeee65** [comment]
ببخشید من اونقدر درگیر بودم و خسته و پر از استرس که اصلا حواسم نبود

**Comment by akarimeee65** [comment]
مشکل از جای دیگه ای بود و ارتباطی به پکیج نداشت. با عرض پوزش
