### ISSUE TITLE
درگاه به پرداخت

### ISSUE THREAD

**Issue by esmaeiliehsan** [shetabit/payment#330]
کسی از درگاه به پرداخت استفاده میکنه؟
هر چی میزنم ارور برمیگرده 
"فرمت اطلاعات ارسالی صحیح نمی باشد"
بارها چک کردم

**Comment by khanzadimahdi** [comment]
کد درگاه رو میتونید توی ادرس زیر پیدا کنید و چک کنید:

https://github.com/shetabit/multipay/blob/master/src/Drivers/Behpardakht/Behpardakht.php

**Comment by esmaeiliehsan** [comment]
همه چیزو بررسی کردم حتی با داکیومنت خود به پرداخت ولی بازم مشکل سرجاشه

**Comment by esmaeiliehsan** [comment]
حل شد
برای کسی اگر به مشکل اینجوری خورد
نوع ارسال callbackurl رو خیلی دقت کنید
