### ISSUE TITLE
php artisan view:cache issue

### ISSUE THREAD

**Issue by alirezamaleky** [shetabit/payment#34]
## Detailed description

`php artisan view:cache` not working

## Context

I have a issue on running `php artisan view:cache` after install this package, It causes the following error:

The "/var/www/vendor/shetabit/payment/src/Provider/resources/views" directory does not exist.

## Possible implementation

i'm using vue and I don't need to publish blade file(s)

**Comment by khanzadimahdi** [comment]
can you solve this and send pull request ? i will merge it.
