### ISSUE TITLE
Verify payment problem

### ISSUE THREAD

**Issue by shdehnavi** [shetabit/payment#38]
Hi
As you know, we can verify zarin
pal payments by Authority uuid in pure PHP codes and Zarinpal let us to get Authority uuid before redirecting to payment url and we can save it to database to help us verifying payments in future. when Zarinpal payment done, Zarinpal redirects to our callback url and pass some parameters like Authority uuid for payment verfying.
I have a problem with this payment package, when we store transactionId in database for every payment, how we can verify in callback page when we have no parameters passed by payment page?
I hope you understand my problem,

My payment function code:
```php
use App\Models\File;
use App\Models\Payment;
use App\Models\TelegramUser;
use Shetabit\Payment\Exceptions\InvalidPaymentException;
use Shetabit\Payment\Invoice;
use Shetabit\Payment\Facade\Payment as PaymentFacade;

public function buyFile($tid, $fid)
{
        $file = File::findOrFail($fid);
        $telegramUser = TelegramUser::whereId($tid)->get();

        $invoice = new Invoice();
        $invoice->amount($file->price);
        $invoice
            ->detail('description', "خرید فایل {$file->path}")
            ->detail('email', 'info@shdehnavi.ir')
            ->detail('mobile', '09123456789');

        return PaymentFacade::callbackUrl(route('bot.verify-pay-file'))->purchase(
            $invoice,
            function($driver, $transactionId) use($tid, $file) {
                $payment = new Payment();
                $payment->amount = $file->price;
                $payment->transaction_id = $transactionId;
                $payment->telegram_user_id = $tid;
                $payment->save();
            }
        )->pay();
 }
```

My callback function:

```php
public function verifyPayFile()
{
       try {
              $receipt = PaymentFacade::amount(XXXXX)->transactionId(XXXXX)->verify();
              echo $receipt->getReferenceId();
       } catch (InvalidPaymentException $exception) {
            echo $exception->getMessage();
       }
}
```
What should be instead of XXXXX in my callback function?

Thanks a lot

**Comment by khanzadimahdi** [comment]
create dynamic callback urls for each payment.
for example:
```php
Route::any('payment/{payment}/verify', 'PaymentsController@verify)

/* exmple urls:
    http://yoursite.com/payments/1/verify
    http://yoursite.com/payments/2/verify
    http://yoursite.com/payments/3/verify
*/
```
then retrieve your invoice (use model binding) and verify it.

you can pass dynamic callback urls using **callbackUrl** method.

**Comment by shdehnavi** [comment]
Than you a lot
so, is this a logical way?
`    Route::get('verify-pay/{paymentId}/file/{fileId}', 'PaymentController@verifyPayFile')->name('bot.verify-pay-file');
`
`public function buyFile($tid, $fid)
    {
        $file = File::findOrFail($fid);
        $telegramUser = TelegramUser::whereId($tid)->get();

        $payment = new Payment();
        $payment->amount = $file->price;
        $payment->telegram_user_id = $tid;
        $payment->save();

        $invoice = new Invoice();
        $invoice->amount($file->price);
        $invoice->detail('description', "خرید فایل {$file->path}")
            ->detail('email', 'info@shdehnavi.ir')
            ->detail('mobile', '09123456789');
        return PaymentFacade::callbackUrl(route('bot.verify-pay-file', ['paymentId' => $payment->id, 'fileId' => $fid]))->purchase(
            $invoice,
            function($driver, $transactionId) use($payment) {
                $updatePayment = Payment::findOrFail($payment->id);
                $updatePayment->transaction_id = $transactionId;
                $updatePayment->save();
            }
        )->pay();
    }

    public function verifyPayFile(Request $request, $paymentId, $fileId)
    {
        $payment = Payment::findOrFail($paymentId);

        try {
            $receipt = PaymentFacade::amount($payment->amount)->transactionId($payment->transaction_id)->verify();
            $payment->authority = $request->input('Authority');
            $payment->ref_id = $receipt->getReferenceId();
            $payment->files()->attach($fileId);
            $payment->save();
            echo 'پرداخت با موفقیت انجام شد'.'<br>'.'کد رهگیری: '.$receipt->getReferenceId();
        } catch (InvalidPaymentException $exception) {
            echo $exception->getMessage();
        }
    }`
