### ISSUE TITLE
shetabit-payment

### ISSUE THREAD

**Issue by amirmms** [shetabit/payment#41]
<div dir=rtl>

سلام من وقتی متد pay رو صدا میزنم این ارور رو میده

Target class [shetabit-payment] does not exist.

</div>

**Comment by amirmms** [comment]
مشکل بالا رفع شد حالا این خطا را میدهد

> ارسال api الزامی می باشد

**Comment by khanzadimahdi** [comment]
سلام میشه بگید مشکل از کجا بود و چجوری رفع شد؟

و اینکه از کدوم درگاه استفاده میکنید؟

همچنین بخشی از کد که ارور میده رو اگه بزارید ممنون میشم

**Comment by amirmms** [comment]
شما باید اون تیکه از آموزشتون که نوشتید اگر از لاراول 5.5 به بالا استفاده میکنید کد های زیر رو نزدید؛ حذف کنید چون من لاراول 6 هست و نیاز داشت کد هارو توی فایل 
app
وارد کنم بدون اون خطا میداد
قبلا داشتم 
payir
رو تست میکردم اوکی بود و درست کار کرد ولی الان دارم زرین پال رو تست میکنم خطای زیر رو داد

`Symfony\Component\Debug\Exception\FatalThrowableError: Class 'SoapClient' not found in file /home/dotapp/public_html/test/core/vendor/shetabit/payment/src/Drivers/Zarinpal/Zarinpal.php on line 65`

**Comment by amirmms** [comment]
توی کلاس زرین پال شما لیست 
use
هاتون به شکل زیر هست
`use Shetabit\Payment\Abstracts\Driver;
use Shetabit\Payment\Exceptions\InvalidPaymentException;
use Shetabit\Payment\Exceptions\PurchaseFailedException;
use Shetabit\Payment\Contracts\ReceiptInterface;
use Shetabit\Payment\Invoice;
use Shetabit\Payment\Receipt;`

و متاسفانه شما 
SoapClient
رو 
import
نکردید برای همین خطا داده

**Comment by amirmms** [comment]
` $client = new \SoapClient($this->getPurchaseUrl(), ['encoding' => 'UTF-8']);`

**Comment by khanzadimahdi** [comment]
<div dir=rtl>

پکیجی که استفاده میکنید چه ورژنی هست؟ احتمال میدم از ورژن های قدیمی تر دارید استفاده میکنید

برای استفاده از زرین پال باید Soap روی سرور شما فعال باشه فایل php.ini  رو بررسی کنید ببینید فعال هست یا نه

</div>

**Comment by amirmms** [comment]
` "shetabit/payment": "^2.2",`

**Comment by khanzadimahdi** [comment]
<div dir=rtl>

ورژن شما اخرین ورژن هست.

مطمئن هستید که Soap فعاله؟


</div>

**Comment by khanzadimahdi** [comment]
اگه هنوز مشکلتون حل نشده در خدمتتون هستم . در صورتی که به این گفتگو ادامه ندید تا 48 ساعت اینده این گفتگو رو میبندم

موفق باشید

**Comment by amirmms** [comment]
کامل درست شد و واقعا متشکرم برای ساخت این پلاگین
♥

**Comment by khanzadimahdi** [comment]
موفق باشید.
