### ISSUE TITLE
‫‪تراکنش های موفقی که به وب سایت ارجاع داده نشده ان

### ISSUE THREAD

**Issue by kazemimorteza68** [shetabit/payment#42]
<div dir=rtl>

وقت بخیر.
در زرین پال 
مشکل من تراکنش های موفقی هست که در سایت ثبت نشده ان چطوری تراکنش ها موفقی که در سایت ثبت نشده ان را پیدا کنم؟؟؟
یعنی تراکنش و پرداخت انجام شده ولی به هر دلیلی کاربر به سایت برنمی گردد. چطور این تراکنش ها را پیدا کنم.
در صورتی که فقط مقدار پرداختی و
$transactionId
  را دارم .
‫
 ‫‪GetUnverifiedTransactions‬‬ ‫متد‬
را پیدا کردم ولی نمیدونم چه جوری ازش استفاه کنم.
با تشکر

</div>

**Comment by khanzadimahdi** [comment]
سلام

تراکنشی که موفق باشه اما از طریق شما verfiy نشده باشه مبلغش به حساب خریدار برمیگرده

بنابراین در صورتی که کاربر به سایت برنگردد پرداخت ناموفق بوده و در هر صورت بانک موظف است تا پول پرداخت شده رو به حساب کاربر برگشت بزنه

داکیومنت های فارسی رو میتونید از لینک زیر پیدا کنید

https://github.com/shetabit/payment/blob/master/README-FA.md

همچنین به نگاه به سوال زیر بندازید

#38

**Comment by kazemimorteza68** [comment]
درود وقت بخیر.
ممنونم بابت پاسخ گویی شما.
مهندس کلا تو هبچ درگاهی نمیشه تراکنش های مرتبط با یک سایت را خواند و بررسی کرد؟
@khanzadimahdi 
من همچین سوالی از زرین پال پرسیدم ولی مثل این که چنین چیزی در زرین پال پیاده نشده.
سوال و جواب را قرار میدم.

> درود .
آیا وقتی کاربر یک خرید را انجام میدهد ولی به وب سایت من بر نگردد .یعنی توسط من وریفای نشود اون پرداخت توسط بانک کنسل شده و مبلغ خریداری شده به حساب کاربر بر می گردد؟
ممنونم

> با سلام و احترام
خیر در زرین پال به این صورت نیست.
ابتدا در زرین پال تایید بعد به سایت شما برمیگردد.
این کار برای عدم از دست رفتن تراکنش های شما می باشد

**Comment by khanzadimahdi** [comment]
<div dir=rtl>

خودتون میتونید تراکنش ها رو ابتدا در دیتابیس ذخیره کنید و بعدش کاربر رو به درگاه مورد نظر انتقال بدید

بعد از اینکه متد purchase رو فراخوانی کردین کد تراکنش مرتبط با پرداخت رو درون دیتابیس ذخیره کنید

</div>

**Comment by kazemimorteza68** [comment]
سلام ممنونم مهندس جان .

من با روال عادی پرداخت مشکلی ندارم. منظورم اینه که اگه شرایط استثنایی پیش بیاد و کاربر بعد از پرداخت موفق نتونه به سایت فروشنده ریدایرکت بشه و پراداخت موفق براش ثبت نشه. با این اوصاف میشه به پورتال یا جایی از بانک وصل شد و پرداخت های مرتبط با سایت خودم را بخونم؟؟

**Comment by khanzadimahdi** [comment]
تاجایی که من میدونم (و درگاه های مستقیم بانک به اینصورت عمل میکنند) در صورتی که کاربر پرداخت رو از هر مرحله ای رها کنه باید مبلغی که پرداخت کرده به حسابش برگشت زده بشه.

اما درگاه های واسط (غیر مستقیم) امکان داره پول رو برنگردونن مثلا زرین پال فرمودین به این صورت هست.
من راهی ندارم که بتونم بهتون ارائه بدم اما در هر صورت میتونید از خود پنل زرین پال لاگین کنید و بررسی کنید. تنها راهش همینه
