### ISSUE TITLE
مشکل در وریفای کردن پرداخت آنلاین درگاه پی پینگ

### ISSUE THREAD

**Issue by h-o-sein** [shetabit/payment#44]
<div dir=rtl>

سلام
درگاه : پی پینگ
Laravel Framework 6.16.0
بعد از رفتن به صفحه پرداخت وقتی کاربر روی گزینه لغو کلیک می کند بعد از این که وریفای انجام می شود به جای این که صفحه تعریف شده را نمایش دهد این صفحه را نمایش می دهد

</div>

![test](https://user-images.githubusercontent.com/9271127/75256653-04f72380-57f9-11ea-81ad-03010df15736.png)

**Comment by khanzadimahdi** [comment]
<div dir=rtl>

سلام. اگه تراکنش verifyنشه یا هرمشکلی داشته باشه یک Exception ایجاد میشه که شما باید اون رو catch کنید و یک صفحه مناسب نشون بدید. مشکل شما این هست که اون exception رو catchنکردین. به مثال ها و داکیومنت ها دقت کنید

</div>

**Comment by khanzadimahdi** [comment]
<div dir=rtl>

در برابر issueایجاد شده پاسخگو باشید. من منتظر هستم تا مشکل شما رو رفع کنم. در صورتی که  طی ۴۸ ساعت اینده پاسخی از شما دریافت نکنم این issue رو میبندم

موفق باشید

</div>

**Comment by h-o-sein** [comment]
تمامی مواردی که گفتید در کد آن در پروژه وجود دارد و همین الان با همین کد ها درگاه زرین پال به خوبی کار می کند و مشکلی ندارد

**Comment by h-o-sein** [comment]
به وجود می آید exception وقتی   catch مشکلی از سمت کد های من وجود ندارد و من در داخل
مثلا می خوام به صفحه داشبورد هدایت بشه اما اصلا به این قسمت ریترن نمیشه و مثل عکس بالا میشه
وقتی هم درگاه را میزارم روی زرین پال همه چیز به خوبی کار می کنه و مشکلی وجود نداره

`try {
Payment::amount($Pay[0]->Amount)->transactionId($FindID)->verify();
...
} catch (InvalidPaymentException $exception) {
...
      return redirect()->route('Dashboard');
}`

**Comment by khanzadimahdi** [comment]
<div dir=rtl>

دوتا سوال دیگه دارم از شما

- فضای نام InvalidPaymentException رو توی صفحه use  کردین؟
- میتونید $exception رو dd کنید ببینید کار میکنه یا نه؟ یا var_dump کنید و بعدش die بزنید

</div>

**Comment by khanzadimahdi** [comment]
دوست عزیز مرسی از پیگیری شما. حرف شما صحیحه. الان باگ رو پیدا کردم و رفع میکنم و ورژن جدید میدم. لطفا ورژن خودتون رو اپدیت کنید با توجه به اخرین ورژنی که الان منتشر میکنم.

مرسی از شما.

**Comment by khanzadimahdi** [comment]
<div dir=rtl>

مشکل رفع شد ورژن v2.2.4 رو نصب کنید. 

چک کنید اگه بازم مشکلی بود اطلاع بدید. مرسی از شما

</div>

**Comment by h-o-sein** [comment]
را بر نمی گردانه InvalidPaymentException الان دوباره چکش که کردم الان کلا
