### ISSUE TITLE
مشکل در وریفای کردن پرداخت آنلاین درگاه پی پینگ

### ISSUE THREAD

**Issue by h-o-sein** [shetabit/payment#45]
<p dir=rtl>امروز داشتم بررسی می کردم که دیدم اصلا InvalidPaymentException را بر نمی گردانه</p>
<p dir=rtl>همچنین اگر پرداخت هم با موفقیت انجام بشه اصلا استاتوسی برگردانده نمیشه</p>

**Comment by h-o-sein** [comment]
مشکل حل شد

**Comment by khanzadimahdi** [comment]
<div dir=rtl>

اکسپشن رو توی صفحه use کنید تا مشکل حل بشه

</div>

**Comment by khanzadimahdi** [comment]
موفق باشید. اگه مشکلی بود در خدمتتون هستم

**Comment by h-o-sein** [comment]
در صفحه هست

**Comment by h-o-sein** [comment]
<p dir=rtl>این کد وقتی اجرا میشه اصلا چه پرداخت موفق باشه چه ناموفق InvalidPaymentException ایجاد نمی کنه</p>
```
try {
	$receipt = Payment::amount(1000)->transactionId($transaction_id)->verify();

    // you can show payment's referenceId to user
    echo $receipt->getReferenceId();    

    ...
} catch (InvalidPaymentException $exception) {
    /**
    	when payment is not verified , it throw an exception.
    	we can catch the excetion to handle invalid payments.
    	getMessage method, returns a suitable message that can be used in user interface.
    **/
    echo $exception->getMessage();
}
```

**Comment by h-o-sein** [comment]
الان دوباره تست کردم کلا پرداخت چه موفق باشه چه ناموفق 
پرداخت را موفق ثبت می کنه

**Comment by h-o-sein** [comment]
توی صفحه همه این ها قرار دارند

```
use Shetabit\Payment\Facade\Payment;
use Shetabit\Payment\Exceptions\InvalidPaymentException;
```

**Comment by khanzadimahdi** [comment]
اگه امکانش هست مشخصات درگاه پی پینگ خودتون رو به شماره زیر در تلگرام ارسال کنید تا باهم صحبت کنیم و مشکل رو رفع کنم

09373620353

من درگاه پی پینگ رو تست کردم مشکلی ندیدم توش! امکان داره مشکلی داشته باشه که از دید من پنهان مونده

ارادتمند شما

**Comment by khanzadimahdi** [comment]
لطفا پیگیری کنید تا مشکل رو باهم رفع کنیم. در غیر اینصورت این ایشو رو میبندم تا ۴۸ ساعت اینده

**Comment by h-o-sein** [comment]
امکانش هست یک پروژه خودتون با لاراول درست کنید بعد برای من ارسال کنید من ببینیم شاید مشکل از کد من باشه

**Comment by khanzadimahdi** [comment]
اوکی خودمم تست میکنم دوباره

**Comment by khanzadimahdi** [comment]
سلام. با توجه به مستندات پی پینگ دوباره درگاه رو بررسی کردم. یکسری تغییرات داشتن که باعث خطا میشد

پکیج خودتون رو اپدیت کنید

یک نمونه کد ساده هم گذاشتم که میتونید روی لوکال تست کنید

[laravel7.0-payment-test.zip](https://github.com/shetabit/payment/files/4335043/laravel7.0-payment-test.zip)

**Comment by khanzadimahdi** [comment]
از پیگیری های شما ممنونم. موفق باشید

**Comment by hadidadkhah** [comment]
سلام. درگاه پی پینگ هنوز مشکل دارد.

**Comment by khanzadimahdi** [comment]
لطفا کدی که نوشتین رو قرار بدید تا بررسی کنم
