### ISSUE TITLE
عدم انتقال به درگاه پرداخت  - ریدایرکت نشدن به درگاه

### ISSUE THREAD

**Issue by kamalgharejeloo** [shetabit/payment#46]
سلام من طبق مثال ها عمل کردم ولی متاسفانه انتقال نمیده به صفحه بانک
کد 301 میده ولی اتفاقی نمیفته

**Comment by khanzadimahdi** [comment]
<div dir=rtl>

سلام. از کدوم درگاه استفاده میکنید؟ ورژن پکیجی که استفاده میکنید چند هست (از فایل کامپوزر نگاه کنید)

</div>

**Comment by kamalgharejeloo** [comment]
"shetabit/payment": "^2.1"

**Comment by kamalgharejeloo** [comment]
توی لوکال هاست برای تست کد تراکنش رو تو دیتایس سیو میکردم و سمت فرانت اند دستی انتقال میدادم
ولی روی هاست اصلا روی دیتابیس هم ذخیره نمیکنه اول کد 301 میده بعدش همون درخواست رو با متد گِت میفرسته
ببخشید یا باید کلا فارسی بنویسم یا انگلیسی جابه جا میشن کلمه ها

**Comment by khanzadimahdi** [comment]
لاراول شما ورژن چند هست؟

ورژن 2.3 پکیج رو نصب کنید

**Comment by kamalgharejeloo** [comment]
لاراول ورژن 5.8

**Comment by khanzadimahdi** [comment]
اخرین ورژن پکیج رو نصب کنید درست میشه همه چیز

**Comment by khanzadimahdi** [comment]
همچنین تنظیمات پکیج رو انجام بدید. کد مرچند خودتون رو ثبت کنید و ادرس برگشت از خرید رو هم قرار بدید. اگه ادرس ها داینامیک هستن از تابع کالبک استفاده کنید

**Comment by kamalgharejeloo** [comment]
متاسفانه همچنان همین مشکل رو دارم

       `use App\Invoice as Invoices;
        use Illuminate\Http\Request;
        use App\Http\Controllers\Controller;
        use Shetabit\Payment\Facade\Payment;
        use Shetabit\Payment\Exceptions\InvalidPaymentException;
         ...
        $invoice = (new Invoice)->amount( $input['cost']);
        $invoice->detail(['course' =>$request['title']]);
         Payment::callbackUrl('http://portal.takinweb.com/verify-invoice')->purchase(
            $invoice,
            function($driver, $transactionId) {
                global $input;
                 $input['transactionId']= $transactionId;
                $result=Invoices::create($input);
            }
        )->pay();`


            `mode' => 'normal', // can be normal, sandbox, zaringate
            'merchantId' => '2a5d9bea-34b3-11ea-xxxxxxxxxx',
            'callbackUrl' => '',
            'description' => 'payment in '.config('app.name'),`

**Comment by khanzadimahdi** [comment]
<div dir="rtl">

شما یه جا اشتباه کردین. شما باید متد پرداخت رو ریترن کنید مثل کد زیر عمل کنید

</div>

```php
return Payment::callbackUrl("http://portal.takinweb.com/verify-invoice")->purchase(
        $invoice,
        function($driver, $transactionId) {
            global $input;
             $input["transactionId"]= $transactionId;
            $result=Invoices::create($input);
        }
    )->pay();
```

<div dir="rtl">

چون return نکردین ریدایرکت نمیشه توی صفحه پرداخت

کمی بیشتر دقت کنید. همین کد دقیقا توی داکیومنت ها موجود بود

موفق باشید

</div>

**Comment by kamalgharejeloo** [comment]
سلام دوباره ممنون از توجهتون ولی من این رو قبلا هم تست کرده بودم و الانم تست کردم باز نشد
چون ریدایرکت نمیشد این return رو حذف کرده بودم تا کلا این ریدایرکت انجام نشه و به جاش کد تراکنش رو return میکردم پایین همین کد و توی انگولار با دستور window ریدایرکت رو انجام میدادم
توی لوکال این کار میکرد ولی روی هاست جواب نمیده

**Comment by khanzadimahdi** [comment]
اگه میخواید سمت فرانت ریدایرکت رو انجام بدید بهتره ادرس رو به سمت فرانت بدید تا با انگولار ریدایرکت کنید. میتونید به صورت زیر عمل کنید

```php
dd($payment->callbackUrl($url)->pay()->getTargetUrl()); // shows the url
```

من کدها رو تست کردم. پکیج مشکلی نداره و به درستی کار میکنه

**Comment by khanzadimahdi** [comment]
من یکبار دیگه کدها رو تست کردم و همه چیز به درستی کار میکنه

فایل تست رو پیوست کردم میتونید تست کنید.

سرور لاراول رو ران کنید بعدش ادرسش رو بزنید اجرا میشه

[laravel7.0-payment-test.zip](https://github.com/shetabit/payment/files/4334967/laravel7.0-payment-test.zip)

**Comment by kamalgharejeloo** [comment]
احتمالا مشکل از کانفیگ هیدر ها باشه
الان وقتی return رو اضافه میکنم توی کنسول به این ارور میخورم

Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://www.zarinpal.com/pg/StartPay/000000000000000000000000000151998385. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing).

**Comment by kamalgharejeloo** [comment]
من چون رست فول نوشتم احتمالا هیدر ها کانفیلیکت میخورن نمیدونم چرا اینطوریه
من از CORS هم استفاده میکنم برای ست کردن orgin ها

**Comment by khanzadimahdi** [comment]
از پکیج زیر استفاده کنید

https://github.com/fruitcake/laravel-cors

**Comment by kamalgharejeloo** [comment]
سلام دوباره ببخشید باز اینجارو باز کردم
من از این پکیجی که شما دادید هم استفاده کردم ولی متاسفانه حل نمیشه که نمیشه
شما به این مشکل Orgin نخوردید تا حالا؟
من توی استک قبل اینکه از شما بپرسم پرسیدم ولی اونجا هم به جوابی نرسیدم
https://stackoverflow.com/questions/60600889/angular-rest-api-http-302-status-error-cross-origin-request-blocked

**Comment by khanzadimahdi** [comment]
لینک زیر رو چک کنید. با یه میدلور میشه مشکل رو حل کرد

https://github.com/khanzadimahdi/ditty/blob/master/app/Http/Middleware/Cors.php

**Comment by kamalgharejeloo** [comment]
کد بالارو که تو استک پرسیدم اگه نگاه کنید من  از این روش استفاده کردم کد شمارم کپی کردم به جای کد خودم ولی باز همون ارور رو میده

این middleware رو من تو قسمت کرنل قسمت protected $middleware ادد کردم
ممکنه از csrf باشه؟

**Comment by khanzadimahdi** [comment]
لینکشو براتون ارسال کردم. توی قسمت کرنل رو برید نگاه کنید خودتون
