### ISSUE TITLE
ریدایرکت نشدن به صفحه پرداخت

### ISSUE THREAD

**Issue by kamalgharejeloo** [shetabit/payment#47]
سلام
من متاسفانه چند روزه با این سر و کله میزنم و هی از این شاخه میپرم به اون شاخه
ولی الان مشکل اصلی رو پیدا کردم مشکل الان اینجاست که توی لوکال هاست انتقال داده میشه به صفحه ی پرداخت ولی روی هاست تو قسمت لوکیشن درخواستی که بر میگرده همون مسیری بر میگرده که خودم فرستاده بودم
اگه از کد ها مشکلی بود نباید تو لوکال هم اجرا میشد
ممکنه از تنظیمات هاست باشه؟
http://takinweb.com/client/Untitled.png

**Comment by khanzadimahdi** [comment]
نمونه کدی که من گذاشتم براتون رو تست کردین روی سرور؟

**Comment by khanzadimahdi** [comment]
این ایشو رو به دلیل عدم پاسخگویی از سمت شما بستم

**Comment by kamalgharejeloo** [comment]
سلام وقت بخیر
ببخشید با تاخیر خیلی زیاد دوباره این ایشو رو باز کردم

من نمونه کد شمارو تست کردم و به درستی ریدایرکت میشه ولی همون کد در کد من کار نمیکنه

من فرانتم انگولاره و از اونجا یک API با متد پست کال میکنم تو اون کنترلری که کال شده این کد رو استفاده کردم

`
    return Payment::callbackUrl("http://portal.takinweb.com/verify-invoice")->purchase(
            $invoice,
            function($driver, $transactionId) {
                global $input;
                $input["transactionId"]= $transactionId;
                Invoices::create($input);
            }
        )->pay();
`
ولی تو نتورک مرورگر وقتی چک میکنم میبینم تو لوکیشن متدم دوباره همون api رو بر میگردونه که خودم فرستادم

اگه براتون مقدوره من سورس کدمو به ایمیلتون بفرستم یه نگاه بندازید خیلی عالی میشه

**Comment by kamalgharejeloo** [comment]
توی لوکال این ارور رو میده 
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://sandbox.zarinpal.com/pg/StartPay/000000000000000000000000000000035767. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing).
ولی تو سرور همون توضیحاتی که بالا دادم

پکیج Fruitcake هم که شما توصیه کردید رو استفاده کردم و دقیق مثل سمپل کد شما تظیمش کردم ولی همچنان این خطارو دارم

**Comment by khanzadimahdi** [comment]
از دستورات ایجکس استفاده میکنید توی پرداخت؟

**Comment by kamalgharejeloo** [comment]
نه ایجکس استفاده نمیکنم
من از رِست فول استفاده میکنم و بک و فرانتم کاملا جدا از همن و فقط ای پی آی کال میکنم
فرانتم از انگولار 8 استفاده میکنم و بک هم از لاراول 7

من کنترلری که مربوط به پرداخته رو از انگولار صدا میکنم فقط و خب طبیعیه که همه چی باید سمت بک اتفاق بیفته

من احتمالم اینه این پکیج تو حالت رست فول درست کار نمیکنه

**Comment by khanzadimahdi** [comment]
امکانش هست با من تماس بگیرید صحبت کنیم راجب مشکلتون؟ شماره تماسم رو این پایین میزارم

09373620353

**Comment by kamalgharejeloo** [comment]
من اینکارو هم انجام دادم ولیی دوباره با 301 بر میگردونه در حالی که من لینکو بر میگردونم

این لینک ای پی آیی هست که من برای پرداخت استفاده میکنم
میتونید این رو تو پست من هم خودتون ببینید

http://portal.takinweb.com/back/Api/invoice/addInvoice
متد پست هستش و با این ورودی ها

{
id:1,
title:"text",
price:"1000",
price_state:"Price"
}

یه توکنم لازم داره که میتونید این رو بدید برای تست
Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiZmUxY2I3YWEyYjk2YWFmZjkxYmJjMDZlMzc5MDExMDQ4MjFjYmMzZGZkN2Q3ZmUzZWZiMmYyYTczMGJlNWQ4MTIyZWIyZGY0YWE1ZTY2NTgiLCJpYXQiOjE1ODYzNDE4NjksIm5iZiI6MTU4NjM0MTg2OSwiZXhwIjoxNjE3ODc3ODY5LCJzdWIiOiIxIiwic2NvcGVzIjpbImFkbWluIl19.iiF43jNVG81QY8Ur3kn2chquCP8TRhE5yA5QbC9iNWOC2veDPJvXJBwYISg1IhNNg65u5hWZQUrvI_qM9IkN3AIZRBuF2eOl9kBmYu7hMVVR8CDnKqHgs-gGOixG9xUVTeP2qEdAWAIZO4iMA0pd-q_qjaIgdGO1hbxBqwx_8B2ENZnSB4PAn9uPfS6lZXNHH_7kOgm8n2GVl5M9fq2NnHzut5NtEudG1OHa-Z2vS2dwABPKWKmfbAIpaqIGzQWnrGHf6iLMyMZLuly5uKihBC643veeHEL33etIX6pyOPLNQbJ68LWlcWfldivgPIiKauNLbXMgMDEUYm6ghdKbzTMww8mJaCsbpZ5x8yQxVaxWVTnXfFfe_hfa-RsO6R6z0Sln0keTGWnN9m-5UeGEr32Z7wRebCG15T8jGbM0FaDTronDmAJzTE8snHjw4FeyNnBwFo02SB5ZvHYEUUpL0yDWQu-9tDJKReNlKxsyDjy2SUmunQB5ukAwsjXxmUH4QB5PdbH1rHy-9gXmeUfERN_QRfHOy7sCyWSys7iurzVn6dPGoyvEjR9XDg7iwJGPROC8eaqW_q5qyydWMa34-8tIVDdvK4Ikwh8ICu0d9htWrYkeKhRCfNx0eizCHaZ99F2dzXTkA0pcrfBCqbZVHC_wNb-yWTQQSHafJ03hnus

**Comment by khanzadimahdi** [comment]
مشکل شما مربوط به پکیج نمیشه و به خاطر کدهای سمت فرانت هست

من این مکالمه رو لاک میکنم.
