### ISSUE TITLE
Simpler api or more control over transaction id

### ISSUE THREAD

**Issue by mokhosh** [shetabit/payment#51]
I see you advise users to use route model binding to find the model that they paid for:
https://github.com/shetabit/payment/issues/38
https://github.com/shetabit/payment/issues/9

This makes `payment.callback_url` obsolete. You can't use static callback urls, you have to use a dynamic one. It would be great if we could somehow use the static url and have a simpler api.

**Comment by khanzadimahdi** [comment]
what's your suggestion for this problem ?

**Comment by mokhosh** [comment]
I think we should be able to get the transaction id from the request and find our model with that.
Exposing the database primary key like that in the url seems very insecure.

**Comment by khanzadimahdi** [comment]
seems very insecure? i don't think so. 
you can sign your urls and set expiration time for it.

we cant inject transaction id to request on callback redirection.

**Comment by khanzadimahdi** [comment]
if you have any solution for this, create a pull request. i will review and merge it.
