### ISSUE TITLE
خطا تایید نشدن وب سرویس ایدی پی (idpay)

### ISSUE THREAD

**Issue by netwons** [shetabit/payment#53]
```
$invoice = (new Invoice)->amount( 1000);
        $invoice->detail(['course' =>'yyy']);
        Payment::callbackUrl('http:://verify')->purchase(
            $invoice,
            function($driver, $transactionId) {
                global $input;
                $input['transactionId']= $transactionId;
                $result=Invoice::create($input);
            }
        )->pay();
```
این ارور رو میده
در صورتی که من از درگاه idpay استفاده میکنم و لاراول من ۶ هست.
> 
> Shetabit\Payment\Exceptions\PurchaseFailedException
> وب سرویس تایید نشده است.

**Comment by khanzadimahdi** [comment]
<div dir=rtl>

وب سرویس شما باید از سمت idpay تایید بشه تا بتونید استفاده کنید.

به پنل idpay خودتون برید و بررسی کنید ببینید تایید شده یا نه؟ اگه تایید نشده تیکت بزنید بررسی کنن

همچنین فایل زیر رو هم بررسی کنید و تنظیمات مرتبط با ایدی پی رو انجام بدید

config/payment.php

مسیر بالا رو توی پروژه خودتون پیدا کنید و بازش کنید به قسمت idpay برید و تنظیمات رو انجام بدید

</div>
