### ISSUE TITLE
Database Structure?

### ISSUE THREAD

**Issue by mrmmg** [shetabit/payment#54]
Hello
Thanks for your helpful package!
Can you give an example of a database structure for this package?

**Comment by khanzadimahdi** [comment]
this package doesn't handle database and storage.
how ever you should store the below information per each payment
- user_id or payer name and email
- transaction_code (on purchase step)
- receipt_code (after verification step)
- amount
- status (unpaid, paid)

you can have single table for payments or 2 tables (one for invoiced and one for payments).
