### ISSUE TITLE
Amount unit isn't equal in all gates

### ISSUE THREAD

**Issue by mshahrokhi** [shetabit/payment#55]
## Detailed description

Payment's amount unit isn't equal in all of the drivers. for example in Zarinpal API amount unis is Toman, but in Payir it's Rial. I use these drivers both, and I have to check the selected gate for payment, then correct the amount based on the selected gate. It's better to fix it in the package.

Thanks a lot

**Comment by khanzadimahdi** [comment]
hi, thanks for your report. i fix it now.

**Comment by khanzadimahdi** [comment]
i have fixed it. now you can use version 2.4.4

change it in `composer.json` and press `composer update`.

thanks for your bug report.

**Comment by mshahrokhi** [comment]
Thanks for the quick reply, 
I think you made a mistake, I told the Zarinpal unit is Toman and it's incorrect when you send Rial amount to its API, then you have to fix Zarinpal driver class, but you changed the Payir driver class and made it incorrect.

Thanks a lot

**Comment by khanzadimahdi** [comment]
in this package, all units must be toman.

which one use rial now?
zarinpal or payir?
i will rollback payir now.

**Comment by mshahrokhi** [comment]
Oh sorry, you are right, I think your package unit is Rial. so it's ok now. (the Payir unit is Rial) 
Thanks.

**Comment by khanzadimahdi** [comment]
hmm :| ok i will do changes again. thanks

**Comment by khanzadimahdi** [comment]
i have done it. update to version 2.4.4.

please create `pull request` if there is any bugs or errors in this package.

thanks.
