### ISSUE TITLE
مشکل transactionId  PayPing

### ISSUE THREAD

**Issue by ShayanSlash** [shetabit/payment#61]
<div dir=rtl>

سلام ، هنگامی که از درگاه پی پینگ میخوام استفاده بکنم .

کد پرداختی که موقع پرداخت میده یک حروف 6 - 7 حرفی هستش ! ( transactionId  )

حالا موقع برگشت مثل بقیه درگاه ها اون کد پرداخت که قبل از وارد شدن به درگاه رو ذخیره کردیم نمیده !

اگر بیرون از پکیج بود میومدم اون کد که اول میده رو مخصوص پی پینگ داخل کال بک برمیگردوندم . اما چون دارم با پکیج کار میکنم کمی گیج شدم !

بنظرتون باید این مورد رو چیکار کنم ؟ ( از 3 درگاه استفاده میکنم و کال بک ها داینامیک هستش )

</div>

**Comment by khanzadimahdi** [comment]
<div dir=rtl>

سلام اگه امکانش هست کد خودتون رو قرار بدید تا بررسی کنم. بعد از پرداخت همیشه کد تراکنش در اختیار شما قرار میگیره

</div>

**Comment by ShayanSlash** [comment]
سلام کد خاص و اضافی ندارم ! از کدهای خود پکیج دارم استفاده میکنم .

` return Payment::callbackUrl(url('/' . $this->userinfo['username'] . '/paymentCheck'))->via($this->request['payGateway'])->config('merchantId', $api)->purchase($this->invoice, function ($driver, $transactionId) {
            $data = array_merge($this->request->all(), ['transactionId' => $transactionId, 'ipAddress' => $this->request->getClientIp(), 'status' => 'Send', 'user_id' => $this->userinfo['id']]);
            Pay::create($data);
        })->pay();`

$transactionId که ساخته میشه برای درگاه پی پینگ به این صورت هستش : 

3d111c یا a7cfb4

کلاً 5 6 رقمی هستن ! البته شکی هم دارم چون روی تست داره انجام میشه شاید پی پینگ 5 6 رقمی بر میگردونه اما درگاه های زرین پال و ایدی پی اوکی هستند !

با همین کد بالا که ارسال کردم تمام درگاه ها وصل میشم ! درگاهی که کاربر انتخاب کرده رو میگیرم و 
via() رو تغییر میدم

**Comment by khanzadimahdi** [comment]
موقع ارسال کاربر به درگاه باید کد تراکنش رو درون دیتابیس یا سشن ذخیره کنید.

موقع برگشت کاربر از درگاه کدی که به شما داده میشه رسید پرداخت کاربر هست و صرفا یه کدی هست که به کاربر نشون بدید که اونم باید توی دیتابیس یا سشن قرار بدید

بعد از تموم شدن کارها سشن رو پاک کنید و اطاعات مورد نیاز رو به کاربر نشون بدید یا ثبت کنید توی دیتابیس

**Comment by khanzadimahdi** [comment]
نیازی نیست که واسه هر درگاه یه کد خاص بنویسید. اطلاعاتی که بهتون داده میشه همه صحیح هست و کدی که الان نوشتید هم کاملا درسته

**Comment by khanzadimahdi** [comment]
اما اگه میخواید همه اطلاعات رو داشته باشید توی هر مرحله هر اطلاعاتی که بهتون داده میشه رو توی دیتابیس یا سشن ثبت کنید که بعدا میتونید بهش دسترسی داشته باشید

**Comment by Hesammousavi** [comment]
hey dude there is a bug or at least i think it's a bug
look if u use payping for your payments, you probably must use this code
```
Payment::purchase($invoice,function($driver, $transactionId) {
	// We can store $transactionId in database.
})->pay()->render();
```
so as you mentioned `We can store $transactionId in database.` and i suppose to use it for verify .
but we can't . cuz at the end we get `invoice uuid` from the bank not transactionId that we stored.
so i will pleased you help me figure out about it

**Comment by khanzadimahdi** [comment]
@Hesammousavi 
Hi. at the end we get invoice uuid ? you mean after puchasing we get uuid instead of transactionId? i cant understand what you mean!!!! could you explain what's wrong with the package?

**Comment by Hesammousavi** [comment]
you get transactionId and you must store it for pay verify in next step , is it right ? 
so the bank (payping) return invoice uuid to callback instead transactionId to us

**Comment by khanzadimahdi** [comment]
@Hesammousavi 

yes that's right.

transactionId is an abstract concept. it is the transaction's unique identifier.
we need such an identifier to specify which transaction we want to be paid or verified.

you must save the transactions unique identifier (transaction id) for future. it lets you to trace which transaction has paid or failed.

please check the codes in the below file

https://github.com/shetabit/multipay/blob/master/src/Drivers/Payping/Payping.php

see line *12* and *143*

using transactionId in verification step is optional in all gateways.

we need a same standard (abstraction) for all gateways. in some gateways transactionId is useless in verification step, however as we need same abstraction for all gateways , i have made using transactionId, in purchase step, optional for all gateways. if you pass transactionId to purchase method, the gateway will use either the given transactionId or the one is exists in the bank redirect back request.

https://github.com/shetabit/multipay/pull/7/commits/17e6def5e115799435dd75f736d43d429a0e68da

thanks for your pull request.
