### ISSUE TITLE
add "AdditionalData" Fields to Saman Driver RequestToken method.

### ISSUE THREAD

**Issue by armin1853** [shetabit/payment#65]
## Detailed description

as mentioned in https://www.sep.ir/Data/Sites/1/media/token98.pdf , saman RequestToken method can accept additional data. 
in fact : 

this : 
$response = $soap->RequestToken($data['MID'], $data['ResNum'], $data['Amount']);

should be changed to something Like This :

$response = $soap->RequestToken($data['MID'], $data['ResNum'], $data['Amount'], 0, 0, 0, 0, 0, 0, $data['AdditionalData1'], $data['AdditionalData2'], $data['wage']);

**Comment by khanzadimahdi** [comment]
please create pull request for this functionality.

I close this issue.
