### ISSUE TITLE
auto logout in laravel v7

### ISSUE THREAD

**Issue by erfanhemmati** [shetabit/payment#66]
@khanzadimahdi 
مشکل اتو لاگ‌اوت بعد از برگشت از درگاه بانکی به روت از نوع پست مشاهده میگردد.
laravel v7

**Comment by khanzadimahdi** [comment]
<div dir="rtl">

پکیج ربطی به لاگ اوت کردن توی سیستم نداره و کلا با سشن کار نمیکنه پس لاگ اوت شدن توی سیستم شما مشکل از کدهای دیگری هست که نوشتین

</div>

**Comment by MadMEMb55** [comment]
سلام 
در هنگام استفاده از درگاه سامان به همین مشکل برخورد کردم که درخواست به درستی از بانک برمیگرده و دقیقاً وقتی به وریفای میرسه کاربر لوگ اوت میشه
`
 $order = order::findorfail($id);
        $invoice = $order->invoices()->latest()->first();
        try {
            $receipt = Payment::amount(intval($invoice->amount))->transactionId($invoice->transactionId)->verify();
            //insert to pays
        } catch (InvalidPaymentException $exception) {
            return redirect()->route('Order.showpay2', ['id' => $order->id])
                ->with('status', $exception->getMessage());
        }
`

**Comment by erfanhemmati** [comment]
@MadMEMb55 
@khanzadimahdi 
اره دقیقا. وریفایش اوکی از سمت بانک. ولی یوزر رو همچنان لاگ اوت میکنه

**Comment by khanzadimahdi** [comment]
لاگ اوت شدن مربوط به پکیج نیست

پکیج هیچ دسترسی به سشن نداره و کلا با سشن کار نمیکنه

**Comment by MadMEMb55** [comment]
بله منم حرف شما رو تایید میکنم ولی یه جایی توی verify مشکل پیش میاد که مربوطه به پکیجه
اگه خواستید شماره بدید تا دسترسی بهتون بدم خودتون چک کنید

**Comment by khanzadimahdi** [comment]
@MadMEMb55 

نیاز به دسترسی نیست. اگه حس میکنید مشکلی هست پکیج رو فورک کنید و تغییراتی که نیازه رو انجام بدید و درخواست مرج بدید

**Comment by MadMEMb55** [comment]
> @MadMEMb55
> 
> نیاز به دسترسی نیست. اگه حس میکنید مشکلی هست پکیج رو فورک کنید و تغییراتی که نیازه رو انجام بدید و درخواست مرج بدید

من چک کردم و مشکل از خط زیر توی تابع notVerified میاد که دقیقاً همه چیز اوکیه و کار میکنه ولی وقتی به خط زیر میرسه سشن هارو پاک میکنه
`            throw new InvalidPaymentException($translations[$status]);
`

**Comment by khanzadimahdi** [comment]
شما باید اکسپشن رو مدیریت کنید

همچنین هیچوقت نباید لینک برگشت از درگاه نیاز به لاگین بودن داشته باشه چون ممکنه بنا به هر دلیلی کاربر موقع برگشت از درگاه لاگین نباشه

**Comment by MadMEMb55** [comment]
آقا من بالاخره پروژه رو تموم کردم و رسیدم به اینکه هر طور شده این مشکل برطرف بشه و دیروز یه سری دیگه از اول پکیج رو نصب کردم و این مشکل رو چک کردم
اول از همه بگم که ساختار پکیج یکم عوض شده پس اگه مثل من قبلاً پکیج رو داشتید حتماً حذفش کنید و دوباره نصبش کنید و بعد از نصب دوباره فایل کانفیگ جدیدش رو پابلیش کنید
خب بریم سراغ مشکل
اول از همه که من اومدم و روت برگشتی خودم رو توی استثناء های csrf قرار دادم 
تا اینجا همه چیز اوکی بود ولی مشکل از جایی شروع میشد که موقع برگشت درخواست با تایپ پست چون اطلاعات کاربری و توکن لاراول توی اون درخواست نبود به صورت اتوماتیک از اکانت خارج میکرد کاربر
پس تصمیم گرفتم یه روت جدید برای برگشت پرداخت هام اضافه کنم (تو این پروژه من چند حالت پرداخت داشتم از شارژ و کالا و بسته گرفته تا اشتراک)
روت جدید رو ساختم و دقیقاً همون محدودیت های روت وب رو براش گذاشتم فقط اومدم و csrf رو حذف کردم
ولی بازم مشکل پا برجا بود بعدش همه محدودیت هارو از فایل کرنل حذف کردم برای این روت جدید و حالا همه چیز اوکی بود و به درستی کار میکرد
گفتم از دوستان اگه کسی این مشکل براش پیش اومده مثل من شاید به دردش بخوره
به نظرم بد نیست این نکته توی داکیومنت پکیج هم ذکر بشه

**Comment by khanzadimahdi** [comment]
از توضیحات شما متشکرم. پس مشخص شد این موردی که گزارش شده ربطی به پکیج نداره 

دم شما گرم. موفق باشید

**Comment by amousavii** [comment]
دوستان منم دقیقا این مشکل رو دارم.
ممنون میشم راهنمایی بفرمایید که چه مواردی باید ادیت کنم تو تنظیمات که کاربر رو لاگ اوت نکنه

**Comment by khanzadimahdi** [comment]
این مورد مشکل از پکیج نیست و ربطی به پکیج نداره

لطفا یکبار از مرورگر کروم و یکبار هم از مازیلا فایرفاکس استفاده کنید و نتیجه رو اعلام کنید
