### ISSUE TITLE
با نسخه php من مشکل داره کلا 

### ISSUE THREAD

**Issue by amir94rp** [shetabit/payment#67]
Package shetabit/payment at version  has a PHP requirement incompatible with your PHP version (7.1.30)
چرا باید همچین مشکلی داشته باشه آخه؟

**Comment by khanzadimahdi** [comment]
<div dir=rtl>

مشخصه دیگه! گفته ورژن php شما پایینه! باید بالاتر از ۷٫۲ باشه تا بتونی از پکیج استفاده کنی

</div>

**Comment by khanzadimahdi** [comment]
update your PHP version to 7.2+
