### ISSUE TITLE
مشکل ثبت پرداخت

### ISSUE THREAD

**Issue by shahinsta** [shetabit/payment#7]
سلام

من برای تست در داخل روت کد های شمارو وارد کردم و در کانفیگ هم تنظیمات اوکی کردم. .

اما متاسفانه این قسمت را پیدا نمیکند
Payment::purchase
و خطای زیر را می دهد
```php
Symfony \ Component \ Debug \ Exception \ FatalThrowableError (E_ERROR)
Class 'Shetabit\Payment\Facade\Payment' not found
```
ممنون میشم کمک کنید یا نمونه پروژه ای که قبلا از این درگاه استفاده کرده را قرار دهید.

```php
use Shetabit\Payment\Exceptions\InvalidPaymentException;
use Shetabit\Payment\Facade\Payment;
use Shetabit\Payment\Invoice;

Route::get('/pay', function () {
    return Payment::purchase(
        (new Invoice)->amount(1000),
        function ($driver, $transactionId) {
            // store transactionId in database.
            // we need the transactionId to verify payment in future
        }
    )->pay();
});

Route::any('/verify', function ($transaction_id = 1) {
    try {
        Payment::amount(1000)->transactionId($transaction_id)->verify();

    } catch (InvalidPaymentException $exception) {
        /**
         * when payment is not verified , it throw an exception.
         * we can catch the excetion to handle invalid payments.
         * getMessage method, returns a suitable message that can be used in user interface.
         **/
        echo $exception->getMessage();
    }
});
```

**Comment by khanzadimahdi** [comment]
سلام مراحل نصب رو به درستی انجام دادین؟ مثل اینکه مراحل نصب به درستی انجام نشده

**Comment by khanzadimahdi** [comment]
open `config/app.php` and put the below configs in it:
```php
# In your providers array.
'providers' => [
    Shetabit\Payment\Provider\PaymentServiceProvider::class,
],
# In your aliases array.
'aliases' => [
    'Payment' => Shetabit\Payment\Facade\Payment::class,
]
```

**Comment by shahinsta** [comment]
اخه نوشتید برای لاراول 5.5 به بالا نیاز نیست این دو خط دستی  اد بشه

**Comment by khanzadimahdi** [comment]
بعله درسته. اما مثل اینکه کامپوزر شما نتونسته اوتو لود کنه برای همین این دو خط رو اظافه کنید و دوباره تست کنید

**Comment by shahinsta** [comment]
الان از اول نصب کردم و این خطا میده
Symfony \ Component \ Debug \ Exception \ FatalThrowableError(E_ERROR)
Class 'Shetabit\Payment\Provider\PaymentServiceProvider' not found

**Comment by khanzadimahdi** [comment]
فایل `config/app.php` رو باز کنید و دستورات زیر رو اظافه کنید
```php
# In your providers array.
'providers' => [
    Shetabit\Payment\Provider\PaymentServiceProvider::class,
],
# In your aliases array.
'aliases' => [
    'Payment' => Shetabit\Payment\Facade\Payment::class,
]
```

**Comment by shahinsta** [comment]
باید خیلی تشکر کنم که صبورانه دارید جواب میدید به من. ممنونم ازتون.
* اینارو اد کردم و این خطا میده باز :(
============
کل کاری که کردم
1- composer require shetabit/payment
2-

# In your providers array.'providers' => [    ...
Shetabit\Payment\Provider\PaymentServiceProvider::class,],# In your
aliases array.'aliases' => [    ...    'Payment' =>
Shetabit\Payment\Facade\Payment::class,],


3- php artisan vendor:publish

4- ساخت روت که برایتون توایمل اول فرستادم

<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use Shetabit\Payment\Exceptions\InvalidPaymentException;
use Shetabit\Payment\Facade\Payment;
use Shetabit\Payment\Invoice;

Route::get('/', function () {
    return view('welcome');
});

Route::get('/pay', function () {
    return Payment::purchase(
        (new Invoice)->amount(1000),
        function ($driver, $transactionId) {
            // store transactionId in database.
            // we need the transactionId to verify payment in future
        }
    )->pay();
});

Route::any('/verify', function ($transaction_id = 1) {
    try {
        Payment::amount(1000)->transactionId($transaction_id)->verify();

    } catch (InvalidPaymentException $exception) {
        /**
         * when payment is not verified , it throw an exception.
         * we can catch the excetion to handle invalid payments.
         * getMessage method, returns a suitable message that can be
used in user interface.
         **/
        echo $exception->getMessage();
    }
});

**Comment by khanzadimahdi** [comment]
خطایی که میده چیه؟ میشه ارسالش کنید؟

**Comment by shahinsta** [comment]
[image: Untitled.png]

**Comment by khanzadimahdi** [comment]
لطفا از گیتهاب لاگین کنید. تصویر پیوست شده دیده نمیشه چون با ایمیل پاسخ میدین

**Comment by shahinsta** [comment]
Symfony \ Component \ Debug \ Exception \ FatalThrowableError (E_ERROR)
Class 'Shetabit\Payment\Provider\PaymentServiceProvider' not found

**Comment by shahinsta** [comment]
C:\xampp\htdocs\zarinpal\vendor\laravel\framework\src\Illuminate\Foundation\ProviderRepository.php
        if (! is_writable(dirname($this->manifestPath))) {
            throw new Exception('The bootstrap/cache directory must be present and writable.');
        }
 
        $this->files->put(
            $this->manifestPath, '<?php return '.var_export($manifest, true).';'
        );
 
        return array_merge(['when' => []], $manifest);
    }
 
    /**
     * Create a new provider instance.
     *
     * @param  string  $provider
     * @return \Illuminate\Support\ServiceProvider
     */
    public function createProvider($provider)
    {
        return new $provider($this->app);
    }
}
 
Arguments
"Class 'Shetabit\Payment\Provider\PaymentServiceProvider' not found"

**Comment by shahinsta** [comment]
الان اون مشکل حل شد. خطا زیر را داره میده
cURL error 77: error setting certificate verify locations: CAfile: C:\xampp\apache\bin\curl-ca-bundle.crt CApath: none (see http://curl.haxx.se/libcurl/c/libcurl-errors.html)

**Comment by shahinsta** [comment]
C:\xampp\htdocs\shetabit\vendor\guzzlehttp\guzzle\src\Handler\CurlFactory.php
                    'An error was encountered during the on_headers event',
                    $easy->request,
                    $easy->response,
                    $easy->onHeadersException,
                    $ctx
                )
            );
        }
 
        $message = sprintf(
            'cURL error %s: %s (%s)',
            $ctx['errno'],
            $ctx['error'],
            'see http://curl.haxx.se/libcurl/c/libcurl-errors.html'
        );
 
        // Create a connection exception if it was a specific error code.
        $error = isset($connectionErrors[$easy->errno])
            ? new ConnectException($message, $easy->request, null, $ctx)
            : new RequestException($message, $easy->request, $easy->response, null, $ctx);
 
        return \GuzzleHttp\Promise\rejection_for($error);
    }
 
    private function getDefaultConf(EasyHandle $easy)
    {
        $conf = [
            '_headers'             => $easy->request->getHeaders(),
            CURLOPT_CUSTOMREQUEST  => $easy->request->getMethod(),
            CURLOPT_URL            => (string) $easy->request->getUri()->withFragment(''),
            CURLOPT_RETURNTRANSFER => false,
            CURLOPT_HEADER         => false,
            CURLOPT_CONNECTTIMEOUT => 150,
        ];
 
        if (defined('CURLOPT_PROTOCOLS')) {
            $conf[CURLOPT_PROTOCOLS] = CURLPROTO_HTTP | CURLPROTO_HTTPS;
        }
 
        $version = $easy->request->getProtocolVersion();
Arguments
"""
cURL error 77: error setting certificate verify locations:
  CAfile: C:\xampp\apache\bin\curl-ca-bundle.crt
  CApath: none (see http://curl.haxx.se/libcurl/c/libcurl-errors.html)
"""

**Comment by khanzadimahdi** [comment]
کد های خودتون رو به صورت زیر بنویسید
```php
Route::get('pay',function(){
    return \Shetabit\Payment\Facade\Payment::purchase(
        (new \Shetabit\Payment\Invoice())->amount(100),
        function($driver, $transactionId) {
            // store transactionId in database.
            // we need the transactionId to verify payment in future
        }
    )->pay();
});
```
درون روتر جای مناسبی برای افزودن فضای نام نیست

**Comment by khanzadimahdi** [comment]
مشکل شما به پکیج مربوط نمیشه. لینک زیر رو مطالعه کنید و تنظیمات رو انجام بدید

https://stackoverflow.com/questions/24611640/curl-60-ssl-certificate-unable-to-get-local-issuer-certificate

**Comment by shahinsta** [comment]
ممنونم بابت راهنمایی خوبتون

**Comment by shahinsta** [comment]
سلام
من مشکل قبلیمو که مربوط به کیورل بود را حل کردم و وارد درگاه پرداخت شدم و پرداخت هم با موفقیت انجام شد.
من به کالبکم یه لینک دادم که وقتی پرداخت انجام شد به همون لینک انتقال داده شد ولی یه خطایی به من داد که ممنون میشم راهنمایی کنید.

Client error: `POST https://www.zarinpal.com/pg/rest/WebGate/PaymentVerification.json` resulted in a `404 Not Found` response:
{"Status":-11,"Authority":"","errors":{"Authority":["The authority must be 36 characters."]}}

**Comment by khanzadimahdi** [comment]
شما باید توکنی که موقع پرداخت تولید میشه و در اختیارتون قرار میگیره رو موقع وریفای کردن استفاده کنید و ارسال کنید.

**Comment by shahinsta** [comment]
url callback = http://localhost:8000/verify?Authority=000000000000000000000000000111601179&Status=OK
======================================
منظور شما این که تو این خط از get 
بگیرم بذارم تو فانکشن verify?
مثل خط پایین
 Payment::amount(1000)->transactionId($transaction_id)->verify($_GET['Authority']);
************************************
من بصورت موقت تو روت گذاشتم تا کامل اوکی بشه

Route::get('/pay', function () {
    return Payment::purchase(
        (new Invoice)->amount(1000),
        function ($driver, $transactionId) {
            // store transactionId in database.
            // we need the transactionId to verify payment in future
        }
    )->pay();
});

Route::any('/verify', function ($transaction_id = 1) {
    try {
        Payment::amount(1000)->transactionId($transaction_id)->verify();

    } catch (InvalidPaymentException $exception) {
        /**
         * when payment is not verified , it throw an exception.
         * we can catch the excetion to handle invalid payments.
         * getMessage method, returns a suitable message that can be used in user interface.
         **/
        echo $exception->getMessage();
    }
});

**Comment by shahinsta** [comment]
در ضمن پس از اینکه اوکی شد من چه تیبل هایی باید داشته باشم برای ذخیره اطلاعات و فیلدهایی؟

ممنون میشم راهنمایی کنید چون نمونه ای اینجوری نداشتم تا حلا

**Comment by khanzadimahdi** [comment]
در صورتی که مشکلی در رابطه با پکیج دارید ذکر کنید تا رفع بشه. در غیر این صورت مواردی که پیش میاد براتون رو میتونید از فروم ها یا مکان های پرسش و پاسخ مطرح کنید مثلا سایت زیر

roocket.ir
موفق باشید.
