### ISSUE TITLE
Class 'SoapClient' not found

### ISSUE THREAD

**Issue by asadghazanfary** [shetabit/payment#71]
سلام

موقع تست درگاه تو محیط لوکال با همچین پیغامی روبرو میشم:

> Class 'SoapClient' not found

"shetabit/payment": "^2.4",
"laravel/framework": "^7.0",

ممنون میشم راهنمایم کنید @khanzadimahdi

**Comment by khanzadimahdi** [comment]
<div dir=rtl>
روی سرور شما باید Soap فعال باشه. 
این خطا به دلیل فعال نبودن Soap به وجود امده
</div>
