### ISSUE TITLE
Trying to access array offset on value of type null

### ISSUE THREAD

**Issue by mostafafallahi** [shetabit/payment#73]
سلام . خسته نباشید ببخشید این کد منه  
```
$invoice = (new Invoice)->amount($amount);

        return Payment::callbackUrl(route('cart.verify'))->purchase(
            $invoice,
            function($driver, $transactionId) use($cart,$request) {
                $cart->update(['transaction_id'=>$transactionId,'amount'=> $amount ]);
            }
        )->pay();
```
ولی ارور 
Trying to access array offset on value of type null 
میده در صورتی فایل کانفیگ هم مشکلی نداره 
![1](https://user-images.githubusercontent.com/47119773/82758213-66c82900-9dfa-11ea-9fad-c42d3fc49456.PNG)
![2](https://user-images.githubusercontent.com/47119773/82758216-67f95600-9dfa-11ea-81c0-c76b006904c7.PNG)
مشکلش چیه ؟

**Comment by khanzadimahdi** [comment]
<div dir="rtl">

سلام خسته نباشید. فایل کانفیگ رو پابلیش کردین؟ 

```php
php artisan vendor:publish
```

</div>

**Comment by mostafafallahi** [comment]
اره درواقع 
`php artisan vendor:publish --all`
کردم

**Comment by khanzadimahdi** [comment]
<div dir="rtl">

فایلی با نام payment.php توی پوشه config دارین؟

و اینکه ورژن php و laravel شما چند هست؟

</div>

**Comment by mostafafallahi** [comment]
اره فایل
 payment.php 
ایجاد شده و 
merchantId 
هم ست کردم و دیفالت هم روی درایور زرینپال هست 
پی اچ پی ورژن 7.2.5 و لاراول ورژن 7.0

**Comment by khanzadimahdi** [comment]
<div dir="rtl">

 توی اون فایلی که عکس گرفتین و خطا داده میتونید زیر خطر ۶۲ کد زیر رو بنویسید و خروجی رو ببینید چیه؟

</div>

```php
dd($this->config);
```

**Comment by mostafafallahi** [comment]
null هست

**Comment by khanzadimahdi** [comment]
<div dir="rtl">
نباید به این صورت باشه حتما مشکلی وجود داره

میشه توی config/app.php تنظیمات زیر رو اعمال کنید و دوباره تست کنید؟

</div>

```php
// In your providers array.
'providers' => [
    ...
    Shetabit\Payment\Provider\PaymentServiceProvider::class,
],

// In your aliases array.
'aliases' => [
    ...
    'Payment' => Shetabit\Payment\Facade\Payment::class,
],
```

**Comment by mostafafallahi** [comment]
اقا ممنون کش رو خالی کردم و دوباره تست کردم درست شد تشکر

**Comment by khanzadimahdi** [comment]
<div dir="rtl">
بعله حدس میزدم از کش باشه خواستم اولش مطمئن بشم

ممنون از همکاریتون و پیگیری که داشتین. موفق و پیروز باشید.
</div>

**Comment by mehransdt** [comment]
سلام. من هم مشکل مشابه دارم و همین ارور را دارم
PHP 7.4.3
Laravel 7.19

مواردی که در بالا گفته شده بود همه چک شد و انجام شد ولی مشکل همچنان وجود داره.
 Trying to access array offset on value of type null
![Screenshot from 2020-12-19 21-09-12](https://user-images.githubusercontent.com/40128480/102695833-19505500-423f-11eb-9a4d-8488ab506319.png)

**Comment by mehransdt** [comment]
dd($body);

null

**Comment by khanzadimahdi** [comment]
@mehransdt 

کانفیگ رو پابلیش کنید و کش کانفیگ رو پاک کنید. مشکل شما به این دلیل هست که کانفیگ رو پیدا نمیکنه

**Comment by mehransdt** [comment]
متاسفانه همچنان ارور وجود داره. تمامی کش ها هم پاک شد.
پابلیش هم انجام شد

@khanzadimahdi

**Comment by khanzadimahdi** [comment]
نمونه کد زیر رو دانلود کنید و تست کنید

https://github.com/shetabit/payment/issues/101#issuecomment-694091114
