### ISSUE TITLE
استفاده از invoiceverifiedevent

### ISSUE THREAD

**Issue by MeysamFallah** [shetabit/payment#74]
<div dir="rtl">

خواستم از ایونت وریفای استفاده کنم اما توی try وریفای، وقتی این ایونت رو صدا میزنم خطا میده که باید ۳تا پارامتر بهش ارسال کنم، هرچی هم از صورتحساب بهش پاس میدم قبول نمیکنه.
درصورت امکان یک مثال برای بنده بفرستید.
پکیج عالیه و داره کار میکنه فقط با این قسمت ایونت مشکل دارم.

</div>

**Comment by khanzadimahdi** [comment]
<div dir="rtl">

سلام. اگه دقت کنید موقعی که ایونت رو میخواید صدا بزنید سه تا مقدار لازمه که بهش پاس داده بشه که به صورت زیر هست

</div>

```php
public function __construct(ReceiptInterface $receipt, DriverInterface $driver, Invoice $invoice)
{
    $this->receipt = $receipt;
    $this->driver = $driver;
    $this->invoice = $invoice;
}
```

<div dir="rtl">

اولین مقدارش رسیدپرداختی هست. دومین مقدارش درایور یا درگاه هست و سومین مقدار هم صورتحساب هست

**نکته ای که باید بدونید این هست که شما نیاز ندارید event رو صدا بزنید! بلکه خودش اتوماتیک صدا زده میشه! شما فقط باید یک Listener بسازید و به این Event گوش بدید! موقعی که ایونت ایجاد بشه شما توی Listener میتونید به مقادیری که در بالا ست شده دسترسی داشته باشید.**
</div>

**Comment by MeysamFallah** [comment]
کد زیر Listener من است که نوشتم.
به گفته شما توی وریفای دیگه فایر نمی کنم. اما باز هیچ اتفاقی نمی افته.
`<?php

namespace App\Listeners\InvoiceVerified;

use App\Smsapi;
use Illuminate\Contracts\Queue\ShouldQueue;
use Illuminate\Queue\InteractsWithQueue;
use Shetabit\Payment\Events\InvoiceVerifiedEvent;

class SendSMSInvoiceVerifiedNotification
{
    /**
     * Create the event listener.
     *
     * @return void
     */
    public function __construct()
    {
        //
    }

    /**
     * Handle the event.
     *
     * @param  object  $event
     * @return void
     */
    public function handle(InvoiceVerifiedEvent $event)
    {
      $smsUser = new Smsapi();
      $smsUser->sendUserPayVerifiedSMS($event->invoice->getAmount(),$event->receipt->getDate());
      return;
    }
}
`
