### ISSUE TITLE
عدم اتصال به درگاه سداد

### ISSUE THREAD

**Issue by mratwan** [shetabit/payment#75]
به درگاه سداد وصل نمیشه و با اینکه کد 0 رو بر میگردونه اما ظاهرا body خالیه!

production.ERROR: دسترسی به صفحه مورد نظر امکان پذیر نمی باشد. (Shetabit\\Payment\\Exceptions\\PurchaseFailedException(code: 0): دسترسی به صفحه مورد نظر امکان پذیر نمی باشد. at /xxxxx/vendor/shetabit/payment/src/Drivers/Sadad/Sadad.php:94

**Comment by khanzadimahdi** [comment]
درگاه رو روی سروری که ایپی برای اون تنظیم شده تست کردین؟

**Comment by khanzadimahdi** [comment]
<div dir="rtl">
درگاه تست شده هست و باید درست کار کنه. لطفا بررسی های زیر رو یکبار انجام بدید و تست کنید ببینید بازم مشکلی هست یا نه

- درگاه تنها روی سروی که به بانک معرفی شده و روی همان ایپی کار میکنه
- تنظیمات درگاه رو بررسی کنید
- کش لاراول خودتون مخصوصا کش مربوط به کانفیگ رو خالی کنید

ورژن لاراول خودتون + ورژن php و ورژن پکیجی که استفاده میکنید رو لطفا درج کنید

</div>

**Comment by khanzadimahdi** [comment]
لطفا  مشکل رو بررسی کنید. در غیر اینصورت این issue رو تا 48 ساعت دیگه میبندم

**Comment by mratwan** [comment]
بله ، درگاه تست شده و هیچ مشکلی با ایپی و ورژن فعلی php نداره

چندین بار اطلاعات درگاه در تنظیمات چک شده و هیچ مشکلی نداشت
لاراول 7 - php 7.3

**Comment by khanzadimahdi** [comment]
<div dir="rtl">

کدهای درگاه  رو میتونید توی پوشه drivers پیدا کنید. من تست کردم مشکلی وجود نداشت اگه براتون مقدور هست کدها رو بررسی و فیکس کنید و مشکل رو رفع کنید و درخواست مرج بدید.

</div>

**Comment by khanzadimahdi** [comment]
<div dir="rtl">

لطفا این Issue رو پیگیری کنید تا مشکل رفع بشه. در غیر اینصورت  اونو میبندم. موفق باشید

</div>

**Comment by Daniyal-Javani** [comment]
سلام
من دو روز وقت گذاشتم به جایی نرسیدم
با گازل اینطوری میزنه و خطای ۵۰۰ میگیره
```
*   Trying 185.203.160.31...
--
  | * TCP_NODELAY set
  | * Connected to sadad.shaparak.ir (185.203.160.31) port 443 (#0)
  | * ALPN, offering http/1.1
  | * successfully set certificate verify locations:
  | *   CAfile: /etc/ssl/certs/ca-certificates.crt
  | CApath: /etc/ssl/certs
  | * SSL connection using TLSv1.2 / ECDHE-RSA-AES256-GCM-SHA384
  | * ALPN, server accepted to use http/1.1
  | * Server certificate:
  | *  subject: C=IR; O=Shaparak Electronic Card Payment Network Co. (PJS); OU=INFOSEC DEPARTMENT; L=Tehran; ST=Tehran; street=No.14,2nd St., Shah Nazari St., Madar Sq.; postalCode=1547914811; jurisdictionC=IR; jurisdictionL=Tehran; jurisdictionST=Tehran; serialNumber=10320718470; businessCategory=Private Organization; CN=sadad.shaparak.ir
  | *  start date: Jun 18 11:52:41 2019 GMT
  | *  expire date: Jun 17 11:52:41 2021 GMT
  | *  subjectAltName: host "sadad.shaparak.ir" matched cert's "sadad.shaparak.ir"
  | *  issuer: C=PL; O=Unizeto Technologies S.A.; OU=Certum Certification Authority; CN=Certum Extended Validation CA SHA2
  | *  SSL certificate verify ok.
  | > POST /vpg/api/v0/Request/PaymentRequest HTTP/1.1
  | Host: sadad.shaparak.ir
  | User-Agent: GuzzleHttp/6.5.4 curl/7.58.0 PHP/7.4.7
  | Content-Type: application/json
  | Content-Length: 249
  |  
  | * upload completely sent off: 249 out of 249 bytes
  | < HTTP/1.1 500 Internal Server Error
  | < Content-Length: 28659
  | < Content-Type: text/html
  | <
  | * Connection #0 to host sadad.shaparak.ir left intact
```
بعد با کرل میزنه و خروجی اینطوری میگیره
```



string(143) "POST /vpg/api/v0/Request/PaymentRequest HTTP/1.1
  | Host: sadad.shaparak.ir
  | Accept: */*
  | Content-Type: application/json
  | Content-Length: 227
  |  
  | "
  | object(stdClass)#1 (3) {
  | ["ResCode"]=>
  | string(1) "0"
  | ["Token"]=>
  | string(52) "*******************************"
  | ["Description"]=>
  | string(46) "عملیات با موفقیت انجام شد"
  | }

```
به نظرت چکار کنم؟
پی آر با کرل بزنم؟
یا چیزی به ذهنت میرسه تست کنم؟

**Comment by khanzadimahdi** [comment]
@Daniyal-Javani 

خب گازل هم از کرل استفاده میکنه شما بیشتر بررسی کن یه تنظیمات خاصی حتما وجود داره. درخواست از نوع پست زدی؟

مشکلی که گفتی توی این پکیج هست؟

**Comment by Daniyal-Javani** [comment]
بله با همین پکیج هست
و اره پست هست، همه چیشو تست کردم

**Comment by Daniyal-Javani** [comment]
@khanzadimahdi 
مطمینی برای بقیه جواب میده؟
میخوایی یه نگاه بهش بندازی

**Comment by khanzadimahdi** [comment]
<div dir="rtl">
روی سرور اصلی تست کردین؟ همون سروری که ایپیشو توی بانک ست کردین؟

قطعا یه نگاه میندازم اما دسترسی های لازم رو ندارم و نیاز دارم که دسترسی بدین بهم

</div>

**Comment by Daniyal-Javani** [comment]
بله روی سرور اصلی هست و اون کد خود بانک هم جواب میده
چک کنید که عالی میشه، توی واتس اپ ارسال کردم براتون
بازم ممنون

**Comment by khanzadimahdi** [comment]
@Daniyal-Javani 

اوکی مرسی از همکاری شما

نتیجه رو هم توی واتس اپ و هم همینجا اعلام میکنم بهتون که باقی دوستان هم بدونن ماجرا از چه قرار بوده

**Comment by khanzadimahdi** [comment]
@Daniyal-Javani 
@mratwan 

Sadad gateway responses will be 500 if any guzzle default user-agent exists!!! 
so we MUST send an empty user-agent to Sadad in our requests.

update shetabit/multipay to its latest version.

https://github.com/shetabit/multipay/commit/d32b9c819fcd95962e49219774ff3a8df3e2c6cf

----

درگاه قبلا کار میکرد اما یهو از کار افتاد!!!! من چک کردم دیدم که جدیدا درگاه سداد یوزر ایجنت رو هم بررسی میکنه و اگه خالی نباشه رسپانس پونصد میده و درخواست رو بلوکه میکنه

پکیج خودتون رو به اخرین ورژن اپدیت کنید این مشکل الان باید رفع شده باشه
