### ISSUE TITLE
استفاده از ریال به جای تومان

### ISSUE THREAD

**Issue by gohari** [shetabit/payment#76]
سلام و احترام
من از زرین پال استفاده میکنم چطور میتونم به جای تومان از ریال اسفاده کنم؟

**Comment by khanzadimahdi** [comment]
سلام. تمامی مبلغ های درون پکیج تومان هستند. در صورت مغایرت توی گیت هاب پکیج
issue ایجاد کنید تا بررسی کنم.

شما قیمتی که به پکیج میدین باید تومان باشه! اگه قیمت های سیستم کنونی شما
ریال هست خب اونا رو تقسیم بر 10 کنید تا به تومان تبدیل بشن و سپس از پکیج
استفاده کنید.

موفق باشید.

**Comment by gohari** [comment]
قیمت رو به ریال تبدیل میکنم میگه باید integer باشه
Amount value should be an integer.

**Comment by khanzadimahdi** [comment]
<div dir="rtl">

مطمعنی مبلغی که تبدیل میکنی عدد صحیح هست؟

عددی که تبدیل میکنی رو توی صفحه var_dump کن ببین نوعش چیه

</div>

**Comment by khanzadimahdi** [comment]
میتونی از روش زیر استفاده کنی :

```php
$amount = (int) $amount / 10;
```

**Comment by gohari** [comment]
عدد من میشه 12345 ریال اما پکیج تومان در نظر میگره من تقسیم به ده میکنه میشه 1234.5

**Comment by khanzadimahdi** [comment]
<div dir=rtl>
اگه باگ یا مشکلی وجود داره لطفا یک issue جدید ایجاد کنید. مرسی از شما
</div>
