### ISSUE TITLE
Wrong parameters for PurchaseFailedException

### ISSUE THREAD

**Issue by mrmkhn** [shetabit/payment#77]
Hi,
I use this package to handle my payments using behpardakht gateway. I got this error :

Symfony\Component\Debug\Exception\FatalThrowableError
Wrong parameters for Shetabit\Payment\Exceptions\PurchaseFailedException([string $message [, long $code [, Throwable $previous = NULL]]])

 please help me.Thanks.

**Comment by khanzadimahdi** [comment]
could you tell me how you use the pakage? let me see your payment codes.

**Comment by khanzadimahdi** [comment]
The `PurchaseFaildedExeption` will be throw whenever purchasing payment fails.
here your purchase has failed.

but wrong parameters is  a bug!!!! can you go to the below path

```php
vendor/shetabit/payment/src/Drivers/Behpardakht/Behpardakht.php
```
and on line 62 put the below code and tell me what you see after running the code?

```php
dd($response);
```

the first parameter of `PurchaseFailedException` must be string (in line 65). I want to sure `$response` is string !!!!

**Comment by mrmkhn** [comment]
![payment](https://user-images.githubusercontent.com/46655073/83975860-5ab88d00-a90b-11ea-8b6b-f1dc6f0360ee.PNG)
![paymentController](https://user-images.githubusercontent.com/46655073/83975905-a9febd80-a90b-11ea-9c80-955a0ff65d05.PNG)

**Comment by khanzadimahdi** [comment]
your codes seems good. 
can you put `dd` on line `62` of the below file and see what the response is?

```
vendor/shetabit/payment/src/Drivers/Behpardakht/Behpardakht.php
```

**Comment by mrmkhn** [comment]
I wrote this code in my file.but it didn't  workout .should i do some thing for making change or restart something?

**Comment by khanzadimahdi** [comment]
no need to do more things. 

it must work! i can't recognize your problem. can you fix it and send a pull request?

**Comment by mrmkhn** [comment]
This is my result after dd response:
![dd-result](https://user-images.githubusercontent.com/46655073/83977316-f4386c80-a914-11ea-9ab7-1a22d7fb081d.PNG)

**Comment by khanzadimahdi** [comment]
here is error codes : your error code is 23

0 = تراکنش با موفقیت انجام شد
11 = شماره کارت نامعتبر است
12 = موجودی کافی نیست
13 = رمز نادرست است
14 = تعداد دفعات وارد کردن رمز بیش از حد مجاز است
15 = کارت نامعتبر است
16 = دفعات برداشت وجه بیش از حد مجاز است
17 = کاربر از انجام تراکنش منصرف شده است
18 = تاریخ انقضای کارت گذشته است
19 = مبلغ برداشت وجه بیش از حد مجاز است
21 = پذیرنده نامعتبر است
23 = خطای امنیتی رخ داده است
24 = اطلاعات کاربری پذیرنده نامعتبر است
25 = مبلغ نامعتبر است
31 = پاسخ نامعتبر است
32 = فرمت اطلاعات وارد شده صحیح نمی باشد
33 = حساب نامعتبر است
34 = خطای سیستمی
35 = تاریخ نامعتبر است
41 = شماره درخواست تکراری است
42 = یافت نشد Sale تراکنش
43 = قبلا درخواست Verify داده شده است
44 = درخواست Verfiy یافت نشد

**Comment by khanzadimahdi** [comment]
<div dir=rtl>
درگاه رو روی سرور اصلی که به بهپرداخت معرفی کردین تست کردین؟ باید روی همون سرور تست کنید در غیر اینصورت کار نمیکنه
</div>

**Comment by mrmkhn** [comment]
بله دقیقا مشکل همین هستش.روی اون سرور تست نمیکردم.سپاس فراوان
