### ISSUE TITLE
Problem of using Rial and converting to Toman (مشکل با ریال)

### ISSUE THREAD

**Issue by gohari** [shetabit/payment#79]
با سلام
پیرو بحث #76 مبلغ رو باید به ریال بفرستم درگاه و با تقسیم کردن مبلغ به ده مشکل حل نمیشه
اگر Amount رو از integer به float تغییر بدید مشکل حل میشه
یا اگر راه حل دیگه ای هستش بفرمایید
باتشکر

**Comment by khanzadimahdi** [comment]
میشه کدی که توش مبلغ رو تقسیم بر 10 کردین رو قرار بدین؟

**Comment by khanzadimahdi** [comment]
<div dir="rtl">
روش زیر رو امتحان کردین؟ مبلغ اعشاری توی دنیای واقعی وجود خارجی نداره و به همین دلیل به هیچ وجهه نمیشه مبالغ رو اعشاری استفاده کرد. حتما باید صحیح باشن

</div>

```php
//گرد به سمت پایین
$amount = (int) $amount / 10;

// گرد به سمت بالا
$amount = ((int) $amount / 10) + ($amount % 10 ? 1 : 0); 
```

**Comment by gohari** [comment]
مشکلی با تبدیل ریال به تومن ندارم
`$amount = (int) round($amount / 10);`
مشکل اینجاست که نمیخوام ریال صورت حساب تبدیل به صفر بشه چون فاکتور ها بهم میریزه 
در روشی که شما میفرمایید مبلغ 1234 ریال تبدیل میشه به 1230 ریال

 احتمالا پکیج داره واسه بانک عدد رو  ضرب در 10 میکنه یا یک صفر بهش اضافه میکنه و میفرسته بانک، خود بانک که تبدیل نمیکنه
اگر ضرب کنه اینطوری integer شما به float تغییر پیدا کنه مشکلی پیش نمیاد

حرف شما درسته عدد اعشاری اشتباه هستش اما وقتی سایت من و درگاه بانک و ... دارن با ریال کار میکنن چه میشه کرد؟

**Comment by khanzadimahdi** [comment]
<div dir="rtl">

پکیج برای درگاه زرین پال هیچ تغییراتی روی مبلغ انجام نمیده. زرین پال کلا با تومان کار میکنه و شما باید مبلغ رو تومان ارسال کنید


مبلغی که کاربر قراره پرداخت کنه را رو به بالا گرد کنید مشکلی پیش نمیاد براتون. کسری مبلغ پیدا نمیکنید

این مورد رو نمیشه کاریش کرد باید با یک رویکرد مناسب مشکل رو رفع کنید

من پیشنهاد میکنم مبلغ را رو به بالا گرد کنید

</div>
