### ISSUE TITLE
Error  - The authority must be 36 characters

### ISSUE THREAD

**Issue by bobper** [shetabit/payment#8]
Hi
I gave this error

{"Status":-11,"Authority":"","errors":{"Authority":["The authority must be 36 characters."]}}
--
 من این خطا رو میگیرم - ایشیو شماره 7 رو هم خوندم 
همین مشکل رو داشتن ولی راه حلی داده نشده 
الان خروجی که توی کالبک بهم برمیگردونه اینه 
http://test.loc/zarinpal/annaul/callback/22086?Authority=100000000000000000000000000129647210&Status=NOK
همونطوری مشخصه authority فرستاده شده 
ولی فانکشن نمیفهمه 
دلیلش چی میتونه باشه 
من خط به خط دنبال کردم
رسیدم به این خط 
فایل

namespace Shetabit\Payment\Drivers;

فانکشن 
verify(){
...
 $response = $this->client->request(
            'POST',
            $this->settings->apiVerificationUrl,
            ['json' => $data]
        );

}

اینجا به بعد دیگه جلو نمیره - ممنون میشم راهنمایی کنید

**Comment by khanzadimahdi** [comment]
سلام.

ایشو شماره هفت دلیل دیگه ای داشت که مربوط به یکی از افزونه های پی اچ پی میشد

در هنگام وریفای کردن تراکنش باید شماره تراکنش هم با اون ارسال بشه به صورت زیر باید عمل کنید

```php
# On the top of the file.
use Shetabit\Payment\Facade\Payment;
use Shetabit\Payment\Exceptions\InvalidPaymentException;
...

# you need to verify the payment to insure the invoice has been paid successfully
// we use transaction's id to verify payments --> مشکل شما به این خاطر هست
// its a good practice to add invoice's amount.
// $transaction_id --> در خط زیر به این قسمت دقت کنید
try {
	Payment::amount(1000)->transactionId($transaction_id)->verify();
    ...
} catch (InvalidPaymentException $exception) {
    /*
    	when payment is not verified , it throw an exception.
    	we can catch the excetion to handle invalid payments.
    	getMessage method, returns a suitable message that can be used in user interface.
    */
    echo $exception->getMessage();
}
```
مشکل شما به دلیل عدم ارسال شماره تراکنش هست اگه دقت کرده باشید توی پیام خطا خالی نمایش داده میشه. به کد بالا دقت کنید

**Comment by khanzadimahdi** [comment]
در صورتی که تراکنش موفق امیز نباشه اکسپشن ایجاد میشه که در قسمت کچ میتونید اونو به راحتی مدیریت کنید. 

در کدی که گذاشتم من پیام اکسپشن رو توی صفحه نمایش میدم
