### ISSUE TITLE
مشکل در وریفای کردن درگاه زرین پال

### ISSUE THREAD

**Issue by Zakariaair** [shetabit/payment#81]
سلام
من پکیج شما رو نصب کردم. روی درگاه زرین پال وقتی متد پرداخت رو اجرا میکنم همه چیز درست کار میکنه. بعد زمانی که ویریفای رو اجرا میکنم با خطای
_عملیات پرداخت توسط کاربر لغو شد_
مواجه میشم.

درضمن دارم روی لوکال کارمیکنم و
sandbox
زرین پال رو تست کردم.

لطفا کمک کنید، ممنون

**_pay:_**
`$paymentInvoice = new Invoice();`
`        $paymentInvoice->amount($amount->totalPay);`
`        $paymentInvoice->uuid($invoiceid->id);`
`        $result = Payment::purchase($paymentInvoice, function($driver, $transactionId) use($invoiceid){  })->pay()->toJson();`
`        return json_decode($result);`

**_verify:_**
`$receipt = Payment::transactionId($token)->verify();`

**_result:_**
`message: 'عملیات پرداخت توسط کاربر لغو شد.'`

**Comment by khanzadimahdi** [comment]
<div dir="rtl">

سلام. مرسی از اینکه مشکل رو گزارش دادین. مشکل الان رفع شده. میتونید پکیج رو اپدیت کنید و به کار خودتون ادامه بدید

دستور زیر رو بزنید تا پکیج اپدیت بشه
</div>

```bash
composer update
```

**Comment by Zakariaair** [comment]
متاسفانه مشکل حل نشده.
آدرس کالبک با استاتوس
OK
برمیگرده. اما پاسخ وریفای همچنان تغییری نکرده در حالت
sandbox
**_URL_**
`/callback?Authority=000000000000000000000000000000109574&Status=OK`
**_عکس_**
![zarinbug](https://user-images.githubusercontent.com/22242388/84770566-0ab58680-afed-11ea-9f67-48b77072cea0.JPG)

**Comment by khanzadimahdi** [comment]
<div dir="rtl">
امکانش هست ورژن پکیج خودتون رو ذکر کنید؟
</div>

**Comment by Zakariaair** [comment]
بله البته.. همین امروز آپدیت کردم
**_composer.lock_**
`"name": "shetabit/payment",
            "version": "v3.0.1",`

**_composer.json_**
`"shetabit/payment": "^3.0",`

**Comment by khanzadimahdi** [comment]
<div dir="rtl">
ورژن shetabit/multipay رو هم میشه ذکر کنید. ممنونم از شما

</div>

**Comment by Zakariaair** [comment]
ورژن یکه
`"name": "shetabit/multipay",
            "version": "v1.0",`

**Comment by khanzadimahdi** [comment]
<div dir="rtl">
مشکل از ورژن multipay هست که توی کامپوزر لاک کش شده

فایل کامپوزر لاک رو پاک کنید و دوباره دستور کامپوزر اپگرید رو اجرا کنید مشکل حل میشه

ورژن مالتی پی باید اخرین ورژنش باشه که الان اینطور نیست

</div>

**Comment by Zakariaair** [comment]
درسته.. توی راهنمای shetabit/payment اسمی از multipay
نبود به همین خاطر فکر کردم اپدیت همون کافی باشه

اما هنوزم همون مشکل وجود داره

با این دستور آپدیتش کردم
`> composer update shetabit/multipay
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 0 installs, 1 update, 0 removals
  - Updating shetabit/multipay (v1.0 => v1.0.1): Downloading (100%)`

**Comment by Zakariaair** [comment]
**_composer.lock_**
`"name": "shetabit/multipay",
            "version": "v1.0.1",`

**Comment by khanzadimahdi** [comment]
مطمئن هستید مشکل رفع نشده؟ لطفا یکبار دیگه بررسی کنید و تست کنید

**Comment by khanzadimahdi** [comment]
من روی سیستم خودم چک کردم درگاه زرین پال به درستی کار میکنه. باید روی سیستم شما هم این مشکل رفع شده باشه

**Comment by khanzadimahdi** [comment]
<div dir="rtl">

لطفا اگه بازم مشکل دارید کدهایی که نوشتین رو اینجا قرار بدید تا بررسی کنم. کدهای مرتبط با پرداخت

</div>

**Comment by Mojtaba118** [comment]
سلام.
منم دقیقا همین مشکل رو دارم.
ورژن پکیج:
composer.lock
 "name": "shetabit/multipay", "version": "v1.8.4"
ممنون میشم راهنمایی کنید!

**Comment by khanzadimahdi** [comment]
سلام. کانفیگ رو پاک کنید و دوباره پابلیش کنید

کش کانفیگ رو نیز پاک کنید

اگه مشکل حل نشد اطلاع بدید تا باهم چک کنیم

**Comment by msmsas167** [comment]
سلام وقتتون بخیر ... منم همین مشکلو دارم و نکاتی که گفتید رو انجام دادم ولی همچنان همون پیغامو میده
توی کمپوزر لاک دوتا ورژن هست :
"name": "shetabit/multipay",
            "version": "v1.16.0",
            "source": {
                "type": "git",
                "url": "https://github.com/shetabit/multipay.git",
                "reference": "8b9470a616cf1b3a8f1745795335200ad4f39592"
            },
و

"require": {
                "illuminate/broadcasting": "^5.0|^6.0|^7.0|^8.0|^9.0",
                "illuminate/support": "^5.0|^6.0|^7.0|^8.0|^9.0",
                "php": ">=7.2",
                "shetabit/multipay": "^1.0"
            },


کدی که درخواست به درگاه انجام میشه:

$invoice = new Invoice;
            $invoice->amount(1000);
            $resultpay = Payment::purchase($invoice, function ($driver, $transactionId) {})
                ->pay()->toJson();


و کدی که قراره درخواست وریفای انجام بشه:

use Shetabit\Multipay\Exceptions\InvalidPaymentException;
use Shetabit\Multipay\Invoice;
use Shetabit\Payment\Facade\Payment;

$transaction = \DB::table('transaction')
            ->where('transaction_id', $request->transaction_id)
            ->first();

try {
            $receipt = Payment::amount(1000)->transactionId($transaction->transaction_id)->verify();
            $result = $receipt->getReferenceId();
        } catch (InvalidPaymentException $exception) {
            $result = $exception->getMessage();
        }
        return $result;

**Comment by daniyal1396m** [comment]
سلام من میخوام یه پرداخت انجام بدم  نمیدونم چیو باید بنویسم و چطور انجام بدم ارور {message: "خطای اعتبار سنجی", exception: "Shetabit\Multipay\Exceptions\PurchaseFailedException",…}
 میگیرم   لططفا نمونه کد میدید با تشکر

**Comment by khanzadimahdi** [comment]
@REZA63686 چه محصولی؟
