### ISSUE TITLE
pay()-render(); does not working

### ISSUE THREAD

**Issue by mratwan** [shetabit/payment#82]
زمان استفاده از 
// Do all things together in a single line.
return $payment->purchase(
    (new Invoice)->amount(1000), 
    function($driver, $transactionId) {
    	// Store transactionId in database.
        // We need the transactionId to verify payment in the future.
	}
)->pay()->render();

با خطای زیر مواجه می شوم

Call to undefined method Illuminate\Http\RedirectResponse::render();

**Comment by khanzadimahdi** [comment]
<div dir="rtl">
سلام. میشه ورژن پکیجی که استفاده میکنید رو درج کنید؟
</div>

**Comment by khanzadimahdi** [comment]
if your version is **lower than 3.0.0** , follow the former docs from the below link

https://github.com/shetabit/payment/tree/v2.4.7

**Comment by mratwan** [comment]
laravel 5.8
"shetabit/payment": "^2.4"

**Comment by khanzadimahdi** [comment]
برای ورژن های پایین تر از ۳ داکیومنت های زیر رو بخونید و استفاده کنید

https://github.com/shetabit/payment/tree/v2.4.7

**Comment by khanzadimahdi** [comment]
توی ورژن های پایین تر از ۳ طبق داکیومنت متد رندر نداریم

داکیومنت ها رو بررسی کنید

**Comment by mratwan** [comment]
ممنونم
کار کرد ولی نمیدونم چرا وقتی از پرداخت انصراف میدم، برمیگرده و دوباره  برمیگرده به صفحه پرداخت بعد از ریدایرکت و حالا یا همون درگاه میاد یا درگاه دیگه ای...

**Comment by khanzadimahdi** [comment]
<div dir="rtl">

چون توی ادرس callbackUrl ادرس صفحه کنونی رو قرار دادین و پس از پرداخت برمیگرده دوباره توی همون صفحه و لوپ میشه دوباره به صفحه پرداخت

</div>

**Comment by khanzadimahdi** [comment]
یه نگاهی به لینک زیر بندازید مشکلتون رفع میشه

https://github.com/shetabit/payment/tree/v2.4.7#callbackurl-can-be-used-to-change-callbackurl-on-the-runtime

میتونید از متد کالبک برای تنظیم ادرس برگشتی از درگاه استفاده کنید البته در صورتی که ادرس داینامیک باشه

درصورتی هم که ادرس های برگشت از درگاه داینامیک نیست میتونید درون فایل کانفیگ اونا رو تنظیم کنید
