### ISSUE TITLE
Shetabit\Multipay\Exceptions\PurchaseFailedException خرید موفقیت‌آمیز نبود

### ISSUE THREAD

**Issue by mrmkhn** [shetabit/payment#86]
با سلام و عرض ادب
من از درگاه به پرداخت ملت استفاده میکنم.این کدها و اروری که دریافت میکنم.ممنون میشم بفرمایید مشکل از کجاهستش
![pamentError](https://user-images.githubusercontent.com/46655073/87843238-2354dd00-c8c8-11ea-8072-a71160d8ffd1.PNG)
![paymentFile](https://user-images.githubusercontent.com/46655073/87843241-251ea080-c8c8-11ea-8319-df50408d99e1.PNG)
![pamentcontroller](https://user-images.githubusercontent.com/46655073/87843242-264fcd80-c8c8-11ea-80e3-d048653fe3c4.PNG)

**Comment by khanzadimahdi** [comment]
سلام. درگاه های مستقیم بانکی رو باید روی  سرور اصلی تست کنید چون نسبت به ایپی سرور حساس هستند

**Comment by mrmkhn** [comment]
روی سرور اصلی هم دقیقا همین ارور رو داریم

**Comment by khanzadimahdi** [comment]
کش کانفیگ های خودتون رو پاک کردین؟

```php
dd(config("payment"));
```

دستور بالا رو چک کنید ببینید کانفیگ ها درست نمایش داده میشن

**Comment by khanzadimahdi** [comment]
اگه مشکلتون حل نشد به مسیر زیر برید و خروجی رو ببینید چیه و اطلاع بدید

vendor/shetabit/multipay/src/Drivers/Behpardakht/Behpardakht.php

بعدش خروجی خط 63 رو توی صفحه ببینید چیه

```php
 $data = explode(',', $response->return);
dd($data);
```

**Comment by mrmkhn** [comment]
عدد 23 برگردوند
کانفیگ هام چک کردم درست نمایش میده

**Comment by mrmkhn** [comment]
مشکل امنیتی هست انگار ولی  روی سرور اصلی نمیدونم چرا باید خطای امنیتی داشته باشیم.

**Comment by khanzadimahdi** [comment]
نمونه کد خودشو روی سرور ران کردین؟ نمونه کدی که خود بهپرداخت میده منظورمه. 

یه کد کوچیک داره خارج از لاراول رانش کنید ببینید ران میشه یا نه

**Comment by khanzadimahdi** [comment]
لطفا مشکل رو بررسی کنید تا رفع کنیم. اگه راه حلی پیدا کردین و مشکل از جای دیگه ای بوده لطفا اطلاع بدید تا باقی دوستانی که از پکیج استفاده میکنن در جریان قرار بگیرن. ممنونم

**Comment by mrmkhn** [comment]
مشکل حل شد و خطای امنیتی از جانب بانک بود
ممنون از پاسخگویی  خوب شما
