### ISSUE TITLE
ست کردن آدرس بازگشت های متفاوت  و  ذخیره کردن توکن

### ISSUE THREAD

**Issue by bobper** [shetabit/payment#9]
واقعیتش یه کم برای من گیج کننده است.
فرض کنید ما توی سایت قراره فایل بفروشیم 
هر فایلی یه آیدی داره و بعد از پرداخت انتظار داریم برگردیم به صفحه مربوط به همون فایل
و بتونیم فایل رو دانلود کنیم 
توی این حالت باید از این متد استفاده کنیم!
و قبلش باید تراکنش رو ذخیره کنیم و براساس آیدی تراکنش آدرس بازگشت رو بسازیم
حالا چطوری میتونیم توکنی که از سایت برمیگرده رو بذاریم توی دیتابیس با همون تراکنشی که ساختیم ؟ 
$transactionId 
رو  ذخیره کنیم توی تراکنشی که قبلا ساختیم و باهاش آدرس بازگشت ساختیم؟

return Payment::callbackUrl($url)->purchase(
            $invoice,
            function($driver, $transactionId ) {
                // we can store $transactionId in database

            }
        )->pay();

**Comment by khanzadimahdi** [comment]
سلام

در هنگام برگشت از درگاه شما باید یه توکن داشته باشید تا متوجه بشید کدوم تراکنش برگشت داده شده حالا میخواد ایدی تراکنش باشه یا توی سشن ذخیره شده باشه یا هرچیز دیگه

**Comment by khanzadimahdi** [comment]
با متد کال بک میتونید ادرس برگشت رو داینامیک مشخص کنید.

بهتره که تراکنش ها رو درون دیتابیس ذخیره کنید و بعدش به صورت مدل بایندینگ ادرسشو استفاه کنید مثلا به صورت زیر

http://yoursite.com/invoice/1

حالا جایی که ایدی برابر با ۱ هست رو میگیریم و با توجه به کد تراکنش (باید ذخیره کنیم در دیتابیس) میتونیم تراکنش رو وریفای کنیم
