### ISSUE TITLE
مشکل در بازگشت از بانک

### ISSUE THREAD

**Issue by mehdi7618** [shetabit/payment#90]
سلام، خسته نباشید

بعداز اینکه به درگاه بانک میرم، در بازگشت (هر حالتی) به صفحه کال بک ، متاسفانه با متن زیر روبه رو میشم:
Sorry, your session has expired. Please refresh and try again. 
البته حتی در روت صفحه ارسال و دریافت رو مستقیم قرار دادم ولی باز این حالت پیش میاد
`Route::get('pay111',function(){
    return \Shetabit\Payment\Facade\Payment::callbackUrl('http://localhost/shop/public/order_i')->purchase(
        (new \Shetabit\Multipay\Invoice())->amount(1234),
        function($driver, $transactionId) {
            // store transactionId in database.
            // we need the transactionId to verify payment in future
        }
    )->pay()->render();
});

Route::any('order_i', function (Request $request) {
    dump($request);
});
`

لطفا راهنمایی بفرمایید

**Comment by khanzadimahdi** [comment]
<div dir="rtl">
لطفا کدهای خودتون رو به صورت مرتب و خوانا بزارید الان معلوم نیست چی به چیه و اصلا نمیشه خوند

مشکل شما به دلیل csrf هست. روی اون ادرسی که قراره از درگاه برگرده غیر فعالش کنید دلیلش هم این هست که برخی بانک ها به صورت متد post ریدایرکت میشن روی سایت شما و لاراول برای درخواست های post همیشه csrf رو چک میکنه

</div>

**Comment by mehdi7618** [comment]
خیلی ممنون بله حل شد
در فایل زیر روت خودم رو وارد کردم

app->Http->Middleware->VerifyCsrfToken.php

class VerifyCsrfToken extends BaseVerifier
{ 
      protected $except = [ 
          **'order'**
      ];
}
