### ISSUE TITLE
دیتابیس

### ISSUE THREAD

**Issue by shirazsoft** [shetabit/payment#92]
سلام
وقت بخیر
آیا این سیستم 
log
و
ثبت دیتا بیسی ندارد؟

**Comment by khanzadimahdi** [comment]
سلام. اطلاعات رو میتونید خودتون با توجه به نیازتون ثبت کنید

این پکیج فقط پرداخت ها رو مدیریت میکنه و هیچ لاگ یا ثبت اطلاعاتی براتون انجام نمیده
