### ISSUE TITLE
درگاه فن آوا کارت

### ISSUE THREAD

**Issue by MadMEMb55** [shetabit/payment#93]
سلام
بنده مستندات + درگاه تایید شده از فن آوا کارت رو دارم ممنون میشم یه راه ارتباطی توی تلگرام معرفی کنید تا به دستتون برسونم
اگه تونستید شما پیام بدید که خیلی خوبه و سریعتر کار انجام میشه
آیدی تلگرام بنده : Stoyt

**Comment by khanzadimahdi** [comment]
<div dir="rtl">
سلام یه نگاه انداختم به لینک زیر 

https://www.google.com/search?q=%D9%81%D9%86+%D8%A2%D9%88%D8%A7+%DA%A9%D8%A7%D8%B1%D8%AA&oq=%D9%81%D9%86+%D8%A2%D9%88%D8%A7+%DA%A9%D8%A7%D8%B1%D8%AA&aqs=chrome..69i57j0l5j69i61l2.318j0j1&sourceid=chrome&ie=UTF-8

مثل اینکه درگاه خوبی نیست چون مردم نظرهای منفی زیادی گذاشتن. 

به هر حال میتونید خودتون درگاه رو اظافه کنید. توی مستندات پکیج نحوه افزودن درگاه درج شده.

بعد از اظافه کردن درگاه درخواست مرج بدید تا بررسی کنم و در صورتی که مشکلی نداشت به پکیج اظافه میشه

</div>
