### ISSUE TITLE
عدم ایجاد فایل config/payment.php

### ISSUE THREAD

**Issue by mohammad5525** [shetabit/payment#97]
هرکاری میکنم
config/payment.php
ایجاد نمیشه . فایلشم هیچ جا نیست که بتونم حتی کپی هم بگیرم ازش

**Comment by khanzadimahdi** [comment]
سلام. دستور زیر را درون ترمینال اجرا کنید

‍‍‍```bash
php artisan vendor:publish
```
میتونید از مسیر زیر فایل رو کپی بگیرید اما من این راه رو پیشنهاد نمیکنم 

```bash
vendor/shetabit/multipay/config/payment.php
```
